dalathegreat/Battery-Emulator

Software/Software.ino

This PR adds a new LED state, Blue, which indicates that there is a problem with the CAN wiring. The reasons for this error can be:
- Swapped CAN High and Low wires
- Incorrect termination resistance
- Missing battery completely on CAN
This should help simplify troubleshooting!

Add Blue LED state for CAN errors

---

Software/NISSAN-LEAF-BATTERY.cpp
Software/NISSAN-LEAF-BATTERY.h
Software/Software.ino

- Rewrite LED handling to handle more colors
- Add parameter to signal from inverter side that contactor closing is OK (needed for e.g. Solax protocol)
Nissan LEAF specifics:
- Add alarm if mV diff goes over 500mV (and trigger yellow LED)
- LB_Charge_Power_Limit  is now read properly from the CAN data
- Poll all the 7bb groups actively from the battery. Read more data from the LEAF pack
- Add inverterAllowsContactorClosing parameter
- Fix so battery temperature is read properly by ZE0 and ZE1 (previously was only OK on AZE0)

Leaf current sensor

---

Software/Software.ino

Modbus server is now turned off incase it is not used. This saves some CPU cycles, reduces dynamic memory usage by 19% and also reduces 1% of program storage space.

Add ifdefs for modbus server

---

Software/CAN.c
Software/ESP32CAN.cpp
Software/ESP32CAN.h
Software/Software.ino

⚠️ Safety improvement. This PR prevents the board from crashing incase a CAN write fails. 
It also changes:
- CAN failure state is now signaled with pulsing blue LED
- LED brightness decresed on normal states

Add timeout to CAN write to prevent crashing

---

Software/TESLA-MODEL-3-BATTERY.cpp
Software/TESLA-MODEL-3-BATTERY.h

Add configurable option to skip HVIL requirement on Tesla Model 3 batteries. See wiki for downsides

Tesla HVIL bypass

---

Software/NISSAN-LEAF-BATTERY.cpp
Software/NISSAN-LEAF-BATTERY.h
Software/TESLA-MODEL-3-BATTERY.cpp
Software/TESLA-MODEL-3-BATTERY.h

- CAN still alive now read from BMS message
- Add contactor opening incase of a FAULT situation
- Add HVIL safety
- Cell voltages now mapped to inverter values (both Tesla and Nissan LEAF)
- Charge max value for Tesla Model3 now estimated

Tesla 3 contactor opening

---

Software/NISSAN-LEAF-BATTERY.cpp

This PR fixes the following for the Nissan LEAF packs
- Active polling now paused for 100s when Leafspy detected. 
- Fixed an issue where LED became yellow if Leafspy was turned on while cell monitoring was performed.
- Added error code 10, when too many corrupted CAN messages detected
- Fixed scaling of LB_Current, A/W values no longer show 2x the real amount
- Only the temperature min/max values used by the inverter are printed to USB

Leaf leafspy

---

Software/INVERTERS.h
Software/SMA-CAN.cpp
Software/SMA-CAN.h
Software/Software.ino
Software/TESLA-MODEL-3-BATTERY.cpp
Software/TESLA-MODEL-3-BATTERY.h
Software/USER_SETTINGS.h

This PR adds support for a new inverter CAN protocol, "BYD Battery-Box H 8.9kWh, 7 modules". It can be enabled by defining the following line in `USER_SETTINGS.h`
//#define SMA_CAN

SMA BYD CAN

---

Software/BYD-CAN.cpp

This PR fixes the capacity BYD batteries report themselves over CAN as. For instance Sungrow inverters have shown "BYD 5.1kWh" due to hardcoded capacity message sent. Now the user defined battery size (set in `USER_SETTINGS.h`) will be sent over CAN to the inverter. Cosmetic fix, but feels better to see larger more realistic values on screen :)

Fix kWh identifier for BYD CAN

---

Software/PYLON-CAN.cpp

This PR adds the ability to change between sending Pylon CAN messages ending with 0 or 1. This is useful for some inverters, like Sofar inverters.
In the PYLON-CAN.cpp file you can change which ID the messages should have.

Add ID ending with 1

---

Software/INVERTERS.h
Software/SOFAR-CAN.cpp
Software/SOFAR-CAN.h
Software/Software.ino
Software/USER_SETTINGS.h

This PR adds the skeleton needed for Sofar CAN, extended protocol V1.0.001 20201106
Note, this is not fully completed, the CAN sending routine needs work for the inverter replies. Adding this information to the Wiki, so that anyone that needs Sofar CAN to work can continue on it.

Add Sofar CAN

---

.github/workflows/compile-arduino-sketch.yml

This pull request adds a GitHub Action that runs on each push and each pull request, to check that the Arduino sketch compiles.
It does this by means of the [arduino/compile-sketches](https://github.com/arduino/compile-sketches) action.

add GitHub Action that compiles Arduino sketch for ESP32

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp
Software/src/battery/TESLA-MODEL-3-BATTERY.h

This PR adds the following new functionality/fixes for the Tesla batteries
- Autodetect LFP or NCA/NCM chemistry. 🔋  These two battery types have different voltage limits, and the code now can select the correct limits automatically
- 50 new fault codes added! ⚠️ The error matrix from 0x3AA is now fully decoded, and the software will alert you if one of them is triggered. Example, `"ERROR: Pack discharge current is above the safe max discharge current limit!"` and another example, `"ERROR: shunt current reading is not available"`
- RealSOC now visible in the USB printout. Previously this value was overwritten instantly by the rescaled value heading towards inverter

Tesla Model3 debug improvements

---

Software/Software.ino
Software/USER_SETTINGS.h
Software/src/battery/BATTERIES.h
Software/src/inverter/BYD-MODBUS.cpp
Software/src/inverter/BYD-MODBUS.h
Software/src/inverter/INVERTERS.h
Software/src/inverter/LUNA2000-MODBUS.cpp
Software/src/inverter/LUNA2000-MODBUS.h

This pull request updates the file names and macros for naming consistency, and it orders macros alphabetically.
Consistency and alphabetical ordering allows easier checking if the code is complete.
Some examples of changes that were made:
- macro update: `CAN_BYD` --> `BYD_CAN` (as all other macros first start with the name of the vendor, followed by the protocol)
- file name update: `MODBUS_LUNA2000.cpp` --> `LUNA2000_MODBUS.cpp` (as other filenames start with the name of the vendor, followed by the name of the protocol)
By ordering the macros alphabetically, I found that:
- a notification of which inverter is used in case of `PYLON_CAN` was missing 
- a notification of which battery is used in case of `CHADEMO_BATTERY` was missing
Both these notifications are now added.

Update file naming and macro naming for consistency, add missing notifications for PYLON_CAN and CHADEMO_BATTERY

---

Software/Software.ino

In pull requests #80 I made a small mistake, causing the code to not compile anymore for the:
- PYLON inverter
I also found some other mistakes, that were already existing before pull request #80, causing the code to not compile for the:
- CHADEMO battery
This pull request fixes these issues.
**Details on the mistake I made:**
I forgot a `;` at the end of this line:
https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/blob/2575fcc190aa3edaff9c1c727993d5da1f2ac4a8/Software/Software.ino#L203
**Details on the existing issues**
These functions are not declared:
https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/blob/2575fcc190aa3edaff9c1c727993d5da1f2ac4a8/Software/Software.ino#L275
https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/blob/2575fcc190aa3edaff9c1c …

Fix: syntax error for PYLON inverter and function errors for CHADEMO battery

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp

Added the known working delay for sending 221 messages, from pelle_c. Now it should be possible to open contactors in a fault scenario.
Also removed an unused Amp value in USB debug printout, this confused users

Bugfix/contactor opening for Tesla

---

.gitignore

This pull request updates the `.gitignore` file to ignore any `.vscode` folder, independent of its location.
Previously only the `.vscode` folder found in the directory `Software/` was ignored.

Update .gitignore to ignore any .vscode folder

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp

Noticed by @Newevg , that the scaling on the current reported by Tesla batteries does not contain decimals. This makes the current value used by inverters not match up with reality.
Example, Nissan LEAF pack reports (130) when 13.0A of current is pulled from the battery. The Tesla Model 3 pack report 13 when 13.0A of current is pulled from the battery.
The fix is to multiply the current value with *10 to get the value to match up with the rest of the system

Tesla: Increase decimal on Amperage value

---

Software/src/battery/BMW-I3-BATTERY.cpp
Software/src/battery/CHADEMO-BATTERY.cpp
Software/src/battery/IMIEV-CZERO-ION-BATTERY.cpp
Software/src/battery/TESLA-MODEL-3-BATTERY.cpp
Software/src/inverter/LUNA2000-MODBUS.cpp
Software/src/inverter/PYLON-CAN.cpp
Software/src/inverter/SMA-CAN.cpp
Software/src/inverter/SOFAR-CAN.cpp
Software/src/inverter/SOLAX-CAN.cpp

This pull request updates the formatting of all TODOs found in the src folder.
It updates all TODOs as `TODO:`
This is done such that the TODOs can be more easily found using VS Code, for instance using the extension [TODO Highlight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight).
This should help quickly find out if there are any TODOs left in a file.

Format todo as TODO:

---

Software/Software.ino

This pull request adds defines around the lines of code that are only needed if the macros `CONTACTOR_CONTROL`, `PWM_CONTACTOR_CONTROL` are defined.
It does this to exclude unnecessary macros being defined when these macros are not needed by the code.

Add defines for contactor parameters

---

Software/Software.ino
Software/src/battery/BMW-I3-BATTERY.h
Software/src/battery/IMIEV-CZERO-ION-BATTERY.h
Software/src/battery/KIA-HYUNDAI-64-BATTERY.h
Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/battery/NISSAN-LEAF-BATTERY.h
Software/src/battery/TESLA-MODEL-3-BATTERY.cpp
Software/src/inverter/SOFAR-CAN.h
Software/src/inverter/SOLAX-CAN.cpp
Software/src/inverter/SOLAX-CAN.h

This pull request updates boolean parameters to use booleans (true, false), rather than (1, 0).
Booleans are easier to read and understand by humans than 1, 0, and the usage of them lead to less errors in the code.

Use booleans for booleans

---

.github/workflows/compile-all-batteries.yml
.github/workflows/compile-all-combinations.yml
Software/Software.ino
Software/USER_SETTINGS.h
Software/src/battery/BATTERIES.h
Software/src/battery/NISSAN-LEAF-BATTERY.h
Software/src/battery/TESLA-MODEL-3-BATTERY.h
Software/src/battery/TEST-FAKE-BATTERY.cpp
Software/src/battery/TEST-FAKE-BATTERY.h
Software/src/devboard/config.h
Software/src/inverter/SMA-CAN.h
Software/src/inverter/SOFAR-CAN.h

This pull request adds a new feature, which lets you test your system with a fake battery!
This new test mode can be very useful when testing a new inverter, or testing the inverter before the battery setup is complete, or doing isolation testing for troubleshooting. This means you no longer have to have a working battery on the CAN bus. The user "f1racr" on the Discord had great progress with this test mode!
There is now a new define, `#define TEST_FAKE_BATTERY` that can be enabled in the `USER_SETTINGS.h` file. When enabled, the values set in `TEST-FAKE-BATTERY.cpp` will be sent towards your inverter of choice. While in this test mode, the LED on the board will cycle thru all RGB values, letting you know you are in a special mode.

New feature: Test fake battery

---

Software/src/inverter/SOLAX-CAN.cpp

The Solax protocol, min/max cell voltage had a silly copy paste error, this PR fixes that!

Solax: Fix cell max volt mapping

---

Software/Software.ino

This PR adds a compiler error, incase the user forgets to define a battery. This makes the project easier for beginners.
The USER_SETTINGS.h file is blank when a new user starts. If nothing is defined and you try to compile, the current compiler error doesn't really make sense:
A compiler #error is used to guide the user to the correct place, so a battery can be defined

Add compilation error for missing battery

---

README.md
Software/Software.ino
Software/USER_SETTINGS.h
Software/src/battery/BATTERIES.h
Software/src/battery/SERIAL-LINK-RECEIVER-FROM-BATTERY.cpp
Software/src/battery/SERIAL-LINK-RECEIVER-FROM-BATTERY.h
Software/src/inverter/INVERTERS.h
Software/src/inverter/SERIAL-LINK-TRANSMITTER-INVERTER.cpp
Software/src/inverter/SERIAL-LINK-TRANSMITTER-INVERTER.h
Software/src/lib/mackelec-SerialDataLink/SerialDataLink.cpp
Software/src/lib/mackelec-SerialDataLink/SerialDataLink.h

This PR adds a new feature. You can now have two LilyGo's talk to each other via serial! (Modbus pins)
Some inverters cannot be on same CAN bus as automotive CAN frames (Solax / Foxess). Having a separate CAN channel for the inverter becomes mandatory. Other HW solutions exist like adding more CAN channels, but this PR adds another alternative to that; Two LilyGos working in tandem:
The USER_SETTINGS.h file now has two new defines, that when enabled turns on this functionality:
`#define SERIAL_LINK_RECEIVER_FROM_BATTERY  //Enable this line to send battery data over Modbus pins to another Lilygo (This LilyGo interfaces with battery)`
`#define SERIAL_LINK_TRANSMITTER_INVERTER  //Enable this line to receive battery data over Modbus pins from another Lilygo (This LilyGo interfaces with …

New feature: Double LilyGo!

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp
Software/src/battery/TESLA-MODEL-3-BATTERY.h

This PR adds a new feature for Tesla batteries, smoothing of charge max value for when battery approaches 100%
@Newevg noticed that when trying to charge their LFP Tesla battery to 100%, charging it with 15kW all the way up to 100% was not possible. To reach 100%, the charge needs to taper off, otherwise the contactors would open, and the BMS would flag a fault. 
The .header file now has a configurable max value, `MAXCHARGEPOWERALLOWED`. This value, which defaults to 15000W, will be used when battery is between 0-95%. When battery reaches 95%, it ramps between `MAXCHARGEPOWERALLOWED`-> 0 in the 95-100% range. This should allow the battery to more gracefully reach 100%.

Add ramped charge value for Tesla

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp

This PR adds plausibility checks for SOC% on Nissan LEAFs batteries. 
Using a Nissan LEAF battery below 1A for extended periods of times will cause the BMS to not calculate SOC% correctly. This can happen for instance when using a Checkwatt profile. When this happens, the BMS needs to be rebooted.
We check that if the battery voltage is close to max, and the SOC% is low, we raise a FAULT(red LED) to stop charging/discharging. We also send a message on the USB to inform the user what has happened, so they can take action.

Add SOC% plausibility detection

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp

This PR makes the debug printout for Tesla batteries easier for beginners
There were many questions about the min / max voltages reported via CAN by Tesla, especially for LFP packs. The values were outright wrong, stating that the LFP packs could go to 402V 🙈 
Instead of printing the misleading min/max, we instead print `LFP chemistry detected!` if we notice that an LFP pack is used. This is much more useful info to have.

Tesla: Remove misleading min/max printout

---

Software/Software.ino
Software/src/devboard/webserver/webserver.cpp
Software/src/devboard/webserver/webserver.h

This PR adds a new feature. The Webserver now lists livedata!
Previously the liveserver only allowed OTA update and LED color status monitoring
- The HTML file is now set to automatically update every 10 seconds, with the latest data heading towards the inverter.
- It also shows which user settings are in place (Inverter choice, battery type)
- The liveview will also change color depending on BMS state (RED = Faulted, Green = OK etc.)
- The bottom of the page has a button that takes you to the OTA page
Attached some screenshots from benchtesting:
Pressing the "Perform OTA update" takes you to this page:

Feature: Add livedata to webserver

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp

Noticed by @MarkoBolt that the stat_bat_power variable is not formatted correctly. This affects all inverters getting wrong values, and also the webserver will show wrong values.
See how the W is shows as -21313W instead of −8685W
After the fix is applied:
This PR fixes the calculation of the value. It is tricky since the signed16 value should be put in an unsigned register (due to legacy modbus reasons)

Tesla: Fix power W calculation

---

Software/USER_SETTINGS.cpp
Software/USER_SETTINGS.h
Software/src/devboard/webserver/webserver.cpp

This PR adds the ability to disable the Access Point Wifi broadcasting. 📶❌
Due to cybersecurity reasons, broadcasting an AP might not always be desired
The `USER_SETTINGS.cpp` file now contains a row that controls wheter the AP should be enabled or not
`#define ENABLE_AP //Comment out this line to turn off the broadcasted AP`
This row can be commented out incase you want to disable AP

Add way to disable AP

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp

This PR fixes the WH max and WH remaining value sent towards inverter. It also adds SOC% plausibility detection, same as LEAF has.
Noticed by f1racer, the Wh value max would sometimes display as 0, and the remaining value would be incorrect. This would mess up Webserver info, along with sending incorrect info towards inverters.
We now use the configured WH number to avoid any u16 overflows. The WH number set in `USER_SETTINGS.h` can be between 0-65000Wh

Tesla S/3/X/Y: Fix Wh max/remain values

---

Software/src/devboard/webserver/webserver.cpp

This PR adds handling for inverter, so that the inverter knows that BMS is updating. It also sets the LED on the board to blue color while the update is running
So the inverter can act properly while OTA is happening
The LEDcolor variable is set to blue, and the bms_status is set to UPDATING while OTA is running

Bugfix: OTA not communicated to inverter/user

---

Software/Software.ino
Software/src/battery/BMW-I3-BATTERY.h
Software/src/battery/CHADEMO-BATTERY.h
Software/src/battery/IMIEV-CZERO-ION-BATTERY.h
Software/src/battery/KIA-HYUNDAI-64-BATTERY.h
Software/src/battery/NISSAN-LEAF-BATTERY.h
Software/src/battery/RENAULT-ZOE-BATTERY.h
Software/src/battery/SERIAL-LINK-RECEIVER-FROM-BATTERY.h
Software/src/battery/TESLA-MODEL-3-BATTERY.h
Software/src/battery/TEST-FAKE-BATTERY.h
Software/src/devboard/config.h
Software/src/inverter/BYD-CAN.h
Software/src/inverter/BYD-MODBUS.cpp
Software/src/inverter/BYD-MODBUS.h
Software/src/inverter/LUNA2000-MODBUS.cpp
Software/src/inverter/LUNA2000-MODBUS.h
Software/src/inverter/PYLON-CAN.h
Software/src/inverter/SERIAL-LINK-TRANSMITTER-INVERTER.h
Software/src/inverter/SMA-CAN.h
Software/src/inverter/SOFAR-CAN.h
Software/src/inverter/SOLAX-CAN.h

Noticed by @Cabooman , the `bms_char_dis_status` parameter would never flip correctly between Charging and Discharging, due to u16 / s16 incompability 
The BYD Modbus handling of this value has been incorrect, which could lead to unwanted desire on inverter side.
This PR fixes the following
- `bms_char_dis_status` parameter now correct depending on current direction flow
- Enumerations added to `bms_char_dis_status` parameter
- Slight memory optimization for `bms_char_dis_status` and `bms_status` variable
- Inverter defines are no longer duplicated in each .header file. Instead all defines to go "../devboard/config.h"

Bugfix: Charge/Discharge status bits (+refactoring)

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp

This PR adds handling for internal battery heaters on Nissan LEAF packs. 
When the LEAF battery gets cold, it does not want to accept charge. Nissan installed high voltage heating elements inside the battery on cold weather equipped vehicles, that turn on when the temperature goes below -17*C. Unfortunately, this info needs to be acknowledged by the vehicle in order to turn on. This PR adds the commands needed to ack the request to start/stop heating.
We now monitor the variables sent by battery
- LB_HeatExist (Specifies if battery pack is equipped with heating elements)
- LB_Heating_Stop (When transitioning from 0->1, signals a STOP heat request)
- LB_Heating_Start (When transitioning from 1->0, signals a START heat request)
- Batt_Heater_Mail_Send_Request (Stores info when a heat …

Nissan LEAF: Heated battery handling

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp

This PR improves the accuracy on both Voltage, Amperage and Power values. Thanks to Eriksson25 over on Discord for noticing! 🙌 
To get more realistic values towards inverter, and to see more realistic values in logs
Instead of downsampling the values by dividing them by 2 on each CAN read, we instead do more math when it is time to use the values. Here's an example:
Ex1: Real values from battery: Voltage = 370.5V , Amperage 0.5A
- Previous implementation, 371V*1A=371W
- New implementation, 370,5V*0.5A=186W
Ex2: Real values from battery: Voltage = 400.5V , Amperage 5.5A
- Previous implementation, 401V*6A=2406W
- New implementation, 400,5V*5.5A=2203W

Bugfix: Nissan LEAF, increase precision on values

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp

The bracket closing **update_values_kiaHyundai_64_battery()** was inside #ifdef DEBUG_VIA_USB.
If DEBUG_VIA_USB wasn't defined, the project wouldn't compile.

Bugfix: project doesn't complie if #define DEBUG_VIA_USB is not enabled

---

Software/Software.ino
Software/USER_SETTINGS.cpp
Software/USER_SETTINGS.h
Software/src/charger/CHARGERS.h
Software/src/charger/chevyvolt.cpp
Software/src/charger/chevyvolt.h
Software/src/devboard/webserver/webserver.cpp
Software/src/devboard/webserver/webserver.h

Basic support for the Chevy Volt Gen1 charger, including webserver integration. Intended to enable use of inverters lacking charging functions and standalone charging modes.
Both HV DC and auxiliary 12v output are supported features. This charger supports 200-420v DC up to 3300w, so not the most powerful by any stretch, but still useful.

Basic support for the Chevy Volt Gen1 charger

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp

This PR improves the accuracy on the reported minimum/maximum temperature value read via CAN. 
Credit to **frenetic** over on the Discord server for noticing this bug!
The original calculation rounded every .5° downwards. For instance if battery temperature was 8.5*C , the code reported back 8.0*C
Old:
`temp = rx_frame.data.u8[2];
max_temp = (temp * 0.5) - 40;`
New:
`max_temp = (rx_frame.data.u8[2] * 5) - 400;`

Tesla: Improve accuracy on temperature value

---

Software/Software.ino
Software/USER_SETTINGS.cpp
Software/USER_SETTINGS.h
Software/src/devboard/webserver/webserver.cpp
Software/src/devboard/webserver/webserver.h

This PR adds the ability to permanently store battery limit settings from the webpage. This means that even if the hardware is rebooted or updated via OTA/USB, the settings will continue to exist!
Users requested this feature
The Preferences.h library is used to store data to flash memory on the ESP32.
To skip reading from flash memory, there is an option in `USER_SETTINGS.h` that you can comment out
`#define LOAD_SAVED_SETTINGS_ON_BOOT  //Enable this line to read settings stored via the webserver on boot`

Feature: Add ability to save parameters to flash

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp

This PR attempts to fix the "High Voltage Output Pins: 1556V" that some users have been getting
Misleading information in USB output
Fixed the bitshifting in the CAN reading for 0x2b4, the upper two bits in frame2 were accidentally included!

Tesla: Fix for high voltage value

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/battery/TESLA-MODEL-3-BATTERY.cpp
Software/src/inverter/BYD-CAN.cpp

This PR improves the following:
- Nissan LEAF: CAN sending optimized for more speed. Safety added for empty battery signal. All debug printouts are now ifdef guarded.
- Tesla: Modified SOH% Warning. Fixed decimal formatting on temperatures.
- BYD CAN: Added USB printout for inverter brand

Bugfix: Tesla / LEAF / BYD CAN

---

Software/Software.ino
Software/src/devboard/webserver/webserver.cpp
Software/src/devboard/webserver/webserver.h

This PR adds a WiFi monitoring loop using a state machine to be non-blocking. 
This ensures that if wifi goes down or is flakey, the Battery Emulator will try to reconnect without blocking the main features. 
Currently will run every 30 seconds
Also improves the wifi initial connection in the same way meaning we can boot faster and start talking to the battery/inverter straight away

add wifi monitoring loop

---

Software/src/inverter/PYLON-CAN.cpp

This PR adds a toggle for Sofar inverters using Pylon CAN. Thanks to Pazdzierz over on the Discord for discovering this bug!
The Min/Max voltages sent on CAN were not interpreted correctly by the inverter, blocking charging/discharging
The PYLON-CAN.cpp file now has a toggle for this inverter
`#define INVERT_VOLTAGE  //If defined, the min/max voltage frames will be inverted, useful for some inverters like Sofar that report the voltages incorrect otherwise`

Pylon CAN: Fix Sofar voltages

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp

This PR makes the values shown in the USB printout more human readable, with decimals. Thanks to brennar10 over on the Discord for reporting these bugs!
When users see the USB debug printout after getting a battery up and running, they ofcourse check every value in the output page. If one of the values dont look right, this makes the users worry. This PR fixes that!
- Temperatures are now typecasted to int16 to avoid showing negative values as (6553*C is now -1*C)
- RealSOC% now has decimals (663 -> 66.3)
- "Current output" renamed to "DC/DC 12V current"
- The charge/discharge values not used by the software are no longer printed

Tesla: Make serialprintout more human readable

---

Software/src/inverter/BYD-CAN.cpp

User brennar10 noticed a bug in the temperature calculation when using BYD CAN. When values go negative, there is a risk that the signed bit is lost during the calculation, causing temperature to appear incorrect
The bug is fixed by converting the uint16 values to local int16 values before performing any calculations.

BYD CAN: Fix average temperature calculation

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp

This PR makes negative temperature values display OK on LEAF batteries
Users did not like to see 6553*C in the USB log
Value is casted to int16 before showing it

Nissan LEAF: Fix temperature value so its human readable

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp

This PR fixes negative temperature values, that would stop inverters from operating when battery gets cold
Thanks to ml265 over on the Discord server for noticing this bug. Temperatures are sent as int8, but we treat them as int16 in the code. This results in buggy values when the battery goes below freezing.
Values are typecasted before they enter the formatting function

Kia/Hyundai 64kWh: Fix negative temp handling

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp
Software/src/battery/KIA-HYUNDAI-64-BATTERY.h

This PR adds individual cellvoltage mappings for all 98 cells on 64kWh Kia/Hyundai 
For safer monitoring of battery status. All cellvoltages can be inspected in the webserver page "Cellmonitor"
Massive thanks to niclashedlund and Dibblah over on the Discord server for implementing and testing this! 🥳

Kia/Hyundai 64kWh: Add cellvoltage mappings

---

Software/Software.ino
Software/USER_SETTINGS.cpp
Software/USER_SETTINGS.h
Software/src/devboard/utils/events.cpp
Software/src/devboard/webserver/README.md
Software/src/devboard/webserver/cellmonitor_html.cpp
Software/src/devboard/webserver/cellmonitor_html.h
Software/src/devboard/webserver/events_html.cpp
Software/src/devboard/webserver/events_html.h
Software/src/devboard/webserver/index_html.cpp
Software/src/devboard/webserver/settings_html.cpp
Software/src/devboard/webserver/settings_html.h
Software/src/devboard/webserver/webserver.cpp
Software/src/devboard/webserver/webserver.h

This PR does some refactoring on the Webserver code. Instead of one long file over 1000s lines long, each page now has its own html.cpp file.
The PR also adds timestamps to events logged, making for easier troubleshooting
The PR also minifies some HTML code, to increase performance
Making code simpler to maintain
Timestamp calculation is performed on client side, since Battery-Emulator does not know time:

Feature: Webserver cleanup + Event timestamps

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp

Testing LFP packs showed that 3500 was slightly too close to the fully charged voltage, raising to 3520 from user testing!
To avoid emergency stops at 100% LFP charged
Tweak limit

Tesla: Raise LFP max cell voltage

---

Software/src/inverter/SMA-CAN.cpp
Software/src/inverter/SMA-CAN.h

This PR fixes a bug that caused SMA Sunnyboy Storage inverters to never use the battery
The bit in the 4D8 message was not set
Setting the bit to 3 allows discharge/charge. Setting it to 2 stops charging. We now set this bit depending on bms_status!

SMA CAN H: Fix charge allowed message

---

Software/Software.ino
Software/USER_SETTINGS.h
Software/src/inverter/INVERTERS.h
Software/src/inverter/SMA-TRIPOWER-CAN.cpp
Software/src/inverter/SMA-TRIPOWER-CAN.h

This PR adds the base for the SMA Tripower CAN protocol, needed to emulate a "SMA Home Storage battery" over CAN bus
To add compatibility for "SMA Sunny Tripower Smart 5.0-10.0 SE" inverters
This is just a starting point, we might need a CAN-log from a running system to fill in the blanks in most CAN messages

New inverter protocol: Add base for SMA Tripower protocol

---

Software/Software.ino
Software/USER_SETTINGS.cpp
Software/USER_SETTINGS.h
Software/src/battery/BATTERIES.h
Software/src/battery/BMW-I3-BATTERY.cpp
Software/src/battery/BMW-I3-BATTERY.h
Software/src/battery/CHADEMO-BATTERY.cpp
Software/src/battery/CHADEMO-BATTERY.h
Software/src/battery/IMIEV-CZERO-ION-BATTERY.cpp
Software/src/battery/IMIEV-CZERO-ION-BATTERY.h
Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp
Software/src/battery/KIA-HYUNDAI-64-BATTERY.h
Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/battery/NISSAN-LEAF-BATTERY.h
Software/src/battery/RENAULT-KANGOO-BATTERY.cpp
Software/src/battery/RENAULT-KANGOO-BATTERY.h
Software/src/battery/RENAULT-ZOE-BATTERY.cpp
Software/src/battery/RENAULT-ZOE-BATTERY.h
Software/src/battery/SANTA-FE-PHEV-BATTERY.cpp
Software/src/battery/SANTA-FE-PHEV-BATTERY.h
Software/src/battery/TESLA-MODEL-3-BATTERY.cpp
Software/src/battery/TESLA-MODEL-3-BATTERY.h
Software/src/battery/TEST-FAKE-BATTERY.cpp
Software/src/battery/TEST-FAKE-BATTERY.h

Common interfaces of batteries
To enable cleanup of Software.ino with tons of #ifdefs, and for the sake of having clearly defined interfaces
All battery files implement/define 4 functions of which 3 were previously common for all batteries with different names. The function declarations are done in BATTERIES.h. This enforces the interface definition of new batteries (somewhat). The functions currently required by the common interface are
``` 
void update_values_battery();
void receive_can_battery(CAN_frame_t rx_frame);
void send_can_battery();
void announce_battery(void);
```
The same can later be done for inverters

Battery interface streamlining

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp

This PR adds autodetection of battery chemistry based on cell amount
Discord user @Newevg noticed that in rare cases, the SOC% way of determining chemistry could fail. This adds another line of defense for LFP packs
Incase the amount of cells goes over 101, we know for sure we are dealing with an LFP battery

Tesla: Add cellamount LFP autodetect

---

Software/Software.ino
Software/src/battery/BMW-I3-BATTERY.h
Software/src/battery/CHADEMO-BATTERY.cpp
Software/src/battery/CHADEMO-BATTERY.h
Software/src/battery/IMIEV-CZERO-ION-BATTERY.h
Software/src/battery/KIA-HYUNDAI-64-BATTERY.h
Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/battery/NISSAN-LEAF-BATTERY.h
Software/src/battery/RENAULT-KANGOO-BATTERY.h
Software/src/battery/RENAULT-ZOE-BATTERY.h
Software/src/battery/SANTA-FE-PHEV-BATTERY.h
Software/src/battery/SERIAL-LINK-RECEIVER-FROM-BATTERY.cpp
Software/src/battery/SERIAL-LINK-RECEIVER-FROM-BATTERY.h
Software/src/battery/TESLA-MODEL-3-BATTERY.h
Software/src/battery/TEST-FAKE-BATTERY.h
Software/src/devboard/webserver/webserver.cpp
Software/src/devboard/webserver/webserver.h
Software/src/inverter/BYD-CAN.h
Software/src/inverter/BYD-MODBUS.cpp
Software/src/inverter/BYD-MODBUS.h
Software/src/inverter/LUNA2000-MODBUS.h
Software/src/inverter/PYLON-CAN.h
Software/src/inverter/SERIAL-LINK-TRANSMITTER-INVERTER.cpp
Software/src/inverter/SERIAL-LINK-TRANSMITTER-INVERTER.h
Software/src/inverter/SMA-CAN.h
Software/src/inverter/SOFAR-CAN.h
Software/src/inverter/SOLAX-CAN.h

The bms_char_dis_status variable was not updated on any other protocol than BYD. This caused webserver to show "Battery Idle" even when battery was in use. This PR fixes this
To make it clearer to users what battery is doing
(Note bms_char_dis_status was actually removed as global variable to increase performance)
bms_char_dis_status is removed from the code. All places where we see if we charge/discharge is by checking the sign of battery_current value. This increases performance for the codebase, less global variables linked. Also the Dual LilyGo code will transmit 1 less parameter which increases performance on serial.

Bugfix: Remove char_dis_status variable

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp

This PR fixes a bug where LFP Tesla packs would trigger the SOC% not plausable
Due to the changes in PR #190 , the LFP pack would be just on the limit when it comes to autodetecting SOC% not plausable. LFP has a very flat voltage curve, so the check no longer makes sense for LFP
We fix this by lowering the SOC% check, and also raising the voltage requirement.

Tesla: Tweak plausable SOC% limits

---

Software/src/battery/RENAULT-KANGOO-BATTERY.cpp

The voltage was not mapped correctly on Kangoo, preventing inverter from operating properly

Fix battery voltage on Kangoo

---

Software/src/battery/SERIAL-LINK-RECEIVER-FROM-BATTERY.cpp
Software/src/inverter/SERIAL-LINK-TRANSMITTER-INVERTER.cpp

This PR fixes large battery pack size values getting corrupted when sent to a Dual LilyGo setup
Self explanatory:
Example
75123wh gets rounded down to 7512 wh at sender to fit 16bits, and rescaled to 75120 at reciever. At most 9Wh inaccuracy, we can live with that :)

Fix u32 Wh values getting corrupted

---

Software/Software.ino
Software/src/battery/BMW-I3-BATTERY.h
Software/src/battery/CHADEMO-BATTERY.h
Software/src/battery/IMIEV-CZERO-ION-BATTERY.h
Software/src/battery/KIA-HYUNDAI-64-BATTERY.h
Software/src/battery/NISSAN-LEAF-BATTERY.h
Software/src/battery/RENAULT-KANGOO-BATTERY.h
Software/src/battery/RENAULT-ZOE-BATTERY.h
Software/src/battery/SANTA-FE-PHEV-BATTERY.h
Software/src/battery/TESLA-MODEL-3-BATTERY.h
Software/src/battery/TEST-FAKE-BATTERY.h
Software/src/devboard/config.h
Software/src/devboard/mqtt/mqtt.h
Software/src/devboard/webserver/cellmonitor_html.cpp
Software/src/devboard/webserver/cellmonitor_html.h
Software/src/devboard/webserver/webserver.h
Software/src/inverter/BYD-CAN.h
Software/src/inverter/LUNA2000-MODBUS.h
Software/src/inverter/PYLON-CAN.h
Software/src/inverter/SMA-CAN.h
Software/src/inverter/SMA-TRIPOWER-CAN.h
Software/src/inverter/SOFAR-CAN.h
Software/src/inverter/SOLAX-CAN.h

This PR increases the cellvoltage array to accomodate 800V batteries
Kia EV6 800V support
Array size increased

Feature: Increase cellvoltagearray for 800V

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp
Software/src/battery/TESLA-MODEL-3-BATTERY.h

This PR adds top balancing feature for teslas, that reduce allowed charge power incase a cell starts to get too high
Charging with high power when nearing 100% causes some cells to go into overvoltage protection mode, and prevent the battery from balancing. 
Three new parameters are added
- RAMPDOWNSOC 900 // 90.0 SOC% to start ramping down from max charge power towards 0 at 100.00%
- FLOATPOWERMAX 200 // W, what power to allow for top balancing battery
- MILLIVOLTFLOAT 20  // mV, how many mV under cell max voltage to start float charging
With these three parameters, the charge curve should look something more like this:

Feature: Add top balancing for Tesla batteries

---

Software/Software.ino
Software/src/devboard/webserver/settings_html.cpp

This PR tweaks the settings page
To improve readability of settings
✕ and ✓ is now used to signal if the setting is on (instead of 0 and 1)
If the setting is off, the min/max limits are greyed out

Improve visibility on scale_soc setting

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp
Software/src/battery/TESLA-MODEL-3-BATTERY.h

This PR rewrites LFP handling of Tesla battery packs
@Newevg noticed a serious flaw in the detection of LFP / NCM-A chemistry, that led to an overvoltage scenario. Incase the emulator is restarted at close to 99% SOC, it can incorrectly assume that NCM chemistry is used for up to 3-5minutes before it figures out that it is actually LFP, but before this happens the cells have already been overvolted. 
This PR does the following
- Introduce a setting in the header file, `LFP_CHEMISTRY`. If this is defined, the battery will start up in LFP mode. (Note that if LFP is used without defining it, it will still jump into LFP mode after a few minutes).
- Remove the voltage based chemistry check. This has proved to be unreliable (downright dangerous!)
- All design voltages are now proper defines in …

Tesla: Rewrite LFP handling

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp

This PR improves support for 40kWh Kona batteries
90S battery showed garbage values on three cells out of range:
This PR checks those three cells, and make sure they are valid (over 1000mV) before writing value to array

Kona 40kWh: Add handling for 90S cellvoltages

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp

This PR inverts the current value. -10A becomes 10A, and 10A will become -10A
The value sent to inverter is wrong way around, making any UI confusing:
We invert the sign by using the unary negation operator (-)

Kia/Hyundai: Swap sign on current value

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp

This PR adds back the last cell in the webserver for a 98S pack
The 90S patch previously commited broke support for 98S
Increase i++ counter from 97 to 98!

Kia/Hyundai: Increase cell counter to accomodate 98S

---

Software/src/inverter/BYD-CAN.cpp

This PR re-maps the charge/discharge allowed values in the CAN message 0x150
According to pelle_c's repository, this is how the CAN messages should be mapped
For this change testers are wanted. Could someone that is using BYD-CAN test this and report back if it works as intended?

BYD CAN: Swap dis/cha limits in CAN mapping

---

Software/Software.ino

This merge request introduces an enhancement to the Battery Emulator code by implementing mDNS (Multicast DNS) for easier device discovery on the local network therefore enhancing the overall connectivity and discoverability of the battery emulator devices.
- Added `init_mDNS` function to initialize mDNS resolution using the last two characters of the device's MAC address, ensuring uniqueness on the network. This results in a more user-friendly hostname (e.g., "batteryemulator8C.local"). 
- Add code that advertises the device as a "battery_emulator" service via Bonjour on port 80, facilitating seamless auto-discovery of these battery emulators within the local network. 
- This project does not contain any unit tests and as such are out of the scope of this pull request.
- Manual testing …

Add mDNS for local device discovery.

---

Software/src/devboard/utils/events.cpp
Software/src/inverter/SOLAX-CAN.cpp

This PR makes Solax inverters more robust on double LilyGo setups
Solax inverters opens the contactors if the battery is at the minimum charge level but there is no PV power available or grid power allowed  to charge it. This is a problem, since we have been treating it as an ERROR, requiring reboot to get out of this state.
- Inverter contactor opening changed from Error -> Info event
- CAN interface is now restarted incase Solax has timed out

Bugfix: Make Solax no longer get stuck with open contactors at 0%SOC

---

Software/src/battery/IMIEV-CZERO-ION-BATTERY.cpp

This PR changes the max allowed voltages for triplet batteries
Noticed by Ruudi S on Discord server, the values allow overcharging of the 88S battery in a worst case scenario
We now limit to 360V max (4.1V/cell on 88s) , and 316V min (3.6V/cell on 88s)

Triplet battery: Revise safety limits

---

Software/Software.ino

**Why**
BMW i3 battery requires can messages every 20ms. BYD modbus spends over 200ms sending some messages and main arduino loop currently has lowest priority. So sending modbus works fine, but can bus messages are sent too late. The battery opens contactors due to this.
**How**
Move the code out of loop() method, make new method and make it loop itself, invoke it as part of setup()
**What**
Make main arduino loop run in a background task to be able to set priority.

Make mainLoop run as background task with same priority as modbus

---

Software/src/battery/BMW-I3-BATTERY.cpp

A few values is scaled wrong / glitches on i3 batteries
- Current value
- Power value
- Max allowed charge/discharge overflows
- CRC check is broken on 2BD message
Mistakes were made in the first implementation
Iterative fixes

Bugfix: BMW i3 values

---

Software/Software.ino
Software/src/battery/BMW-I3-BATTERY.cpp
Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/devboard/config.h
Software/src/devboard/webserver/cellmonitor_html.cpp
Software/src/devboard/webserver/events_html.cpp
Software/src/devboard/webserver/index_html.cpp
Software/src/devboard/webserver/webserver.cpp
Software/src/lib/me-no-dev-AsyncTCP/src/AsyncTCP.h

This PR focuses on reducing CPU load further, to reduce the amount of CAN_OVERRUN events
Keeping the CAN messages in time is essential for good control over batteries. Delayed messages could cause issues in form of contactors opening under load
- Webserver filesize further reduced, reducing load when accessing pages
- Webserver set to refresh mainpage every 15 seconds instead of 10 seconds
- Nissan LEAF: 10ms messages now sent before 100ms are queued
- AsyncTCP moved to Core 0 to reduce load on Core 1
- Scheduler delay reduced from 2ms to 1ms
- LED code made less resource intensive. 
- digitalRead moved into LED block, which makes it run less often.
- Amount of if statements reduced

Bugfix: Further CPU load reductions

---

Software/src/battery/VOLVO-SPA-BATTERY.cpp

The Volvo file on main doesn’t include BATTERIES.h , this causes compilation error
The github Actions use command line compiler flags for the battery define, so VOLVO_SPA_BATTERY is #defined when compiling the volvo .cpp file. Compiling locally, the definition comes from BATTERIES.h, that in turn includes USER_SETTINGS.h
Added include line to fix issue!

Bugfix: Missing include for Volvo

---

Software/src/battery/TEST-FAKE-BATTERY.cpp

This PR adds CAN logging via USB serial.
Very useful feature for those working with new and unknown hardware, and don't have access to expensive CAN logging equipment. Now you can just use the inexpensive LilyGo board, and sniff CAN buses. 
The CAN-logging is added to the `TEST_FAKE_BATTERY` feature. When you are using this test mode, all the received CAN messages will get timestamp, ID, DLC, and data fields printed out via the Arduino IDE. This can then be exported to a .txt file for later analysis. Example format:
```
7556  54A  8  10 0 70 2 0 0 0 2B 
7558  54B  8  1 8 80 12 4 0 0 0 
7560  54C  8  61 66 0 0 0 0 57 0 
7561  1D4  8  F7 7 0 0 7 46 0 7B 
7573  11A  8  1 40 0 AA C0 0 0 3 
7574  1F2  8  10 64 0 0 0 1E 0 C 
7575  50B  6  0 0 2 C0 0 60 
7576  54F  8  21 1 0 0 7 0 8C 20 
7577 …
```

Feature: Add CAN logging to TEST-BATTERY

---

.gitignore
platformio.ini

What
When using platformio serial monitor it automatically creates log file with serial data in logs folder.
Why
Copying serial monitor data is tricky. This makes it a lot easier to debug even if there is lots of data in serial monitor. And also sending serial data to others for debugging is easier with this.
How
In VSCode using platformio serial monitor it automatically saves serial monitor output to log file in logs folder.

Add platformio serial logging

---

Software/src/battery/VOLVO-SPA-BATTERY.cpp

This PR removes a few lines where Volvo batteries were writing `system_bms_status = FAULT;`
This is redundant, event is already called which sets the status. Writing to same variable from multiple places can cause issues.
Events are responsible for setting the system_bms_status

Bugfix: Remove Volvo battery writing to bms_status

---

Software/src/battery/CHADEMO-BATTERY.cpp
Software/src/battery/IMIEV-CZERO-ION-BATTERY.cpp
Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/battery/VOLVO-SPA-BATTERY.cpp

This PR cleans up some unnecessary USB debug handling
Reduces complexity
* Volvo SPA: Removed USB printouts for cellvoltage errors (Events are better and already in place)
* Nissan LEAF: Removed USB printouts for inverter values (Can be viewed in Webserver instead, and data is 100% known working)
* Triplets: Removed USB printouts for inverter values (Can be viewed in Webserver instead)
* Chademo: Removed obsolete errorCode, and inverter values (Can be viewed in Webserver instead)

USB debug removal and improvements

---

Software/src/devboard/utils/types.h

What
This PR fixes KIA-E-GMP-BATTERY.cpp build.
Why
Refactor missed INTERVAL_500_MS_DELAYED definition.

Add INTERVAL_500_MS_DELAYED to types.h for KIA-E-GMP-BATTERY.cpp

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp
Software/src/battery/KIA-HYUNDAI-64-BATTERY.h

This PR makes the Kia/Hyundai battery respect the BMS max allowed charge/discharge values
By the reverse engineering performed by projectgus and tiny_man over on the Discord, we now know that the value to use is in CAN message 0x594
Safer battery operation

Kia/Hyundai 64: Add allowed charge limits from CAN

---

Software/src/lib/miwagner-ESP32-Arduino-CAN/ESP32CAN.cpp

This PR makes the board attempt to retransmit messages quicker incase the bus failed. This makes it so that double LilyGo / double CAN is no longer needed for Goodwe/GE inverters, everything can co-exist on one CAN bus! 🥳 
Some inverters like to swap between 250kbps and 500kbps to poll what battery is connected. Doing this with battery/inverter/emulator on same CAN channel might cause contactors to open on battery side.
The hold off delay was lowered from 2000ms -> 20ms. ⚠️ This might cause unforseen consequences, incase we actually have an issue it should be better to hold off the retransmission for longer periods of time, to let the other CAN devices recover more gracefully.

Bugfix: Decrease time before CAN retransmission

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp

In this PR we edit the logic on how CAN sending towards Kia/Hyundai batteries work
Due to recent CPU load optimizations, it was noticed that the startup process had become less stable. This PR attempts to make starting the batteries up more reliable.
We now wait until a CAN message has arrived from the battery, before we start to send stuff towards the battery.

Bugfix: Remake logic how Kia64 startup is handled

---

Software/src/battery/BMW-I3-BATTERY.cpp
Software/src/devboard/utils/events.cpp
Software/src/devboard/utils/events.h

This PR adds two more events to the i3 battery code
To assist installation troubleshooting
We now alert the user via the webui via events, one for high voltage interlock not seated, and another one for capacitor missing on HV side.

Feature: Add more events for BMW i3 to aid troubleshooting

---

Software/src/devboard/utils/led_handler.cpp

This PR makes the LED on the board stay on with solid red color incase we enter faulted state
Having the fault state solid red without any animations helps the user figure out that something is wrong. It is also better for colorblind users that may mistake the green from red.
The rewrite for the LED handling introduced in software 5.7.1 added new animations. The fault state accidentally got animated, it should be static.

Bugfix: Make faulted LED solid red again 🔴 

---

Software/src/battery/SERIAL-LINK-RECEIVER-FROM-BATTERY.cpp

A small bugfix to permit successful compilation for SERIAL-LINK-RECEIVER (search/replace issue from PR#254).

Fix regression in SERIAL-LINK-RECEIVER

---

Software/Software.ino
Software/src/devboard/webserver/webserver.cpp
Software/src/devboard/webserver/webserver.h
Software/src/lib/Uptime_Library/LICENSE
Software/src/lib/Uptime_Library/README.md
Software/src/lib/Uptime_Library/examples/DeviceUptime/DeviceUptime.ino
Software/src/lib/Uptime_Library/examples/DeviceUptimeCustomFormatting/DeviceUptimeCustomFormatting.ino
Software/src/lib/Uptime_Library/library.properties
Software/src/lib/Uptime_Library/src/uptime.cpp
Software/src/lib/Uptime_Library/src/uptime.h
Software/src/lib/Uptime_Library/src/uptime_formatter.cpp
Software/src/lib/Uptime_Library/src/uptime_formatter.h

**What**
Adds overflow-tolerant uptime tracking and reporting via webserver UI
**How**
By incorporating the very useful Uptime_Library by Yiannis Bourkelis (license compatibility verified). Header guard added locally within this project.
**Notes**
Feature requested by f1racr.
Multiple other time-oriented refinements are likely possible as benefit of having this in place (already noted by @Cabooman in discussion). This branch may be revised to account for some of those.

Microfeature: Add uptime tracking and display

---

Software/Software.ino
Software/src/devboard/utils/events.cpp
Software/src/devboard/utils/events.h

This PR adds an event for when automatic contactor control (via GPIO) decides to open contactors
For easier troubleshooting
- An event is added "Info: Too much time spent in error state. Opening contactors, not safe to continue charging. Check other error code for reason!"
- We also increase ticks from 500->1000, to avoid making the control too rapid.

Feature: Add Event when automatic contactor opening happens

---

Software/src/devboard/webserver/webserver.cpp

This PR makes the Webserver say `System` instead of `BMS`
Some users were confused, and thought the BMS was bad. System is a better name, since we can go into Faulted mode even if the BMS still thinks everything is fine.
Renamed the BMS -> System

Improvement: Rename BMS to System in webserver

---

.github/workflows/compile-all-inverters.yml
Software/Software.ino
Software/src/charger/CHARGERS.h
Software/src/charger/CHEVY-VOLT-CHARGER.cpp
Software/src/charger/CHEVY-VOLT-CHARGER.h
Software/src/charger/NISSAN-LEAF-CHARGER.cpp
Software/src/charger/NISSAN-LEAF-CHARGER.h
Software/src/include.h

This PR makes it possible to compile with Charger support enabled
Charger support was broken when the refactoring for v5.7.1 was done
We now prevent this from ever happening again, `NISSANLEAF_CHARGER` is now added to the Github workflow

Bugfix: Make chargers compile and add to workflow 🤖 

---

Software/Software.ino
Software/src/include.h
Software/src/inverter/BYD-CAN.cpp
Software/src/inverter/BYD-CAN.h
Software/src/inverter/BYD-MODBUS.cpp
Software/src/inverter/BYD-MODBUS.h
Software/src/inverter/INVERTERS.h
Software/src/inverter/LUNA2000-MODBUS.cpp
Software/src/inverter/LUNA2000-MODBUS.h
Software/src/inverter/PYLON-CAN.cpp
Software/src/inverter/PYLON-CAN.h
Software/src/inverter/SERIAL-LINK-TRANSMITTER-INVERTER.h
Software/src/inverter/SMA-CAN.cpp
Software/src/inverter/SMA-CAN.h
Software/src/inverter/SMA-TRIPOWER-CAN.cpp
Software/src/inverter/SMA-TRIPOWER-CAN.h
Software/src/inverter/SOFAR-CAN.cpp
Software/src/inverter/SOFAR-CAN.h
Software/src/inverter/SOLAX-CAN.cpp
Software/src/inverter/SOLAX-CAN.h

This PR refactors inverter handling
To simplify the code, and make it easier for new developers to join in
We remove the majority of the ifdeffing in the Software.ino file, with clearly defined functions for each inverter:
- receive_can_inverter();
- send_can_inverter();
- update_values_can_inverter();

Refactor: Inverter handling

---

Software/src/battery/BMW-I3-BATTERY.cpp
Software/src/battery/BMW-I3-BATTERY.h

This PR adds automatic pack size detection, which is used to set designvoltages and check safeties
Safer operation of BMW i3 batteries. Added:
* Cell deviation warning event
* Cell overvoltage fault event
* Cell undervoltage fault event
* Total pack voltage design voltage limits
We use kWh reported amount to switch between 60/94/120AH cellvoltage/packvoltage limits. Note, values needs testing, this is a good starting point!

BMW i3: Add cellvoltage safeties and pack size autodetect

---

Software/Software.ino

Serial-link fixer upper
Serial-link is handy!
RS485_EN_PIN, RS485_SE_PIN and PIN_5V_EN are needed for using Serial2 via the RS485 pins. Their configuration had been excluded from serial-link builds when the function was made exclusive for modbus
Tested ok on the kitchen table, tested live in a user setup.

Fix serial-link

---

Software/src/inverter/PYLON-CAN.cpp

This PR adds more mappings to the CAN inverter protocol Pylon
User Pazdzierz on the Discord noticed that the following were hardcoded from early development.
We now map:
- Cellvoltage max
- Cellvoltage min
- Celltemperature max
- Celltemperature min
- Number of cells
- Number of modules (fake but ok)
- Battery capacity in AH

Pylon CAN: Add more battery mappings

---

Software/src/inverter/BYD-CAN.cpp
Software/src/inverter/SMA-CAN.cpp
Software/src/inverter/SMA-TRIPOWER-CAN.cpp

This makes the calculated max charge/discharge value sent on CAN be based on actual battery voltage (instead of theoretical pack max voltage)
To make values make more sense. @Newevg noticed that the values sent towards inverter were too small, and loosing out on a few kW of power
In all calculations, `datalayer.battery.info.max_design_voltage_dV` is replaced with `datalayer.battery.status.voltage_dV`

Improvement: Make amp value based on actual voltage

---

Software/Software.ino
Software/USER_SETTINGS.h
Software/src/battery/KIA-E-GMP-BATTERY.cpp

What
This PR adds settings to enable can fd debugging.
Why
To improve ease of access to can fd data in serial monitor.
How
Enabling #define DEBUG_CANFD_DATA in USER_SETTINGS.h then it starts to print out frames from can fd data stream.

Add debug functions for can fd

---

Software/src/inverter/BYD-MODBUS.cpp

This PR does two things:
- New feature: Values set in webserver for max charge/discharge in amps is now read and used by the BYD Modbus inverter protocol
- Performance improvements for BYD Modbus
To be able to tune peak power from the webui on Fronius inverters
Using the std::min function to see which is smaller, User set limit OR battery value? We use the smallest one! This PR also removes all memcopy handling, and simplifies the register writing significantly

Feature: Add configurable limit to charge/discharge on BYD Modbus

---

Software/src/inverter/SOLAX-CAN.cpp

This PR fixes kWh remaning on Solax 
Decimal point was wrong;
Instead of dividing value with 100, divide with 10

Bugfix: Correct scaling on kWh for Solax

---

Software/src/battery/BMW-I3-BATTERY.cpp

Remove 0x426 block from BMW i3 support as it is not currently known how to provoke the SME into responding with a frame with that ID.
Originally: a fix for an overwritten index of datalayer.battery.status.cell_voltages_mV in the BMW i3 code for 0x426 frames.

Bugfix: Fix overwritten cell voltage value

---

Software/Software.ino
Software/USER_SETTINGS.h
Software/src/battery/CHADEMO-BATTERY-TYPES.h
Software/src/battery/CHADEMO-BATTERY.cpp
Software/src/battery/CHADEMO-BATTERY.h
Software/src/devboard/hal/hw_lilygo.h

**What**
This enhancement includes the appropriate CHAdeMO sequence for negotiation, connector locking and discharge support. Testing and further refinement is needed before this feature is entirely usable. Charging support is not yet present, though this PR lays the groundwork.
**Why**
To enable CHAdeMO vehicles to function as a battery, while retaining the safety afforded by a connector with locking solenoid, contactor control, and similar.
**How**
By implementing as much of the CHAdeMO standard as feasible given hardware limitation and access to closely-held specs.

Rework CHAdeMO support to more fully implement standard

---

Software/Software.ino
Software/USER_SETTINGS.h
Software/src/devboard/hal/hal.h
Software/src/devboard/hal/hw_stark.h

This PR adds support for the Stark hardware board, developed by @StarkJohan 🙌 
This board is considered more of a heavy-duty / prosumer board compared to the LilyGo alternative. The Stark board has built in support for 2x CAN channels, one of them being CAN-FD. It also has built in relays for actuating contactor closing, more advanced LED visualization of each output, DIP switches for CAN terminaton, and more. Once the board reaches maturity, we'll do a more in-depth explanation of it!
In the USER_SETTINGS.h file, you can now choose which hardware you are using ( LilyGo / Stark )

Feature: Add initial support for Stark hardware

---

Software/src/devboard/webserver/index_html.cpp
Software/src/devboard/webserver/webserver.cpp

This PR adds the ability to set a custom name on the webserver
Now the ssidAP name set in USER_SETTINGS.cpp will also be shown as header (Default is Battery Emulator)
Example, ssidAP set to "Battery #1"
Requested feature from users.

Microfeature: Customizable name on webserver

---

Software/src/devboard/mqtt/mqtt.cpp

In addition to checking the value of the variable number_of_cells, we also test the value of the last cell, as the value of the cells can be filled some time after initializing the number of cells. This test was also added before publishing the values cell_max_voltage and cell_min_voltage since they are ​​calculated from the cell data.

Prevent MQTT to publish cell voltage values before they are populated

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/devboard/webserver/cellmonitor_html.cpp

Ensure that the values ​​in the cell voltage datalayer are only updated when all information from all cells is received from battery. Changed the maximum cell reference in cellmonitor to use the specific datalayer information of the battery in use instead of the MAX_AMOUNT_CELLS which is the maximum possible value.

LEAF - Setting cell voltage values after last cell frame values

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/inverter/BYD-MODBUS.cpp
Software/src/lib/me-no-dev-ESPAsyncWebServer/src/AsyncEventSource.cpp
Software/src/lib/me-no-dev-ESPAsyncWebServer/src/AsyncWebSocket.cpp
Software/src/lib/me-no-dev-ESPAsyncWebServer/src/WebAuthentication.cpp
Software/src/lib/miwagner-ESP32-Arduino-CAN/CAN.c

This PR fixes the issues encountered when upgrading from from Espressif versions 2.X.X (based on ESP-IDF 4.4) to version 3.0.0 (based on ESP-IDF 5.1) of the Arduino ESP32 core
This PR also fixes a minor bug in the LEAF code, that could cause contactors to never turn on
All Arduino builds will be migrated to 3.0.0, the automatic build system we have in place already uses 3.0.0 , so we need to update the code
IMPORTANT! Users will need to update their version of ESP32 to 3.0.0, it can be done here in the Arduino IDE:

Feature: ESP32 Arduino Core v3.0.0 compatibility

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp

This PR fixes a bug, that sometimes the LEAF battery would not set the "Allowed contactor closing" ✅ when starting up
This prevented people using automatic contactor control from having a reliable startup
We wait 500ms until we start sending CAN messages towards the battery, allowing it to fully start

Bugfix: Nissan LEAF, Contactor closing allowed

---

Software/src/battery/CHADEMO-BATTERY-INTERNAL.h
Software/src/battery/CHADEMO-BATTERY.cpp
Software/src/battery/CHADEMO-BATTERY.h
Software/src/lib/smaresca-SimpleISA/SimpleISA.h

**What**
This PR updates EVSE data structures with measured current and voltage information in lieu of hardcoding values or using vehicle-supplied limits as the asserted values.
**Why**
Measured current and voltage are required for various aspects of CHAdeMO protocol compliance, safety checks, and dynamic power adjustments.
**How**
This functionality is achieved by using the SimpleISA adaptation added in a previous PR. When the ISA shunt is not available, there is an attempt to simulate protocol expectations..these simulations may be removed for safety purposes.

Improvement - CHAdeMO: Add measured current and voltage via IVT Shunt

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp

This PR fixes the amber warning light seen on startup, when using Kia/Hyundai batteries
If the 12V value has not updated via CAN, the safety would check the incorrect default value (0V), and report it as too low
Default value is now 12.0 V instead of 0V

Bugfix: Kia/Hundai, Make 12V default value reasonable

---

Software/src/devboard/webserver/webserver.cpp

This PR adds a microfeature to the WebUI, it now shows what hardware the code has been compiled for!
To spot configuration mistakes more easily, and to easier be able to spot what HW has been used from people sending screenshots.
Added ifdef printing to webserver.cpp

Microfeature: Add hardware printout to Webui

---

Software/src/inverter/BYD-CAN.cpp
Software/src/inverter/SMA-CAN.cpp
Software/src/inverter/SMA-TRIPOWER-CAN.cpp
Software/src/inverter/SOLAX-CAN.cpp

This PR fixes a bug that could in rare circumstances crash the board and cause it to reset with a PANIC event
If Voltage value from battery was unavailable (0V), the P/U=I calculation used to convert max allowed Charge speed in W -> A would perform a divion by zero, crashing the board. 4 different inverter protocols were affected by this bug, Solax, SMA, BYD and Tripower CAN protocols.
Massive thanks to V2H_chris over on the Discord for noticing this, and alerting me about it! 🙌

Bugfix: Division by 0 could crash the board

---

Software/src/battery/BMW-I3-BATTERY.cpp
Software/src/battery/BYD-ATTO-3-BATTERY.cpp
Software/src/battery/CHADEMO-BATTERY.cpp
Software/src/battery/IMIEV-CZERO-ION-BATTERY.cpp
Software/src/battery/KIA-E-GMP-BATTERY.cpp
Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp
Software/src/battery/MG-5-BATTERY.cpp
Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/battery/RENAULT-ZOE-BATTERY.cpp
Software/src/battery/SANTA-FE-PHEV-BATTERY.cpp
Software/src/battery/TESLA-MODEL-3-BATTERY.cpp
Software/src/battery/VOLVO-SPA-BATTERY.cpp

This PR adds possibility to clear any "CAN OVERRUN" event, when the messages are no longer delayed.
To allow for better visualization of CPU load issues. Now we just get 1 single event, no way to know if it was a one time occurance, or a massive problem that happens several times per day
Added clear_event() to all sections that use this event

Bugfix: Add clearing of overrun event

---

Software/Software.ino
Software/src/datalayer/datalayer.h
Software/src/devboard/webserver/webserver.cpp

A relocation of wifi_monitor() to a separate task dedicated to various connectivity
The WIFI functionality sometimes takes a looong time to finish handling reconnections and other shenanigans, which we don't want to affect core functions
Move wifi_monitor() to the mqtt task, rename everything properly enough, test
Tested on my personal FroLeaf setup. WIFI load now doesn't affect the core task

Move WIFI out from the core task

---

Software/src/battery/BYD-ATTO-3-BATTERY.cpp

This PR fixes the voltage scaling on BYD Atto3
Voltages were scaled 10x too large, blocking charge/discharge

Bugfix: Rescale voltage for Atto3

---

Software/Software.ino

A bugfix for lost Wifi if not using MQTT
People love their Wifi
When Wifi handling was moved out of the core loop, it ended up under a `#ifdef MQTT`section, causing Wifi to be inactive unless you use MQTT. Since the dev uses MQTT, he didn't notice this (shaame). Now the #ifdefs should be split properly.

Bring Wifi back

---

Software/src/lib/miwagner-ESP32-Arduino-CAN/CAN.c

This PR attempts to reduce CPU load, by filtering the CAN signals less
The code occasionally spikes in CPU load, this should help!
Instead of triple checking that the CAN signals are going high/low, we instead directly set the values to high/low once they are sampled. This reduces CPU load in two ways;
- Less Processing: Sampling once requires fewer computations and less time compared to sampling three times.
- Reduced Interrupt Load: With fewer samples, there are fewer interrupts generated for processing the CAN messages.
:warning: After making this change, we need to monitor CAN communication performance to ensure that it has the desired effect of reducing CPU load, and does not introduce any new CAN issues

CPU load improvement: Apply less filtering on CAN signals

---

Software/src/battery/BYD-ATTO-3-BATTERY.cpp

This PR improves support for BYD Atto 3 batteries, by adding more data
We now also get:
- Cell Voltage Max from polling
- Cell Voltage Min from polling
- Calculated Active Power is now implemented
- Current now signed right way
- Calculated SOC% from cellvoltage
Ideally, the SOC% value should be taken from CAN instead of being estimated from cellvoltage

Improvement: More BYD Atto 3 mappings

---

Software/USER_SETTINGS.h
Software/src/devboard/mqtt/mqtt.cpp

Removed the code that allows subscriptions to MQTT topics
It has no functional application (currently), only a debug callback. 
We could easily implement it back once a requirement/feature requires it, in the mean time we save some cpu cycles and ram.
Removed the code, after that tested if publishing MQTT data is not affected.

Removed MQTT subscription functionality

---

Software/src/lib/adafruit-Adafruit_NeoPixel/esp.c

This PR reduces CPU load, by optmizing the LED driver
To improve CPU overhead on the Battery-Emulator, less time spent on LED modes, more time spent on actual battery-inverter synergy
Stolen from @Cabooman 's CAN buffer branch 🕴️ 🙊

Improvement: Improve performance on LED driver

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp

This PR makes it more clear for Tesla owners that an inverter is blocking contactor closing
To help trouleshooting
Thanks to TheOfficialBatteryMan over on the Discord server for noticing this!

Improvement: Improve error message on HVIL block

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp

This PR removes the SOH% calculation performed on Tesla batteries
The calculation is unreliable, and often results in incorrect low readings (<25%), that messes up inverter operation.
SOH% is now hardcoded to 99.00% like in other batteries that doesn't have SOH% decoded

Tesla: Revert SOH% calculation

---

Software/Software.ino
Software/USER_SETTINGS.cpp
Software/USER_SETTINGS.h
Software/src/devboard/webserver/settings_html.cpp
Software/src/devboard/webserver/settings_html.h
Software/src/devboard/webserver/webserver.cpp
Software/src/devboard/webserver/webserver.h

This PR adds Wifi SSID/Password settings to the Webserver, so user can edit them there. Once entered, they get stored to permanent storage and loaded on boot. This PR also enables the LOAD_SAVED_SETTINGS_ON_BOOT by default.
This allows the user to update the board over the air with a software that is compiled without specific WiFi SSID and password. Flashing the binary that is compiled without specific WiFi SSID and password would still allow the board to connect to the WiFi network it was previously connected to. This helps the user to quickly update to the latest version of the software, without having to manually update the WiFi SSID and password in the source code.
This allows the user to flash code without specific WiFi SSID and password to the board, connect to the WiFi access point …

Feature: Add SSID/PWD writing from webserver!

---

Software/src/battery/BYD-ATTO-3-BATTERY.cpp

This PR adds setting the `battery_allows_contactor_closing` flag to allow contactor control to function
Some BYD Atto 3 batteries are locked if they are crashed too hard. This fix enables use of contactor control via GPIO pins, to manually force the contactors on.
`battery_allows_contactor_closing` set to true if we are not in faulted mode

BYD Atto 3: Add contactor closing allowed section

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp

This PR removed the kWh not plausible info messages on Tesla S/3/X/Y packs. 
Some packs simply report no kWh data. This lead to confused users, worrying about this message. Since we no longer use the kWh data to estimate SOH%, no sense in keeping the info messages.
Removed all kWh plausible messages

Tesla S/3/X/Y : Remove misleading info messages

---

Software/src/devboard/hal/hw_lilygo.h

This PR adds a compilation error. 
Some users accidentally enabled contactor control on i3 batteries. This caused WUP pin 25 to never go high. Contactor control is not required on i3, and will collide with GPIO pin 25 usage
#error added in HAL

BMW i3: Add error about pin usage

---

Software/src/battery/IMIEV-CZERO-ION-BATTERY.cpp

This PR improves cellvoltage and temperature writing
To avoid fault events before values have been read
We check if value is sane before writing it

Triplets: Only update values that are sane

---

Software/src/inverter/SOLAX-CAN.cpp

This PR makes it easier to configure the Solax parameters for number of modules / battery type
The defauly values are good for most 96S batteries, with a voltage range of 300-400V. However, if you try to use a 60S, 75S , or some other voltage range battery, you will most likely encounter the fault code BattVoltFault on the inverter. 
If you see this, edit the newly created defines at the top of the SOLAX-CAN.cpp file:
```
#define NUMBER_OF_MODULES 0
#define BATTERY_TYPE 0x50
```
The Wiki contains a matrix of known working definitions for some battery ranges

Feature: Configurable solax voltage range

---

Software/src/battery/BMW-I3-BATTERY.cpp

The Pin25 used for 3.3V SSR output was not working for the BMW i3. The output was floating between 0-1V.
The pinMode init function was not called on setup
Added the setup function, to allow the pin to work as intended

BMW i3: Fix initialization of WUP_PIN

---

Software/src/battery/BMW-I3-BATTERY.cpp

This PR fixes the min/max temperatures being swapped on the i3, and also changes so we use the DisplaySOC% instead of the raw SOC%.
The DisplaySOC% is better to use, since it can reach 100%. The raw SOC% is not always reaching the extremes (0 / 100%), so it is safer to use the Display value.
This PR takes the smaller fixes from PR #381 , since the cellvoltages part is not done yet

Bugfix: BMW i3 temperature and SOC improvement

---

Software/Software.ino

The CAN_TX_PIN and CAN_RX_PIN configuration in the HAL is not currently used. They are both hard coded in Software.ino and this currently overrides the HAL.
This PR fixes this issue.

Update CAN pins from hard coded to using HAL as intended

---

Software/src/battery/BMW-I3-BATTERY.cpp
Software/src/battery/BMW-I3-BATTERY.h

This PR adds cellvoltage monitoring for the BMW i3. It also fixes some minor issues that Havrla noticed while testing the code, like using wrong SOC% value and wrong capacity value.
Safer operation of the battery. SOC% is now using the display value, since the raw value can sometimes get "stuck" during recalibration. kWh remaining is also rewritten.
Reverse engineering how the cellvalue reading worked, in cooperation with Havrla :raised_hands:

Feature: BMW i3 cellvoltages + small fixes

---

Software/src/devboard/webserver/settings_html.cpp

This was prematurely closing the tag, preventing TEST_FAKE_BATTERY, CHEVYVOLT_CHARGER and NISSANLEAF_CHARGER from inserting their scripts.
Before
After

Remove extra closing script tag

---

Software/Software.ino
Software/USER_SETTINGS.cpp
Software/USER_SETTINGS.h
Software/src/devboard/mqtt/mqtt.cpp
Software/src/devboard/webserver/webserver.cpp
Software/src/devboard/webserver/webserver.h
platformio.ini

I have added a user setting for WIFI access point. I don't like having an access point available for everybody who is in range of the wifi network. While it can be protected with a strong password, it's still better to disable it if it's not used.
My preference is to hardcode my wifi credentials and make battery emulator connect to my network, making mdns unnecessary. 
For users who do not use Homeassistant, autodiscovery of MQTT sensors is now optional.
This pull request makes WIFI AP mode, MDNS and Home Assistant autodiscovery a user setting. 
Updates platformio platform packages.

User settings for MDNS, WIFI AP, Home Assistant autodiscovery

---

Software/src/battery/KIA-E-GMP-BATTERY.cpp

This PR improves the following things for eGMP
- Make eGMP use correct CAN struct
- Add default value to voltages, to avoid misleading low voltage warning
- Add CAN message sending towards the battery, to *hopefully* make the contactors close and SOC% to start working. NOTE, not working yet.
Improve support for eGMP platform

Bugfix: eGMP improvements

---

Software/src/devboard/utils/events.cpp

This PR removes EEPROM writing for storing events
This feature is using too much CPU when executed, causing CAN message transmission to be delayed by 70 milliseconds. We will disable it until we can get it optimized

Triage: Remove EEPROM writing

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp
Software/src/battery/TESLA-MODEL-3-BATTERY.h

This PR fixes the issue noticed in #432 
For safer battery operation
We now do two things differently.
- Power ramping is no longer tied to normal charge speed define. This avoids battery possibly being charged with 50kW while nearing 100% SOC.
- The Tesla.h file now has a clear distinction which defines should be edited by users
Note, for future implementations, we should:
- Try sending the entire vehicle CAN bus towards the battery
- This should at the same time fix that the battery sends 0A allowed Charge/Discharge, so we can stop using estimated value
- Once allowed A is available, use this to perform balancing / graceful stopping of charge at 100% soc

Tesla S3XY: Change how power ramping is performed

---

Software/USER_SETTINGS.h
Software/src/battery/BATTERIES.h
Software/src/battery/TESLA-BATTERY.cpp
Software/src/battery/TESLA-BATTERY.h
Software/src/devboard/webserver/webserver.cpp

This PR adds support for the 108s Model X battery.
In the current code if you tried to use this battery, you would get overvoltage and cellvoltage errors.
The PR fixes this by refactoring how Tesla packs are defined when compiling. You can now specify which Tesla battery you are using, previously it was all Model 3. Now there are specific rows for each battery:

Tesla: Add support for 108S Model X +refactor

---

Software/src/inverter/BYD-SMA.cpp
Software/src/inverter/SMA-CAN.cpp

This PR improves the success rate of getting a SMA battery paired
..it took pairing time down from ~45 mins and a 20% chance of it working to ~15 minutes and a 70% chance of it working the first time.
We now look at the enable line status (via the inverter allowes closing contactors), and when this is ON, we periodically broadcast messages every 100ms

Bugfix: SMA pairing reliability

---

Software/src/devboard/webserver/events_html.cpp
Software/src/devboard/webserver/events_html.h

This PR changes the events page on the web server to display events in reverse chronological order, showing the most recent event first instead of the internal definition order.
Currently, events are displayed based on their internal definition order, which doesn't always reflect the actual sequence in which they occurred. This makes it difficult for users to quickly find the most recent events. Reordering the events based on when they occurred improves the user experience by allowing easier access to the latest activity.
This was also requested by users on https://github.com/dalathegreat/Battery-Emulator/issues/355
The events were reordered by timestamp in descending order prior to rendering on the page.
The implementation has been tested to ensure the correct ordering and proper …

display events in reverse chronological order

---

Software/src/battery/RJXZS-BMS.cpp
Software/src/battery/RJXZS-BMS.h

This PR adds configurable settings for how much charge/discharge is allowed to the battery. It also adds smooth ramping at the top SOC% area, and a configurable float charge setting.
Custom batteries require more tweaking of allowed power levels. The built in BMS does not know what battery you have constructed. You need to define the power allowed.
You can define your battery limits in `RJXZS-BMS.h` file

Bugfix: RJXZS BMS, Add ramping charge power + settings

---

Software/src/devboard/wifi/wifi.cpp

improves the handling of Wi-Fi disconnect and connect events in the emulator. Specifically, it addresses the issue where the ARDUINO_EVENT_WIFI_STA_DISCONNECTED event was being fired multiple times without any new disconnections occurring. The change ensures that the disconnect event is cleared upon a successful connection or GotIP event (ARDUINO_EVENT_WIFI_STA_CONNECTED or ARDUINO_EVENT_WIFI_STA_GOT_IP), preventing repeated triggers when the system is already disconnected.
The emulator disconnect event was being triggered and coounted repeatedly without reflecting actual new wifi real disconnections, leading to inaccurate handling of Wi-Fi status. 
The fix was implemented by modifying the event handler logic. Now, the disconnect event is cleared whenever the system successfully …

Improve emulator Wi-Fi events handling for disconnect/connect

---

Software/Software.ino

This pull request resolves a compilation error by encapsulating the ssid and password variables with #ifdef checks to ensure they are only used when WiFi is defined.
Previously, the absence of these checks resulted in compilation error when WiFi was not configured,
Wrapping the usage of ssid and password in #ifdef WIFI clauses, ensuring they are conditionally compiled only when WiFi functionality is enabled.

Compilation Fix for Undefined WiFi Variables

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

This PR implements GitHub templates for new issues/PRs.
This is so I don't annoy @dalathegreat when opening PRs which do not follow the standard format ;-).
Following github documentation to create the templates.
PS: Feel free to improve by editing the commit or commenting here. I will collect all changes.

Improvement: Add initial GitHub Issue/PR templates

---

Software/Software.ino
Software/src/datalayer/datalayer.h
Software/src/devboard/webserver/webserver.cpp

When CONTACTOR_CONTROL is used, the battery-emulator controls
its own contactors. There is nowhere on the WebUI to show if
the contactors are engaged or not, only an error event is shown
if the contactors are disengaged.
Add an entry in the WebUI to show the CONTACTOR_CONTROL status.

Feature: Show CONTACTOR_CONTROL status in the WebUI

---

Software/src/devboard/utils/events.cpp

This PR fixes the core dump panic reported in #477 
There was a "% n" inside an event description causing a crash. Strings should now contain this :sweat_smile: 
We remove %-char from description text from here on!

Remove %n causing crash

---

Software/Software.ino
Software/USER_SETTINGS.h
Software/src/battery/JAGUAR-IPACE-BATTERY.cpp
Software/src/battery/TEST-FAKE-BATTERY.cpp

This PR fixes the broken PWM_CONTACTOR_CONTROL, as reported in https://github.com/dalathegreat/Battery-Emulator/issues/472 as well some small quality-of-life improvements.
When PWM_CONTACTOR_CONTROL was set the contactor coil pins for positive & negative never actually went high
It's broken.
Root cause was due to a wrong argument passed to `ledcWrite`: the existing code used the PWM channel; while `ledcWrite` actually expects the PWM pin to be passed.

Fix: PWM_CONTACTOR_CONTROL now actually engages contactors

---

Software/Software.ino

This PR adds outgoing canfd messages to the DEBUG_CANFD_DATA serial output as well as direction info to make debug life easier. Updated the solution according to suggestions from PR 495/496
Example output:
07:25:10.968 -> RX 111 66 F9 00 D5 00 00 00 00
07:25:11.125 -> TX 110 0F C8 0A 28 02 3A 02 EE
07:25:11.738 -> RX 91 0E A6 00 03 00 00 02 00
07:25:12.126 -> RX D1 02 08 00 00 00 00 02 00
07:25:12.544 -> RX 111 66 F9 00 D7 00 00 00 00
07:25:13.125 -> TX 110 0F C8 0A 28 02 3A 02 EE
07:25:13.319 -> RX 91 0E A6 00 03 00 00 02 00
07:25:13.740 -> RX D1 02 08 00 00 00 00 02 00
07:25:14.127 -> RX 111 66 F9 00 D8 00 00 00 00
07:25:14.936 -> RX 91 0E A6 00 03 00 00 02 00
07:25:15.097 -> TX 110 0F C8 0A 28 02 3A 02 EE
07:25:15.323 -> RX D1 02 08 00 00 00 00 02 00
07:25:15.743 -> RX 111 66 F9 00 DA …

Improved DEBUG_CANFD_DATA output ... MORE!

---

Software/src/battery/IMIEV-CZERO-ION-BATTERY.cpp

This PR fixes a bug that caused cellvoltage min/max to not appear in webserver for iMIEV
The check was assuming integer values, but we had double datatype
Fixed the if check

Bugfix iMIEV: Make cellvolt check work with double

---

Software/src/battery/PYLON-BATTERY.cpp
Software/src/devboard/safety/safety.cpp

This PR implements a configurable min/max voltage for Pylon batteries. It also omits the reasonable SOC check on pylon packs, since it is very unreliable here due to being voltage based.
Since we do not know the voltage limits of the pylon battery the user intends to use, it is better if they specify this themselves.
This is set at the top of the PYLON-BATTERY.cpp file

Pylon Battery: Add voltage limits, remove faulty safety

---

Software/src/battery/IMIEV-CZERO-ION-BATTERY.cpp

This PR fixes a bug on imiev, all cellvoltages were missing on webserver cellmonitor page
Better monitoring of battery
We set the cell amount, this was missing from the code

Bugfix iMIEV: Set amount of cellvoltages

---

Software/Software.ino

This PR fixes a bug, it was not able to receive any CAN messages on the CAN-FD port on the Stark board. Transmit worked however!
A bug was made during recent refactoring
All incoming CAN-FD messages were treated as CAN_ADDON_FD_MCP2518 . This hindered anyone with the configuration set to CANFD_NATIVE

Stark CMR: Fix broken RX for CANFD native

---

Software/Software.ino
Software/USER_SETTINGS.h

This PR fixes the issue #514 
To make it easier for MCP2515 add-on board users to take into use a new version of the Battery-Emulator
Instead of having the user modify Software.ino, we move the crystal definition to USER_SETTINGS.h

Improvement: Make MCP2515 crystal value easily configurable

---

Software/src/battery/RJXZS-BMS.cpp

RJXZS errors mostly have equivalents in Battery Emulator. This PR raises an event for each possible error.
Logging the error events in the Battery Emulator UI is useful for having one place to identify problems. It could also allow Battery Emulator to react to the errors in some cases.
Raises an event depending on the byte response.

RJXZS: Map errors to Battery Emulator events

---

Software/src/datalayer/datalayer.h
Software/src/devboard/safety/safety.cpp
Software/src/inverter/BYD-CAN.cpp
Software/src/inverter/BYD-SMA.cpp
Software/src/inverter/PYLON-CAN.cpp
Software/src/inverter/SMA-CAN.cpp
Software/src/inverter/SMA-TRIPOWER-CAN.cpp
Software/src/inverter/SOFAR-CAN.cpp
Software/src/inverter/SOLAX-CAN.cpp

This PR implements a check for all CAN based inverter protocols. The check verifies that CAN messages are still sent by the inverter
To make troubleshooting easier
If we go 60 seconds without seeing a CAN message from the inverter, we raise an event

Feature: Add CAN missing safety for all protocols

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp

This PR makes the capacity autodetect on Kia/Hyundai 64/40kWh packs
Simplified for users, no longer needed to set correct capacity in USER_SETTINGS when using these Kia/Hyundai batteries
Based on amounts of cells detected, we can determine what pack size in kWh is. 98S = 64kWh, 90S = 40kWh

Improvement: Kia64: Make autodetect kWh size

---

Software/Software.ino
Software/src/devboard/webserver/webserver.cpp

Keep CAN communications active during Equipment Stop
After reconsidering the equipmentstop functionality, particularly following some users feedback I believe it’s better to keep CAN communications active. This would allow us to monitor battery status (voltage, temperature, etc.) during stop while improving safety.
Changing the call to pause functionality so it does not halt CAN.

Keep CAN communications active during Equipment Stop

---

Software/src/devboard/webserver/advanced_battery_html.cpp

I deleted the ContactorSetState line because it was the same register as the main contactor state just being read twice in the Tesla.cpp file.. I will clean up that tesla.cpp file later but this gets the basic values interpreted.

Add tesla extra data enumeration

---

Software/USER_SETTINGS.h
Software/src/inverter/AFORE-CAN.cpp
Software/src/inverter/AFORE-CAN.h
Software/src/inverter/INVERTERS.h

This PR adds a new inverter protocol, Afore CAN
To add support for more inverters
The code is following the Afore 2.3 CAN standard, little-endian, 500kbps, from 2023.08.07. It can be enabled by turning on `AFORE_CAN` in USER_SETTINGS.h

New inverter protocol: Afore CAN

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/devboard/utils/events.cpp
Software/src/devboard/utils/events.h

This PR implements a new event for Nissan LEAF batteries. Incase a critical value is unavailable, we now inform the user.
We had an user with a faulty PSU, feeding the BMS with only 9V. Due to this the BMS did not start up properly. Having an event like this would have sped up the troubleshooting
Incase we see voltage unavailabe (0x3FF), we alert the user to check 12V supply and battery wiring.
`Warning: Battery measurement unavailable. Check 12V power supply and battery wiring!`

Nissan LEAF Add event for unavailable value

---

Software/src/devboard/utils/events.cpp

This PR downgrades the implausible SOC from Error -> Warning
Lots of different battery integrations have issues with this check, since it is voltage based. The check was written for a 96S LEAF battery. When using larger or smaller batteries, the check easily miscalculates
For now we downgrade severity to warning, until we can do a proper fix

Bugfix: Downgrade SOC check to warning

---

Software/src/battery/BMW-I3-BATTERY.cpp
Software/src/datalayer/datalayer_extended.h
Software/src/devboard/webserver/advanced_battery_html.cpp

This PR implements an extra battery info page for the BMW i3
User requested feature, to aid troubleshooting
The following extra info is added to the Webserver page:

Feature: Add more battery info for BMW i3

---

Software/src/battery/BYD-ATTO-3-BATTERY.cpp
Software/src/datalayer/datalayer_extended.h
Software/src/devboard/webserver/advanced_battery_html.cpp

This PR implements an extra battery info page for the BYD Atto 3
More insight for users if battery is locked or not, you can see if SOC% moves
The more battery info webpage now contains the following info:

Feature: Add more info page for Atto3

---

Software/src/lib/eModbus-eModbus/ModbusServerRTU.cpp

This PR changes to Modbus RTU server only prints error messages incase user has extra USB debugging enabled
Serial printing is slow and takes CPU resources. We raise an event already if we have RTU missing.
Now we only get Modbus RTU debug info via serial, incase the DEBUG_VIA_USB flag is set.

Improvement: Add ifdef to Modbus server error message printing

---

.github/workflows/compile-all-batteries.yml
Software/USER_SETTINGS.h
Software/src/battery/BATTERIES.h
Software/src/battery/CELLPOWER-BMS.cpp
Software/src/battery/CELLPOWER-BMS.h
Software/src/datalayer/datalayer_extended.h
Software/src/devboard/webserver/advanced_battery_html.cpp
Software/src/devboard/webserver/webserver.cpp

This PR implements support for the 250kbps Cellpower BMS
User requested feature
When `CELLPOWER_BMS` is selected in the battery list, we interpret the incoming CAN messages according to the Cellpower protocol supplied in https://github.com/dalathegreat/Battery-Emulator/issues/569

New battery: Cellpower BMS

---

Software/Software.ino
Software/USER_SETTINGS.h

Serial Link Baud rate increase
increase default baud rate for Serial Link to 115200 and add SERIAL_LINK_BAUDRATE define to the USER_SETTINGS.h
make the Serial Link Connection faster to reduce the chance of blocking issues
just increase the default bautrate from 9600 to 115200 and make it user configurable to be able to test different speeds.

increase default Serial_Link baud rate and make it configurable

---

Software/USER_SETTINGS.h
Software/src/devboard/safety/safety.cpp
Software/src/devboard/webserver/webserver.cpp
Software/src/inverter/INVERTERS.h
Software/src/inverter/PYLON-LV-CAN.cpp
Software/src/inverter/PYLON-LV-CAN.h

Implementation of the talking-to-inverter side of the pylontech protocol
This is by far the most common protocol for LV batteries. Having this allows to talk to a wide range of inverters (Victron, SMA, Deye, ...).  See [this list starting on page 2](https://www.photovoltaikforum.com/core/attachment/307672-pylontech-compatible-list-v2-11-ess-neu-20221212-pdf/)
Straightforward implementation of the CAN bus messages as documented [here](https://www.photovoltaikforum.com/core/attachment/77135-pylon-bms-protocol-can-can-20161103-pdf/)

Add new inverter implementation "Pylontech LV"

---

Software/src/battery/KIA-E-GMP-BATTERY.cpp
Software/src/battery/KIA-E-GMP-BATTERY.h

This PR implements voltage limits for each EGMP battery. It also raises the polling speed from 500ms -> 200ms , and cleans up some unused codeblocks. Finally, it adds ramping down power when SOC% starts to go over 90%
To improve safety
60 seconds after startup, we count each cellvoltage, and if we land on 144/180/192 cells, we set the voltage limits accordingly.

EGMP: Code cleanup and voltage limits added

---

Software/src/battery/PYLON-BATTERY.cpp

This PR fixes a bug, when using `PYLON_BATTERY` the remaining capacity would be 0 all the time
Fixing this to correct behaviour
We set capacity left according to SOC%, same as other implementations

Bugfix: Add remaining capacity writing for Pylon

---

Software/src/battery/BMW-I3-BATTERY.cpp
Software/src/devboard/utils/events.cpp
Software/src/devboard/utils/events.h

This PR removes a faulty precharge check, and replaces it with a welded contactor check. 
It is not possible to use battery_status_precharge_locked to see if capacitor is seated, the parameter cannot be used in this way. Reported by users in https://github.com/dalathegreat/Battery-Emulator/issues/574
Now we check contactor status, if either of the contactors are welded/sticking we report an EVENT_CONTACTOR_WELDED

BMW i3: Replace faulty cap check with welded contactor check

---

Software/src/inverter/BYD-CAN.cpp
Software/src/inverter/BYD-CAN.h

This PR updates the BYD firmware version string we send towards the inverter.
To make the emulator appear as an up to date BYD battery. This fixes the issue reported in #597
We implement a definable firmware version in .header

Bugfix: Update BYD FW to 3.29

---

Software/USER_SETTINGS.h
Software/src/devboard/hal/hal.h
Software/src/devboard/hal/hw_3LB.h
Software/src/devboard/webserver/webserver.cpp

This PR implements initial support for 3LB development board (v0.1)
To make the Battery-Emulator more accessible, via open source hardware

Feature: Add initial HAL for v0.1 3LB

---

Software/Software.ino
Software/src/datalayer/datalayer.h
Software/src/devboard/safety/safety.cpp
Software/src/devboard/webserver/settings_html.cpp
Software/src/devboard/webserver/webserver.cpp
Software/src/inverter/AFORE-CAN.cpp
Software/src/inverter/BYD-CAN.cpp
Software/src/inverter/BYD-MODBUS.cpp
Software/src/inverter/BYD-SMA.cpp
Software/src/inverter/FOXESS-CAN.cpp
Software/src/inverter/PYLON-CAN.cpp
Software/src/inverter/PYLON-LV-CAN.cpp
Software/src/inverter/SMA-CAN.cpp
Software/src/inverter/SMA-TRIPOWER-CAN.cpp
Software/src/inverter/SOFAR-CAN.cpp
Software/src/inverter/SOLAX-CAN.cpp

This PR adds allowed charge/discharge to datalayer. This simplifies the code, since each inverter protocol no longer needs to calculate its own current value.
All EV batteries send allowed charge/discharge in Watts. This is problematic, since the Inverters often need an amperage limit.
We remove 300 lines of code, and add 100 lines :)
The values are also shown in the Webserver

Improvement: Add charge/discharge current to datalayer

---

Software/src/battery/TESLA-BATTERY.cpp

This PR implements contactor opening incase we encounter a fault
To increase safety when using a Tesla battery
If we encounter FAULT state, we drop sending the 221_2 message, and after a few seconds we stop sending also the 221_1 message

Bugfix: Tesla S/3/X/Y , add contactor opening incase of FAULT

---

Software/src/inverter/FOXESS-CAN.cpp

This PR fixes an incorrect CAN_INVERTER_MISSING event raised on Foxess protocol
Better diagnostics
We (I) forgot to use the global SAFETY.cpp way of detecting missing inverter, and relied on a local check. I removed the local check, and started using the global watchdog. This fix will take care of the CAN_INVERTER_MISSING

Bugfix: Inverter missing event for Foxess

---

Software/Software.ino
Software/src/battery/BMW-I3-BATTERY.cpp
Software/src/battery/BMW-IX-BATTERY.cpp
Software/src/battery/BYD-ATTO-3-BATTERY.cpp
Software/src/battery/CELLPOWER-BMS.cpp
Software/src/battery/IMIEV-CZERO-ION-BATTERY.cpp
Software/src/battery/JAGUAR-IPACE-BATTERY.cpp
Software/src/battery/KIA-E-GMP-BATTERY.cpp
Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp
Software/src/battery/KIA-HYUNDAI-HYBRID-BATTERY.cpp
Software/src/battery/MG-5-BATTERY.cpp
Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/battery/PYLON-BATTERY.cpp
Software/src/battery/RANGE-ROVER-PHEV-BATTERY.cpp
Software/src/battery/RENAULT-KANGOO-BATTERY.cpp
Software/src/battery/RENAULT-TWIZY.cpp
Software/src/battery/RENAULT-ZOE-GEN1-BATTERY.cpp
Software/src/battery/RENAULT-ZOE-GEN2-BATTERY.cpp
Software/src/battery/RJXZS-BMS.cpp
Software/src/battery/SANTA-FE-PHEV-BATTERY.cpp
Software/src/battery/TESLA-BATTERY.cpp
Software/src/battery/TEST-FAKE-BATTERY.cpp
Software/src/battery/VOLVO-SPA-BATTERY.cpp
Software/src/datalayer/datalayer.h

This PR implements centralized writing of the active power (W) value
To make it simpler to maintain and add new battery protocols
Instead of having each battery implementation doing the same calculation to get W from Volt&Amp, we perform this in the `update_calculated_values()` function

Improvement: Centralize active_power_w writing

---

Software/src/inverter/BYD-CAN.cpp

This PR fixes the endianess of values read from inverter. 
Reported in https://github.com/dalathegreat/Battery-Emulator/issues/612
We now read the values right way round. At the same time, the inverter name reading is simplified

Bugfix: BYD CAN, Fix endianess & simplify inverter brand read

---

.github/workflows/compile-all-inverters.yml
Software/USER_SETTINGS.h
Software/src/devboard/webserver/webserver.cpp
Software/src/inverter/INVERTERS.h
Software/src/inverter/SCHNEIDER-CAN.cpp
Software/src/inverter/SCHNEIDER-CAN.h

This PR implements the Schneider V2 SE BMS CAN Communication protocol
Protocol: CAN 2.0 Specification
Frame: Extended CAN Bus Frame (29 bit identifier)
Bitrate: 500 kbps
Endian: Big Endian (MSB, most significant byte of a value received first)
To improve inverter compatibility. This adds support for [Schneider XW Pro](https://github.com/dalathegreat/Battery-Emulator/wiki/Schneider-inverters) inverters
There are still a few TODOs in the code related to how we should report Battery Manufacturer ID / Battery Model ID. Let's see if this is required when testing the protocol

New Inverter: Schneider CAN inverter protocol

---

Software/src/battery/BYD-ATTO-3-BATTERY.cpp

This PR Fixes compilation error when using SOC sent from battery
Mistake from branch merge

BYD Atto3: Fix compilation error

---

Software/src/devboard/webserver/webserver.cpp

This PR fixes two things:
- Added current min/max to secondary battery view
- Fixed a bug where if the user paused  the battery (virtual e-stop), and then rebooted, the webserver would not show red text anymore on charge allowed 0W
To not confuse users and developers on actual estop status
Webserver before the fix (note the missing red text after reboot on right side)
Webserver after the fix (Note that text stays red after reboot :+1: )

Bugfix: Webserver did not reflect paused state on reboot

---

Software/src/battery/BMW-I3-BATTERY.cpp

This PR fixes the swapped SOC% for BMW i3 in advanced webserver page "More Battery Info"
User reported bug in https://github.com/dalathegreat/Battery-Emulator/issues/633
The two parameters are now mapped correctly

BMW i3: Swap raw and dash SOC in More Battery Info page

---

.github/workflows/compile-all-batteries.yml
.github/workflows/compile-all-combinations.yml
.github/workflows/compile-all-inverters.yml
Software/USER_SETTINGS.h

This PR adds missing battery and inverter options to GitHub workflows
It also sorts the options lexicographically, to be able to more easily compare the batteries and inverters listed in different files.
To ensure that all different battery and inverter combinations get compiled automatically.
By updating the GitHub workflow files

Add missing battery and inverter options to GitHub workflows

---

Software/src/battery/BYD-ATTO-3-BATTERY.cpp

There was one decimal too much on the real Atto 3 SOC% value sent by battery
To fix being able to use real soc
*10 instead of *100
Fixes #590

Atto 3: Update scaling on real SOC

---

Software/Software.ino
Software/USER_SETTINGS.h
Software/src/devboard/webserver/webserver.cpp

Using PWM contactor control breaks the precharge pin. This PR fixes that
During development of PWM control, precharge was never tested
This PR fixes the bug, and implements additional improvements to GPIO contactor control
- Precharge pin now works when using PWM :bug: 
- Precharge duration now configurable in USER_SETTINGS
- Precharge logic improved significantly, the new logic is:
- Turn on negative contactor
- Wait a few ms, turn on precharge resistor
- Wait the user specified time (Set in USER_SETTINGS). Then turn on positive contactor
- Wait a few ms, turn off precharge resistor (and economize contactors if PWM is on)
- Webserver now shows precharge time instead of :x: to not confuse users:
- Webserver now work with PWM and shows off/economized state:

Bugfix: PWM causes precharge to break

---

Software/Software.ino

This PR fixes a bug, where if PWM was used and the board was reset via powercut (Not reproducible via Webserver reboot), the next time it booted it could occasionally engage the startup sequence incorrectly
We fix this, since an incorrect startup sequence will skip precharge, and potentially damage components. Phenomenon still unclear why it happens on PWM setups, but this PR fixes it. 
We fix the issue with a very simple fix. Instead of hammering the statemachine 10ms after CPU poweron, we wait 10 seconds until we start the precharge sequence. This has multiple benefits apart from fixing the glitched PWM startup, now incase a critical FAULT is encountered before the system has started (for instance battery sends something via CAN), we can now act on this and not turn on the battery at …

Bugfix: Add startup delay for contactors, fix PWM sequence

---

Software/src/inverter/SOLAX-CAN.cpp

This PR fixes missing SOC% in app when using Solax Ultra inverter
Better user experience
We send 5x CAN messages on boot towards the inverter. From testing, it appears that only sending these messages once seem to do the trick
Fixes #650

Bugfix: Add messages needed for Solax Ultra

---

Software/Software.ino
Software/USER_SETTINGS.h
Software/src/datalayer/datalayer.h
Software/src/devboard/utils/events.cpp
Software/src/devboard/utils/events.h
Software/src/devboard/webserver/settings_html.cpp
Software/src/devboard/webserver/webserver.cpp
Software/src/inverter/BYD-CAN.cpp

This PR achieves two things
- We no longer send the battery design voltage value to BYD protocol (it expects a target voltage)
- If user has not defined a value, we send the design value -+ offset in order to not trigger events/faults
- If user has defined a value, we use that as target
- We add target voltages as persistent setting
- Bonus, added event to signal incase storing usersettings fail
Fixes https://github.com/dalathegreat/Battery-Emulator/issues/643
The configurable settings are in the Webserver (and in USER_SETTINGS.h)

Feature: Add target voltage BYD setting, configurable setting!

---

Software/src/battery/RENAULT-ZOE-GEN1-BATTERY.cpp

This PR adds some CAN message info from a log file provided by piitsi_ over on the Discord
To gain better understanding of the Zoe Gen1
We now set the alive state based on specific CAN messages, not on any CAN message. Comments added on which messages are present in the 41kWh log file

Zoe Gen1: Add more info about which CAN messages are present

---

Software/src/battery/BYD-ATTO-3-BATTERY.cpp
Software/src/devboard/safety/safety.cpp

This PR makes the Atto 3 less likely to throw Events the first seconds on startup
Feedback from flying tools video on the Atto 3, which reports CELL DEVIATION and UNDERVOLTAGE as soon as the battery starts.
The issue was split into two parts
- Cell max/min values where updated async during OBD2 polling, causing the min to actually be larger than max for a few seconds. By adding ABS subtraction to compare the diff, we catch this edge case
- Pack undervoltage on startup. Due to the Datalayer having 370.0V as startup value, which is 10V lower than the Atto 3 minimum voltage (380.0V), we now init the value to 380.1V to avoid false positive events.

BYD Atto 3: Make startup less prone to throw Events

---

.github/workflows/compile-all-combinations-part1-batteries-A-to-M.yml
.github/workflows/compile-all-combinations-part2-batteries-N-to-Z.yml

This PR updates the GitHub Action workflow that compiles all battery and inverter combinations.
Currently the "Compile all combinations" workflow fails, with the error `Strategy expansion exceeded 256 results for job 'build-matrix'`. See [Compile All Combinations | v7.9.2 #159](https://github.com/dalathegreat/Battery-Emulator/actions/runs/12339753775) as an example.
This PR avoids that GitHub Action workflow strategy expansion exceeds 256 results for job build-matrix
It does this by splitting the workflow into two parts:
- Part 1: batteries starting with A-N
- Part 2: batteries starting with M-Z

Bugfix: avoid that GitHub Action workflow strategy expansion exceeds 256 results

---

Software/src/battery/RENAULT-ZOE-GEN1-BATTERY.cpp

This PR fixes some of the last TODO mappings for the Zoe Gen1, mainly allowed charge/discharge and Current value
Safer operation of battery by listening to the allowed power
Based on the excellent information found in this [spreadsheet document](https://docs.google.com/spreadsheets/d/1Qnk-yzzcPiMArO-QDzO4a8ptAS2Sa4HhVu441zBzlpM/edit?gid=0#gid=0)
Fixes #688

Renault Zoe Gen1: Add Current and allowed charge mappings

---

Software/src/battery/RENAULT-ZOE-GEN1-BATTERY.cpp

This PR changes to that Zoe Gen1 uses regen allowed instead of charger allowed value. This allows battery to charge full faster
The charger allowed value started to limit operation (dropping below 4kW) already at 60% SOC. The regen allowed value is still 40kW at this stage
We switch out:
datalayer.battery.status.max_charge_power_W = LB_Charging_Power_W;
To:
datalayer.battery.status.max_charge_power_W = LB_Regen_allowed_W;

Zoe Gen1: Change to use regen allowed value

---

.github/workflows/compile-all-batteries.yml
.github/workflows/compile-all-combinations-part1-batteries-A-to-M.yml
.github/workflows/compile-all-combinations-part2-batteries-N-to-Z.yml
.github/workflows/compile-all-inverters.yml
.gitignore
README.md
Software/USER_SECRETS.TEMPLATE.h
Software/USER_SETTINGS.cpp
Software/USER_SETTINGS.h
Software/src/devboard/mqtt/mqtt.cpp
Software/src/devboard/webserver/webserver.cpp

This PR moves user secrets from USER_SETTINGS.cpp & USER_SETTINGS.h into a platformio config file USER_SECRETS.ini
This change makes it less likely that secrets are accidentally exposed by users committing them and makes it easier to maintain these secrets during development
- USER_SECRETS.ini is included as additional platformio configuration in platformio.ini
- A template file USER_SECRETS_TEMPLATE.ini is copied to USER_SECRETS.ini if it does not exist and acts as a base configuration file
- USER_SECRETS.ini has been added to .gitignore to ensure it is not accidentally tracked

Improvement: Moving secrets from USER_SETTINGS.cpp to platformio config

---

Software/src/inverter/BYD-SMA.cpp
Software/src/inverter/SMA-CAN.cpp

This PR implements turning on/off an LED pin to indicate that SMA inverter allows/does not allow contactor closing, respectively.
To make use of the implemented code, a GPIO pin must be defined in the hardware file used. For instance
`#define INVERTER_CONTACTOR_ENABLE_LED_PIN GPIO_NUM_2` can be defined in `hw_liligo.h` when using one of the SD card pins for the LED.
This PR is implemented to get visual information if the SMA inverter request to close the contactors is sent and recognized up by the battery emulator.
The code checks whether the SMA inverter allows contactor closing, and turns on an LED when the inverter allows contactor closing, and turns off the LED when the inverter does not allow contactor closing.

Indicate that SMA inverter allows contactor closing via LED

---

Software/src/inverter/SOLAX-CAN.cpp

This PR makes the Ultra specific messages a part of the normal CAN sending routine
To improve compatibility for the Ultra inverters, and make them satisfied with the CAN content
Based on the reverse engineering efforts done on the Discord server 🙌

Solax: Make Ultra messages part of normal sending

---

Software/Software.ino
Software/USER_SETTINGS.h
Software/src/communication/can/comm_can.cpp
Software/src/communication/can/comm_can.h
Software/src/devboard/sdcard/sdcard.cpp
Software/src/devboard/sdcard/sdcard.h
Software/src/devboard/utils/types.h
Software/src/devboard/webserver/can_logging_html.cpp
Software/src/devboard/webserver/webserver.cpp
Software/src/include.h

This PR implements logging of CAN frames to an SD card
To enable logging of CAN frames over time to debug issues
Implements a ring buffer that CAN frames are pushed onto which are then written to the SD card using the second core to take load off the primary core.

Adding ability to log CAN frames to SD card

---

Software/src/battery/BATTERIES.h
Software/src/battery/BMW-I3-BATTERY.cpp
Software/src/battery/BYD-ATTO-3-BATTERY.cpp
Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/battery/SANTA-FE-PHEV-BATTERY.cpp
Software/src/battery/TESLA-BATTERY.cpp
Software/src/battery/TEST-FAKE-BATTERY.cpp
Software/src/communication/can/comm_can.cpp

Update function name `map_can_frame_to_variable_battery2()` to `handle_incoming_can_frame_battery2()`
This follows as the change done in #699 (eb4e5bc) was not fully carried out.
By carrying out the change done in eb4e5bc, also for battery2.

Bugfix: ensure code builds for DOUBLE_BATTERY

---

Software/src/battery/BMW-I3-BATTERY.cpp
Software/src/battery/BMW-I3-BATTERY.h
Software/src/battery/BMW-IX-BATTERY.h
Software/src/devboard/hal/hw_3LB.h
Software/src/devboard/hal/hw_lilygo.h
Software/src/devboard/hal/hw_stark.h

This PR implements a Wake up pin for a second battery (`DOUBLE_BATTERY`) for BMW I3 (`BMW_I3_BATTERY`).
This PR fixes #626. This feature was requested by [pmajor021](https://github.com/pmajor021).
- The `WUP_PIN` is updated to `WUP_PIN1` and `WUP_PIN2`.
- The pin definition is moved from the battery file to the hardware abstraction layer of each supported hardware.
- Error handling is implemented, in case the pins defined as wake up pin, are also used for contactor control.

Add wake up pin for second BMW I3 battery

---

Software/src/devboard/sdcard/sdcard.cpp
Software/src/devboard/sdcard/sdcard.h

This PR fixes the issue that the code does not compile anymore for hardware that does not have SD card pins defined, since the SD functions were introduced in #707.
To ensure the code compiles for all hardware types.
By adding `#if defined()` statements around the code that requires the hardware pins to be defined.

Bugfix: ensure code compiles for hardware that does not have SD card pins

---

.github/workflows/compile-all-batteries.yml
.github/workflows/compile-all-combinations-part1-batteries-A-to-M.yml
.github/workflows/compile-all-hardware.yml
.github/workflows/compile-all-inverters.yml
Software/USER_SETTINGS.h
Software/src/devboard/hal/hw_stark.h
Software/src/include.h

This PR implements automatic builds for the different supported hardware platforms, using GitHub Actions.
It does this, to ensure that the code compiles for all different types of hardware. This prevents the need for bug fixes such as #714.
A GitHub Action workflow is added to compile the code for different hardware setups. This check is done on each push and each pull request.

Add hardware to GitHub Actions workflows

---

Software/src/battery/BMW-I3-BATTERY.cpp

This PR fixes a bug causing cellvoltages not to be available for the second i3 battery in double-battery setups
We copy the same method from battery1, forgotten during development

BMW i3: Make cellvoltages work for double-battery

---

Software/src/battery/TESLA-BATTERY.cpp

The names where recently changed by @josiahhiggs , causing compilation error
When #ifdef DEBUG_LOG was turned on, the build would not pass. Main tests does not test with this turned on. Maybe it should?
Quickfix, rename variables

Bugfix: Tesla, fix broken references in logging

---

.github/workflows/compile-all-hardware.yml
Software/USER_SETTINGS.h
Software/src/devboard/hal/hal.h
Software/src/devboard/hal/hw_devkit.h
Software/src/devboard/webserver/webserver.cpp

This PR adds support of ESP32 DevKit V1 hardware with 30 pins. The hardware is, for instance, documented on [lastminuteengineers.com](https://lastminuteengineers.com/esp32-pinout-reference/).
The hardware is available with micro USB, or USB C connector.
To make the hardware work with the battery emulator, the relevant breakout boards must be connected to the ESP32 DevKit V1, for instance:
- SN65HVD230 for `CAN_NATIVE`
- MCP2515 for `CAN_ADDON`
- MCP2518FD for `CANFD_ADDON`
- MAX485 for RS485
To connect these breakout boards, it is handy to use an ESP32 DevKit V1 breakout board, which includes GND, 3V3, 5V rails, and can be powered with 12V.
This hardware is added, as the LilyGo only has relatively little pins available to connect additional hardware. The ESP32 DevKit V1 has 30 pins, and …

Add support for ESP32 DevKit V1 hardware

---

Software/src/devboard/hal/hw_lilygo.h
Software/src/include.h

This PR moves the check if `CAN_ADDON` and `CANFD_ADDON` are defined simultaneously, to throw an error if these functions use the same hardware pins, only to the hardware where these pins overlap (i.e. LilyGo).
To ensure that the respective error message is only triggered for the hardware that it needs to trigger for.
By moving the check from `include.h` to `hw_liligo.h`, as this check is only relevant for LilyGo hardware.

Move check if CAN_ADDON AND CANFD_ADDON are defined simultaneously, to respective hardware

---

Software/src/battery/TESLA-BATTERY.cpp

This PR makes the Tesla debug messages a bit more manageable
During normal operation of the battery, the Tesla code spams the following error codes every second:
```
1.000 ERROR: The processor has experienced a reset due to watchdog reset
1.000 ERROR: BMS_a035_SW_Isolation
1.000 ERROR: BMS_a036_SW_HvpHvilFault
1.000 ERROR: BMS_a088_SW_VcFront_MIA_InDrive
1.000 ERROR: BMS_a090_SW_Gateway_MIA
1.000 ERROR: BMS_a091_SW_ChargePort_MIA
1.000 ERROR: BMS_a092_SW_ChargePort_Mia_On_Hv
1.000 ERROR: BMS_a094_SW_Drive_Inverter_MIA
1.000 ERROR: BMS_a170_SW_Limp_Mode
```
The MIA messages are good info for further development, hinting towards CAN messages from these units are missing. We should improve the software by sending more CAN towards the battery.
However, the first message about the Watchdog is …

Improvement: Remove Tesla watchdog spamming 

---

Software/src/battery/JAGUAR-IPACE-BATTERY.cpp
Software/src/battery/KIA-E-GMP-BATTERY.cpp
Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp
Software/src/battery/RENAULT-KANGOO-BATTERY.cpp
Software/src/battery/TESLA-BATTERY.cpp
Software/src/battery/TEST-FAKE-BATTERY.cpp
Software/src/battery/VOLVO-SPA-BATTERY.cpp
Software/src/charger/CHEVY-VOLT-CHARGER.cpp
Software/src/communication/can/comm_can.cpp

This PR fixes the panic reset caused by using Weblogging with the Tesla battery, as reported in #723 
Serial printing % signs are a bad idea in C++

Bugfix: Fix Panic Reset caused by percentage char

---

Software/src/lib/pierremolinaro-ACAN2517FD/ACAN2517FD.cpp
Software/src/lib/pierremolinaro-acan2515/ACAN2515.cpp
Software/src/system_settings.h

This PR fixes the crashing at boot reported in #729 when using ESP32 v3.1.0
To be able to use the application with ESP32 v3.1.0
Both CAN libraries are creating tasks with a priority of 256, which is far beyond the maximum allowed value for the ESP32's FreeRTOS. We now set this manually instead, base value of 10 added.

Assert failure: Add task priority setting for CAN addons

---

Software/Software.ino
Software/USER_SETTINGS.h
Software/src/devboard/sdcard/sdcard.cpp
Software/src/devboard/sdcard/sdcard.h
Software/src/devboard/utils/logging.cpp
Software/src/devboard/utils/logging.h
Software/src/devboard/webserver/debug_logging_html.cpp
Software/src/devboard/webserver/webserver.cpp
Software/src/devboard/wifi/wifi.cpp
Software/src/include.h

This PR implements logging messages to an SD Card where available
This will help to diagnose issues when an emulator reboots as the log is persisted
This is an extension to the sdcard methods to add a second buffer for logs which are sent from the logger and written to the SD Card on the second CPU core

Adding feature to log to SD Card

---

Software/USER_SETTINGS.h
Software/src/communication/contactorcontrol/comm_contactorcontrol.cpp
Software/src/communication/contactorcontrol/comm_contactorcontrol.h
Software/src/devboard/hal/hw_lilygo.h
Software/src/include.h

This PR implements a periodic BMS reset. It achieves this by toggling a GPIO pin every 24h. This 3.3V pin can be used to control the 12V power going into the BMS via an SSR or other type of relay.
Some automotive BMSes like the Nissan LEAF BMS does not work well when powered on continously. According to OEM specs, a powercycle is required every 24hours to keep the BMS working as intended. Failure to reset the BMS can cause SOC% to drift overtime, as reported in #86 
We add a new user configurable feature in the USER_SETTINGS, called `PERIODIC_BMS_RESET`. When this is enabled, a GPIO pin (See the HAL file for your hardware to see which pin), will be toggled ON upon start, and after 24 hours it will turn off for 30s. When the power is cut to this pin, the emulator is put into Paused state, …

Feature: Add periodic BMS power reset

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp

Slow down ParameterPolling of Kia / Hyundai battery
Sometimes the CellVoltages are corrupted due to high CAN-load / CPU load
Polling of Parameter ID's polled every other time instead of each 100ms cycle.

Slow down polling of ParameterPolling KIA / Hyundai 

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp

This PR implements a sanity check on the last cellvoltages for Kia64/40kWh packs
Some 90S packs incorrectly report some garbage on the unpopulated cells. Attached is a screenshot from a Kia 40kWh 375A0 - K4403
We check the cells above 85. If the value seems sus, we zero it

Kia64: Add sanity checking for last cellvoltages

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp
Software/src/datalayer/datalayer_extended.h
Software/src/devboard/webserver/advanced_battery_html.cpp

This PR implements a more battery info page for Kia64, along with cellvoltage sanity checking
To make 90S batteries work better with cellmonitor page
This PR also fixes the More Battery Info page from breaking, bug introduced in PR 744
More Battery Info page added:

Bugfix: Kia64 cellvoltages + More Battery Info

---

Software/src/battery/VOLVO-SPA-BATTERY.cpp

This PR allows for safer operation of Volvo/Polestar SPA batteries
To not damage the battery while charging. Before this PR, allowed charge/discharge was locked at 30kW, even at 99%!
We now use the Charge/Discharge power limit values that the BMS sends. Example of values at 95.53%SOC

Bugfix: Make Volvo/Polestar use BMS allowed charge/discharge values

---

Software/src/lib/pierremolinaro-ACAN2517FD/ACAN2517FD.cpp
Software/src/lib/pierremolinaro-ACAN2517FD/ACAN2517FD.h

This PR adds the suggested changes to the pierremolinaro/acan2517FD library as suggested [in this PR](https://github.com/pierremolinaro/acan2517FD/pull/34)
There is a performance gain, disabling 2517FD compat mode, it no longer disables interrupts during SPI transactions which slightly increases performance and avoids delaying interrupts. There should be no downside to enabling this, since [our Wiki](https://github.com/dalathegreat/Battery-Emulator/wiki/CAN%E2%80%90FD-add%E2%80%90on-(MCP2518FD)#hardware) suggests using the 251**8**FD chip instead.
Disabling the MCP2517 compatibility mode can be done in ACAN2517FD.h by uncommenting the `#define DISABLEMCP2517FDCOMPAT` line. By default we keep this disabled until someone has had time to test it properly on a heavy bus load CAN-FD setup.

Improvement: Update CANFD library with 2517 compat toggle

---

Software/src/devboard/sdcard/sdcard.cpp
Software/src/devboard/sdcard/sdcard.h
Software/src/devboard/webserver/webserver.cpp

This is an update to the CAN logging to SD feature to significantly improve performance for busy CAN networks
- Migrate from SPI SD library to SD_MMC
- Minimise the number of individual file writes by batching writes where possible
- Write a binary stream to the buffer to stop corruption

Improvements to CAN logging to SD to significantly improve performance

---

Software/Software.ino
Software/src/devboard/utils/logging.cpp
Software/src/devboard/utils/logging.h

Fix bugs in printf logging code & add Battery Emulator version and build date/time to log
Fix the bug and being able to see the exact build version that is running
Fixed the code. Added printf containing version and date/time.

Fix bugs in printf logging code & add version to log

---

Software/src/battery/TESLA-BATTERY.cpp
Software/src/battery/TESLA-BATTERY.h
Software/src/datalayer/datalayer.h
Software/src/devboard/safety/safety.cpp
Software/src/devboard/utils/events.cpp
Software/src/devboard/utils/events.h
Software/src/devboard/webserver/settings_html.cpp
Software/src/devboard/webserver/webserver.cpp

This PR implements forced balancing functionality for Tesla LFP batteries (Model 3/Y)
To help keep LFP batteries balanced outside of a Tesla vehicle. This mimics more how the batteries would be commanded in a vehicle.
The forced balancing mode can be enabled via the Webserver. It is recommended to run this once per month on Tesla LFP batteries. **Before enabling, make sure battery is close to full, and you have enough sun or grid power to continue charging and forcing the balance!**
When enabling the `Manual LFP balancing` , the balancing runs for the specified amount of time, set in `Balancing max time`. The balancing parameters, Balancing float power , Max battery voltage , Max cell voltage and Max cell voltage deviation can also be adjusted from here.

Feature: Add forced Tesla LFP balancing functionality

---

Software/src/battery/VOLVO-SPA-BATTERY.cpp

This PR makes the startup more robust
Sometimes contactors dont close after a reboot
We send 2 more messages on startup, one to open, clear, and then finally close

Volvo/Polestar SPA: Add startup routine for contactor closing

---

.github/workflows/compile-all-combinations-part1-batteries-A-to-M.yml
.github/workflows/compile-all-combinations-part2-batteries-N-to-Z.yml
.github/workflows/compile-all-inverters.yml
Software/USER_SETTINGS.h
Software/src/inverter/GROWATT-LV-CAN.cpp
Software/src/inverter/GROWATT-LV-CAN.h
Software/src/inverter/INVERTERS.h

This PR adds initual support for 48V Growatt batteries
To increase amount of inverters supported by the Battery-Emulator
CAN protocol added from discussion in [Issue 156](https://github.com/dalathegreat/Battery-Emulator/issues/156#issuecomment-2568335155) , massive thanks to @ErikssonPer

New inverter protocol: Growatt 48V Low Voltage

---

Software/src/battery/TESLA-BATTERY.cpp
Software/src/datalayer/datalayer.h
Software/src/devboard/webserver/advanced_battery_html.cpp
Software/src/devboard/webserver/webserver.cpp

This PR implements isolation fault clearing via the More Battery Info page for Tesla batteries
Good to have diagnostic feature
Pressing the "Clear Isolation Fault" under the "More Battery Info" page will send diagnostic messages towards the battery
CAN messages sent:
NOTE: For future implementation, we should instead reply when the UDS messages arrive from battery. This should still work fine, but no feedback from battery is taken into account.

Feature: Tesla, add isolation clearing function

---

Software/src/inverter/PYLON-CAN.cpp

This PR fixes the following Pylon CAN bugs:
- An issue where INVERT_LOW_HIGH_BYTES option was ignored for some messages
- An issue where some temperature messages was not set for SEND_1 option
- + Adds the option to use manually set voltage limits from Webserver as discharge/charge cutoff voltages
Bugs are bad, and user customization is great!
See sourcecode for implementation, same as on BYD CAN

Pylon CAN: Bugfix + pylon respect voltage limit

---

Software/src/communication/contactorcontrol/comm_contactorcontrol.cpp
Software/src/inverter/KOSTAL-RS485.cpp
Software/src/inverter/KOSTAL-RS485.h

Example:
```
FAKE Values going to inverter
SOH%: 99% , SOC%: 52% , Voltage: 370V , Max discharge power: 5000W , Max charge power: 5000W , Max temp: 6°C , Min temp: 5°C , Max cell voltage: 3596mV , Min cell voltage: 3500mV
[28357 ms] RX (dropped): 07 63 FF 02 FF 29 5E 02 16 00
FAKE Values going to inverter
SOH%: 99% , SOC%: 52% , Voltage: 370V , Max discharge power: 5000W , Max charge power: 5000W , Max temp: 6°C , Min temp: 5°C , Max cell voltage: 3596mV , Min cell voltage: 3500mV
[29177 ms] RX (dropped): 07 63 FF 02 FF 29 5E 02 16 00
[29997 ms] RX (dropped): 07 63 FF 02 FF 29 5E 02 16 00
FAKE Values going to inverter
SOH%: 99% , SOC%: 52% , Voltage: 370V , Max discharge power: 5000W , Max charge power: 5000W , Max temp: 6°C , Min temp: 5°C , Max cell voltage: 3596mV , Min cell voltage: …
```

kostal: more debug output to get better understanding of temporal behaviour

---

Software/Software.ino

This PR fixes a bug related to using 2x batteries without SOC scaling
Old software only calculated power for battery2 when "SOC scaling" option was turned on
Massive thanks to @pmajor021 for finding and reporting this bug!

Bugfix: Move Battery2 power calculation outside SOC scaling function

---

Software/src/battery/BMW-I3-BATTERY.cpp

This PR writes cellvoltage amount for battery 2 also on i3
To make the cellmonitor page able to see and display the second battery
datalayer.battery2.info.number_of_cells = 97;

Bugfix: i3, Add cellvoltage amount for battery2

---

Software/src/battery/BMW-I3-BATTERY.cpp

This PR implements a sanity check on the min/max cellvoltage readings
The BMW i3 BMS can give strange values the first few seconds on a start, causing events to be incorrectly triggered. This has been reported in #774 
Incorrect readings range between 6000-8000mV. We now do a quick sanity check to see if value is below 4500. If it is, we use the value.

Bugfix: BMW i3, Add sanity check to minmax reading

---

Software/src/battery/RENAULT-ZOE-GEN1-BATTERY.cpp

This PR fixes the missing cell voltage 32. This has plauged the Zoe Gen1 for a while, 95 out of 96 cells have been visible.
Safer operation of the battery
We fix a mistake, where I typed [21] instead of [31]

Bugfix: Make all 96 cells work on Zoe Gen1

---

Software/src/battery/BMW-I3-BATTERY.cpp

fix forBMW i3 remaining capacity issue for 2nd battery #725
This PR implements a fix for issue #725
there was a typo during copy-pasting calculations from battery 1 to battery 2
and remove rows that do not exist for the first one
datalayer.battery2.info.total_capacity_Wh = (battery2_energy_content_maximum_kWh * 1000);  // Convert kWh to Wh
datalayer.battery2.status.remaining_capacity_Wh = battery2_predicted_energy_charge_condition;

Bugfix: BMW i3 remaining capacity issue for 2nd battery

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp

This PR attempts to fix the bug reported in #792
PERIODIC_BMS_RESET was a newly introduced feature in 8.x.x , it periodically reboots the battery BMS to prevent memory leaks. However, the LEAF battery sends some garbage data upon poweron, which we incorrectly interpreted as sane values. This caused many events to trigger once we resumed using the battery.
We now sanity check voltage measurements, if they are 0x3FF we skip using it. This is the default value when you boot

Bugfix: Make PERIODIC_BMS_RESET not cause events after reset

---

Software/src/battery/RENAULT-ZOE-GEN1-BATTERY.cpp
Software/src/devboard/utils/events.cpp
Software/src/devboard/utils/events.h

This PR adds a new event, EVENT_BATTERY_FUSE
On the Zoe, it is possible to detect that the internal fuse connecting the two battery halves have been blown. This is good info to relay back to the user, to let them know that the battery needs service
If the cell number 48 is low (<100mV), we trigger this event.
Example of battery with blown fuse:

Feature: Add event for blown fuse in Zoe battery

---

Software/src/inverter/PYLON-CAN.cpp

This PR fixes a small bug, we have only been writing status bits to the message 0x4251 , but not to the 0x4250 message
We fix this, to be able to better relay status when using the SEND_0 option
Thanks to Stefan for noticing this on the Discord :raised_hands:

Bugfix: Pylon CAN, add status bit writing to 0x4250

---

Software/USER_SECRETS.TEMPLATE.h

This PR fixes issue #738
To make it easier for new users to setup MQTT
Comment provides additional information on how to add credentials

Improvement: Update comment on MQTT password

---

Software/src/battery/BMW-IX-BATTERY.cpp

This PR implements regular requests for the BMS to start balancing and sets some valid values at startup.
Improves support for iX battery
Additional of two UDS routine requests sent regularly

Add iX balancing requests

---

Software/src/communication/contactorcontrol/comm_contactorcontrol.cpp

This PR fixes the bug reported in #679 
To make it easier for users to see actual contactor state
Currently datalayer.system.status.contactors_engaged only gets set to false if contractor opening is requested from the web page, not if it is requested by the inverter or estop.

Bugfix: Make Webserver show correct contactor status when Solax opens them

---

Software/Software.ino
Software/USER_SETTINGS.h
Software/src/charger/CHEVY-VOLT-CHARGER.cpp
Software/src/charger/NISSAN-LEAF-CHARGER.cpp
Software/src/datalayer/datalayer.h
Software/src/devboard/webserver/settings_html.cpp
Software/src/devboard/webserver/webserver.cpp

This PR moves the global charger variables from Software.ino into the datalayer
Better coding standards. Less includes and repetitions
Same way as other components, batteries, shunts, etc.

Cleanup: Move global charger variables to datalayer

---

Software/src/battery/CHADEMO-BATTERY.cpp
Software/src/battery/CHADEMO-SHUNTS.cpp
Software/src/battery/CHADEMO-SHUNTS.h
Software/src/battery/TESLA-BATTERY.cpp
Software/src/devboard/webserver/webserver.h

This PR introduces an event for detecting blown pyro fuse on Tesla batteries
To aid troubleshooting Tesla batteries
We now fire an event about fuse being blown if the voltage is 1.0V
Bonus, removed some unnecessary header include files for quicker compilation time

Improvement: Tesla blown pyro event

---

Software/USER_SETTINGS.h
Software/src/battery/TESLA-BATTERY.h

This PR cleans up the arrangement in USER_SETTINGS file. It has recently grown quite rapidly, so some new features were a bit all over the place. It also moves the Tesla LFP definition from the tesla.h file, into USER_SETTINGS
It was too easy for users to forget to set the LFP define, as reported in #805 
We move `LFP_CHEMISTRY` definition to USER_SETTINGS

Improvement: Move LFP option, rearrange USER_SETTINGS

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/communication/can/comm_can.cpp
Software/src/communication/contactorcontrol/comm_contactorcontrol.cpp
Software/src/datalayer/datalayer.h

This PR makes the BMS Reset only halt CAN message sending towards battery
The current implementation pauses CAN sending globally. That means that if you use a CAN based inverter + Period BMS reset, the inverter will also get starved of CAN messages while the reset is active. This is not desired, since it risks using power from battery while it is off. This new fix makes it pause only sending CAN towards battery while it is down.
Another issue was also that the original implementation only stopped ESP32.CAN , which was the first CAN interface. So it was impossible to use the feature right on setups where battery was not connected to fist CAN port
Moved the `isBMSResetActive` into the datalayer `datalayer.system.status.BMS_reset_in_progress`. Also simplified the code a bit.

Bugfix: Halt only CAN sending towards battery while BMS resetting

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp

This PR moves the `battery_allows_contactor_closing` writing for Nissan LEAF
Periodic BMS reset would always cause this red X on the webserver, confusing users
It also confused users, some packs never set this bit as stated in the LEAF wiki
_NOTE: with some Leaf BMS (so far only noticed on the 30kWh 2016) the line batteryAllowsContactorClosing = true is never set: https://github.com/dalathegreat/Battery-Emulator/blob/d759946cc41882576b6c27be095fffe0f47ba191/Software/src/battery/NISSAN-LEAF-BATTERY.cpp#L745 . This prevents the automatic contactor sequence. A workaround is to force the value to always true. So if you are having problems with the contactor sequence, change the above line to datalayer.system.status.battery_allows_contactor_closing = true;_
Instead of dynamically writing it …

Bugfix: Nissan LEAF, move battery-allows-closing writing

---

Software/src/inverter/SOLAX-CAN.cpp

Revert part of commit d8e1259eee0ee2a1a15ced42f22a919487a2db2a to fix issue with remaining kwh being reported incorrectly in Solax cloud app.
remaining kwh being reported incorrectly in Solax cloud app.
Use remaining kwh value instead of total kwh value.

Fix remaining kwh value for SOLAX-CAN

---

Software/USER_SETTINGS.h
Software/src/devboard/mqtt/mqtt.cpp
platformio.ini

This PR adds a new setting MQTT_QOS with a default value of 0 to stop crashes when the mqtt server is unavailable but still allow higher QoS when desired
It also updates the platformio config to use ESP 3.1.1 as it was using an out of date version
Fix for #824

Bugfix for mqtt crash & platformio update

---

Software/src/battery/PYLON-BATTERY.cpp

This PR maps the min/max cellvoltages to the global cellmonitor array
To get the values sent via MQTT properly. Bug was noticed in #813 
We now set amount of cells to 2 (was 0 previously), and map the min/max to the global array. This makes MQTT transmit the values

Pylon: Map cellvoltage min/max to array

---

Software/src/battery/BYD-ATTO-3-BATTERY.cpp

This PR changes the source for BYD Atto 3 temperature readings
Some users reported that values can glitch out when rebooting
Instead of reading all daughterboard temperatures and doing mathematical operations to figure out min/max, we now just use the temperature values sent via PID polls-
Bonus, this PR cleans up the code

BYD Atto 3: Change temperature reading + code cleanup

---

.github/workflows/compile-all-batteries.yml
.github/workflows/compile-all-combinations-part1-batteries-A-to-M.yml
Software/USER_SETTINGS.h
Software/src/battery/BATTERIES.h
Software/src/battery/FOXESS-BATTERY.cpp
Software/src/battery/FOXESS-BATTERY.h

This PR implements support for [FoxESS OEM HV2600 / ECS4100 batteries](https://github.com/dalathegreat/Battery-Emulator/wiki/Battery:-FoxESS-HV2600)
Requested feature in https://github.com/dalathegreat/Battery-Emulator/issues/828
We utilize the excellent https://github.com/FozzieUK/FoxESS-Canbus-Protocol repository for the CAN mappings :raised_hands:

New Battery: Add FoxESS support 

---

Software/src/devboard/mqtt/mqtt.cpp
Software/src/include.h

What
This PR fixes MQTT build errors when autodiscovery is disabled and mqtt is enabled as per issue #831 - pre-commit now run/checked :-)
Why
Build fails when #define HA_AUTODISCOVERY is commented out (disabled) in USER_SETTINGS.h
How
ifdefs changed to incorporate missing function definitions

Fix for compilation errors when HA_AUTODISCOVERY is commented out

---

Software/src/devboard/sdcard/sdcard.cpp
Software/src/devboard/sdcard/sdcard.h
Software/src/devboard/utils/events.cpp
Software/src/devboard/utils/events.h

This PR adds a warning event on SD initialization failure to make it more visible when a failure occurs. It includes the messages that a power reset is required if you end up in this state.

Add warning event if SD card fails to initialize

---

Software/src/battery/BMW-IX-BATTERY.cpp
Software/src/battery/BMW-IX-BATTERY.h

A fix to reset battery at BatEmu startup
Previously if BMS was already in error state at battery emulator it will fail to auto reset.
Sends a BMS reset can frame at boot. Also extends stale timeout as it's possible to trigger it in solar/use equilibrium.

iX Battery Type - Send BMS Reset at startup

---

Software/src/inverter/KOSTAL-RS485.cpp

Kostal RS485 protocol CRC calculation and byte scrambling improvements
Byte scrambling has been resolved, allowing the removal of 2-byte float tweaks from the code. Additionally, CRC calculation can now be performed correctly.

kostal inverter crc and byte scrambling rewritten

---

Software/src/battery/TESLA-BATTERY.h

This PR updates the default rampdown powervalue for Tesla batteries
We had an user that overcharged their Tesla LFP pack, since the current values still allow for almost 7kW charging at 97%SOC.
Instead of starting the rampdown from 15kW at 90%, we now start at 10kW. This change will hopefully allow for the cellvoltage safeties to have more time to react, and write allowed power to 0W incase it starts to get out of hand

Tesla S/3/X/Y: Update rampdown power

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp

This PR fixes the issues noticed when using Double-Battery with Kia-Hyundai 40/64 batteries
- 2nd battery not closing contactors
- 2nd battery not showing cellvoltages
Safer operation of battery
Duplicate code handling of 0x200 message. Fix copypaste mistakes on 2nd battery code

Kia64: Bugfix for using Double-Battery

---

Software/src/inverter/PYLON-CAN.cpp

This PR fixes a compilation error, when using SET_30K_OFFSET
We fix is to users can use Pylon CAN with all inverters
Fix the compilation errors

Pylon: Fix compilation error when using SET_30K_OFFSET

---

Software/src/battery/BOLT-AMPERA-BATTERY.h
Software/src/battery/IMIEV-CZERO-ION-BATTERY.h
Software/src/battery/JAGUAR-IPACE-BATTERY.h
Software/src/battery/NISSAN-LEAF-BATTERY.h
Software/src/battery/PYLON-BATTERY.h
Software/src/battery/RANGE-ROVER-PHEV-BATTERY.h
Software/src/battery/RENAULT-KANGOO-BATTERY.h
Software/src/battery/RENAULT-TWIZY.h
Software/src/battery/RENAULT-ZOE-GEN1-BATTERY.h
Software/src/battery/RENAULT-ZOE-GEN2-BATTERY.h

This PR lowers the threshold needed to trigger a cellvoltage warning on most battery implementations
Many batteries were left at the default 500mV diff value, before raising an event. The idea was that feedback should be gathered from each integration, and these limits refined over time. They have now been set to the same value for a long time, so this change is long overdue. 
We now tighten the limits significantly for those batteries left with essentially un-set limits

Improvement: Tigthen cellvoltage warnings on most batteries

---

Software/src/inverter/SOLAX-CAN.cpp

On Solax CAN message 187E should contain the total capacity of the battery.
To make solax modbus report the bms capacity value correct.
Report the correct value.

SOLAX-CAN: message 187E should contain total_capacity.

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp

This PR fixes the Wh bug reported in https://github.com/dalathegreat/Battery-Emulator/issues/825#issuecomment-2615887506
Make the Wh value more realistic on 24kWh packs. 30/4/62kWh packs automatically fill in the available Wh based on maxGids, which is not available on 24kWh packs
We now scale the 24kWh value based on SOH%

Nissan LEAF: Make Wh max value more realistic based on SOH

---

Software/USER_SETTINGS.h
Software/src/datalayer/datalayer.h
Software/src/devboard/webserver/webserver.cpp
Software/src/inverter/BYD-CAN.cpp

This PR fixes bug https://github.com/dalathegreat/Battery-Emulator/issues/868 by introducing a microfeature, showing the detected inverter in webserver instead of spamming it every second to log
Easier debugging. Less taxing on system resources
We now show the detected inverter brand in the webserver (dont mind my miss-spelling in test data :sweat_smile: )

Microfeature: Add inverter brand to datalayer and webserver

---

.github/workflows/compile-all-inverters.yml
Software/USER_SETTINGS.h
Software/src/inverter/FERROAMP-CAN.cpp
Software/src/inverter/FERROAMP-CAN.h
Software/src/inverter/INVERTERS.h

This PR implements a dedicated protocol for the Ferroamp inverters.
Previously this protocol has relied on the Pylon protocol, but the changes introduced in 8.2.0 and onwards has broken support for Ferroamp. Apparently this inverter does not like to see more strict Pylon protocol enforcement.
We branch out a spinoff specifically for Ferroamp based on the last working 8.1.0 version.

New inverter: Add dedicated Ferroamp pylon spinoff

---

Software/Software.ino
Software/src/inverter/SOLAX-CAN.cpp

Move init of events to earlier in initialisation, to prevent and event being generated before the event system is initialised.
Prevent crashes due to uninitialized values/pointers.
Move the init_events function call to earlier in the setup routine.

Init event handling before any use of events

---

Software/src/inverter/BYD-CAN.cpp

This PR implements a safety check to the BYD CAN protocol. Incase the battery no longer wants to charge, we send 100% SOC, and incase it no longer wants to discharge, we send 0% SOC
To avoid offgrid Deye inverters overdischarging batteries, as reported in https://github.com/dalathegreat/Battery-Emulator/issues/873
If checks

BYD CAN: Safety, add overriding SOC incase of 0W allowed

---

Software/src/inverter/GROWATT-HV-CAN.cpp

This PR implements user customizable charge/discharge voltage limits
Fixes #880 
The configurable settings are in the Webserver (and in USER_SETTINGS.h). These are now utilized by the Growatt HV protocol. Incase user does not enable this feature, the hardcoded min/max design limits are used instead.

Bugfix: Growatt HV, Add user customizable charge/discharge voltage

---

Software/src/battery/BYD-ATTO-3-BATTERY.cpp
Software/src/battery/BYD-ATTO-3-BATTERY.h
Software/src/datalayer/datalayer_extended.h
Software/src/devboard/webserver/advanced_battery_html.cpp

This PR makes it so you can track all 10 temperature sensors inside the battery
It also adds a method to skip using a specific temperature sensor, if you know it is broken.
Example, Sensor number 4 broken
Better way to monitor the battery.
Also adds a way to use a battery without needing to replace a daughterboard with broken temp sensor (Note, requires deep knowledge of actual battery status)
All 10x measurements added to extended datalayer
Configurable option in .h file, SKIP_TEMPERATURE_SENSOR_NUMBER that can be tuned between 1-10 if needed

BYD Atto3: Add 10 temperature sensors to datalayer

---

Software/Software.ino
Software/src/datalayer/datalayer.h
Software/src/devboard/webserver/webserver.cpp

This PR implements an user requested feature, Webserver to show what is limiting power in/out of the battery.
Feature requested by Discord users
We implement a few new variables to the datalayer
- user_settings_limit_charge
- user_settings_limit_discharge
Based on these, we show in the Webserver when the charge/discharge amperage values are limited by the battery itself (BMS), or by the user configurable settings (Manual)
We also show if the Inverter or the Battery is the limiting factor, at the Battery Charging/Discharging text, using the following variables
- inverter_limits_discharge
- inverter_limits_charge

Feature: Add limiting factor to Webserver

---

Software/Software.ino

This PR enables task watchdogs for both the core loop and the connectivity loop. The task watchdog prevents a process from spinning indefinitely and locking up a core.
During the refactoring in 5.x.x, task watchdogs were accidentally disabled! This could lead to unresponsive cores and system instability. See issue [#877](https://github.com/dalathegreat/Battery-Emulator/issues/877).
We now trigger a panic event in case of a lockup, ensuring the board can recover from fault scenarios more reliably.

Feature: Enable task watchdogs

---

Software/src/battery/RJXZS-BMS.cpp
Software/src/devboard/utils/events.cpp
Software/src/devboard/utils/events.h

This PR adds a generic event for when the RJXZS BMS has errors active
Easier for end users to understand the system. As reported in https://github.com/dalathegreat/Battery-Emulator/issues/886
Incase the fault code bits are high, we fire an info event that tells the user:
"Error code active in RJXZS BMS. Clear via their smartphone app!"

Feature: Add event for RJXZS BMS error and guide user how to clear

---

Software/src/battery/RJXZS-BMS.cpp

This PR fixes a bug that caused all current directions to appear as charging
Forgotten during development: https://github.com/dalathegreat/Battery-Emulator/issues/882
We now check message 0x51 and take the direction from this message. Based on this info we add sign to value

Bugfix: Add current direction for RJXZS

---

Software/src/devboard/safety/safety.cpp

This PR fixes the bug reported in #903 
Safer operation of battery
Incase `datalayer.battery.status.bms_status == FAULT` we now force allowed charge/discharge values to 0 always in SAFETY.cpp

Bugfix: Add writing of values to 0 incase of critical fault

---

Software/src/battery/BYD-ATTO-3-BATTERY.cpp

This PR implements cellvoltage reading for BYD Atto 3
Better monitoring of battery
Code based on the reverse engineering done in https://github.com/dalathegreat/Battery-Emulator/issues/894 by @demon1300 :raised_hands:

Feature: Add cellvoltage reading for BYD Atto 3

---

Software/Software.ino
Software/USER_SETTINGS.h
Software/src/battery/BATTERIES.h
Software/src/battery/VOLVO-SPA-HYBRID-BATTERY.cpp
Software/src/battery/VOLVO-SPA-HYBRID-BATTERY.h
Software/src/datalayer/datalayer_extended.h
Software/src/devboard/webserver/advanced_battery_html.cpp
Software/src/devboard/webserver/webserver.cpp

This PR implements basic read-only support for [Volvo hybrid batteries](https://github.com/dalathegreat/Battery-Emulator/wiki/Battery:-Volvo-SPA-S60-90-V60-90-XC60-90-Hybrid-batteries).
Add support for the newest 18.83 kWh hybrid batteries.
Based on the existing Volvo full-electric batteries XC40/Polestar with a few differences.

Add basic read-only support for Volvo hybrid batteries

---

Software/src/battery/BMW-I3-BATTERY.cpp

This PR makes the max kWh value reported by battery more accurate 
Bug, reported in https://github.com/dalathegreat/Battery-Emulator/issues/914
Instead of rounding the values down to kWh, we increase resolution to Wh.
battery_energy_content_maximum_kWh becomes battery_energy_content_maximum_Wh

Bugfix: BMW i3, Make kWh more accurate

---

Software/USER_SETTINGS.h
Software/src/datalayer/datalayer.h
Software/src/devboard/utils/led_handler.cpp
Software/src/devboard/utils/led_handler.h
Software/src/devboard/utils/types.h
Software/src/system_settings.h

This PR makes the LED pattern customizable in USER_SETTINGS.h
Previously you had to edit Software/src/system_settings.h to get the LED modes to change. Not a lot of users even knew about this feature
Now we move it to USER_SETTINGS, for easy tuning

Microfeature: Make LED modes customizable in USER_SETTINGS

---

Software/src/communication/can/comm_can.cpp

This PR fixes a bug where the incoming CAN-FD frames are logged twice
Bug, reported in https://github.com/dalathegreat/Battery-Emulator/issues/938
We now skip logging twice :)

Bugfix: Prevent logging incoming FD twice

---

Software/src/communication/can/comm_can.cpp
Software/src/datalayer/datalayer.h
Software/src/devboard/safety/safety.cpp
Software/src/devboard/utils/events.cpp
Software/src/lib/miwagner-ESP32-Arduino-CAN/CAN.c
Software/src/lib/miwagner-ESP32-Arduino-CAN/CAN.h
Software/src/lib/miwagner-ESP32-Arduino-CAN/ESP32CAN.cpp
Software/src/lib/miwagner-ESP32-Arduino-CAN/ESP32CAN.h

This PR improves low level performance of the CAN driver. It also changes how CAN TX fail events are handled
Performance improvements are nice :sunglasses: 
By moving out serial printing / event triggering from inside the CAN driver, we increase performance significantly in the event that it would fail to send. The SAFETY.cpp loop now keeps track of every CAN interface, and checks every 1000ms if something has occurred. 
The PR also changes a native CAN TX fail event from Error -> Warning. This was an old assumption that a single TX fail on this CAN channel would be tied to battery, but with the new can_config option the battery is necessarily not connected to the CAN native port. We keep the 60s without CAN from battery as an error event.

Improvement: Optimize CAN-Native driver and event handling

---

Software/src/lib/miwagner-ESP32-Arduino-CAN/CAN.c
Software/src/lib/miwagner-ESP32-Arduino-CAN/CAN.h
Software/src/lib/miwagner-ESP32-Arduino-CAN/ESP32CAN.cpp

This PR removes an old delay() workaround in the CAN native driver
More performance
Previosly we had implemented a hacky yield function, that blocked further CAN sending for 20ms incase one CAN message fails to send. This was done to avoid locking up the board. **Something** has changed in the ESP32, and now this workaround is no longer needed! Good for us, since removing it makes the function call much faster.
Bonus, this PR also gets rid of the three compilation warnings that were present in platformIO
Fixes #667

Improvement: More CAN performance

---

Software/src/battery/BMW-I3-BATTERY.cpp
Software/src/battery/BMW-I3-BATTERY.h

This PR fixes a bug, where BMW i3 would not transmit cellvoltages via MQTT
Fixes #920 
We set the amount of cells correctly (96 instead of 97), and directly at startup

BMW i3: MQTT not sending cellvoltages

---

Software/src/battery/DALY-BMS.cpp
Software/src/battery/DALY-BMS.h
Software/src/devboard/webserver/settings_html.cpp

Some minor leftover changes I made to the Daly BMS code. As of today battery is in daily use and works fine.
The changes include:
- Adjust webservice to display RS485 for battery connection when `RS485_BATTERY_SELECTED` is set
- Add a low temperature limit to Daly BMS (checking the various battery datasheets this could be way more complicated including charge/discharge differences, temperature to power curves, 30s peak power etc. For now this very simple approach should keep the battery safe when having the maximum charge/discharge low enough)
- Adjust default Daly BMS settings to the most common LV battery voltage range
Final installation Pictures:

Minor (final) Daly BMS  changes

---

Software/src/lib/adafruit-Adafruit_NeoPixel/Adafruit_NeoPixel.cpp
Software/src/lib/adafruit-Adafruit_NeoPixel/Adafruit_NeoPixel.h
Software/src/lib/adafruit-Adafruit_NeoPixel/esp.c

This PR updates the Adafruit_NeoPixel library
To remove the compiler warning
```
In file included from Software/src/lib/adafruit-Adafruit_NeoPixel/esp.c:23:
/packages/framework-arduinoespressif32-libs/esp32/include/driver/deprecated/driver/rmt.h:18:2: warning: #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h" [-Wcpp]
18 | #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h"
|  ^~~~~~~
```
By using the latest content available from the [Adafruit_NeoPixel](https://github.com/adafruit/Adafruit_NeoPixel) library.

Update Adafruit_NeoPixel library to commit fd74287

---

Software/src/battery/MEB-BATTERY.cpp
Software/src/communication/can/obd.cpp
Software/src/communication/can/obd.h

MEB needs OBD requests to be canFD.
No response from battery if sent as normal can.
Add a parameter to the function call so the calling side can choose between normal can and FD can.

Make transmit_obd_can_frame canFD aware.

---

Software/src/inverter/GROWATT-HV-CAN.cpp

This PR implements batch sending of the periodic CAN data for Growatt HV protocol
By trying to send 20 messages at the same time, we risk easily overflowing the CAN send buffer, as seen in https://github.com/dalathegreat/Battery-Emulator/issues/960#issue-2907055552
We now instead send the messages in 5 batches (5x4 messages), with 10ms inbetween each batch send. The same approach has been used on other CAN heavy inverters like Foxess

Bugfix: Growatt HV: Refactor CAN sending to be performed in batches

---

Software/src/battery/MEB-BATTERY.cpp
Software/src/datalayer/datalayer_extended.h
Software/src/devboard/webserver/advanced_battery_html.cpp
Software/src/devboard/webserver/webserver.cpp

Adds:
BMS_fault_performance
BMS_fault_emergency_shutdown_crash
BMS_error_shutdown_request
BMS_error_shutdown
SOH calculation.
Fixes:
(hopefully) the capacity calculation from Ah to kWh.
To help with debugging battery packs where the pyro went off, or with precharge issues.
Resolves issue where kWh reported was larger than design capacity.
Adds the four fields to the extended datalayer and to the webpage code.

MEB: Improve MEB status output.

---

Software/src/devboard/mqtt/mqtt.cpp

Updating mqtt topic processing to incorrect topic matching when a shorter topic than expected is used which in some situations could cause a crash.
Fixes #963

MQTT Crash bugfix

---

Software/src/battery/TESLA-BATTERY.cpp

Noticed a typo in TESLA-BATTERY.cpp. There was two flags decoded from the same source bit.

Update typo while decoding error flags in TESLA-BATTERY.cpp

---

Software/src/battery/RENAULT-TWIZY.h

Adds function declarations to the header file for the Renault Twiggy battery
To fix the compilation error seen in #1006.
Fixes #1006
By defining missing declarations in header file created in #537.

Fix compilation error Renault Twizy

---

Software/src/battery/TESLA-BATTERY.cpp

This PR extends the voltage range check for determining if the Pyrofuse is blown on a tesla battery
The original check did not catch all cases of blown pyro, since it just checked if voltage is 1.0VDC
The new check verifies if the voltage is between 0.5V-5.0V, and if it is, we fire the event!

Bugfix: Tesla, extend pyrofuse event check

---

Software/src/inverter/FERROAMP-CAN.cpp
Software/src/inverter/PYLON-CAN.cpp

This PR fixes the compilation warning in Ferroamp and Pylon CAN protocol
To make build system work again
Careful assigning of correct bits to u8 value

Housekeeping: Fix compilation warning from build system

---

Software/Software.ino
Software/src/devboard/utils/logging.cpp

This PR fixes a crash (Core  1 panic'ed (LoadProhibited). Exception was unhandled.) that would occur when the DEBUG_LOG option was enabled in the code
Crashes are bad. Hopefully fixes https://github.com/dalathegreat/Battery-Emulator/issues/972
Quickfix, remove the faulty code section

Crash fix: Remove faulty DEBUG_LOG section

---

Software/src/battery/BMW-IX-BATTERY.cpp

This PR updates the values of the CAN messages sent for the BMW iX batteries.
To match the content with the messages seen in CAN logs.

BMW iX: update values in CAN messages

---

Software/src/battery/RENAULT-ZOE-GEN2-BATTERY.cpp

This PR improves the ZoeGen2 handling
User feedback on integration
- We now send ID 0x373 every 100ms instead of 200ms, and with the correct still alive formatting
- We now poll the current every second, instead of every 8.2seconds. The current measurement is very important for the integration
- We now use the 12V measurement, and trigger an event if it goes lower than 11V

Improvement: Zoe Gen2, feedback fixes

---

Software/Software.ino
Software/src/datalayer/datalayer.h
Software/src/devboard/webserver/webserver.cpp

This PR implements CPU temperature monitoring, for the ESP32 chip running all the Battery-Emulator code
Paving way for adding safeties for CPU temp monitoring. This first stage now adds the value to webserver
CPU temperature value now shown at the top of the Webserver page, next to the Hardware used:

Microfeature: Add CPU temperature monitoring in Webserver :thermometer: 

---

Software/src/battery/TESLA-BATTERY.cpp
Software/src/datalayer/datalayer.h
Software/src/devboard/webserver/advanced_battery_html.cpp
Software/src/devboard/webserver/webserver.cpp

What
This PR implements BMS ECU reset for the Tesla BMS (checks to make sure contactors are open and ECU allows reset), and some basic logging of UDS responses. Needs wider testing and feedback.
Why
Once the BMS goes into an error state, manual intervention is needed (unplug power for a time, yellow connector disconnect etc.)
How
Implementing the same CAN UDS command sequences Tesla's tools do.

Feature: Add Tesla BMS ECU reset, basic UDS response logging

---

Software/src/battery/BYD-ATTO-3-BATTERY.cpp
Software/src/battery/BYD-ATTO-3-BATTERY.h

This PR implements support for Standard range 50kWh Atto 3 batteries.
Current implementation does not support 50kWh packs, only extended range 60kWh packs. Fixes #1022 
We now startup in NOT_DETERMINED_YET state, and later on switch between STANDARD_RANGE or EXTENDED_RANGE
Switching between these modes happens automatically, and it will affect the following values:
- Max pack voltage
- Min pack voltage
- Cell count (104 vs 125)
- Estimated SOC from voltage (New map added for standard range
- Total pack capacity
Testers wanted! Both Extended range and Standard range!

New Battery: Add support for 50kWh standard range Atto3

---

Software/Software.ino
Software/src/datalayer/datalayer.h
Software/src/devboard/webserver/settings_html.cpp

This PR implements the possibility to do negative SOC scaling
Some inverters restrict the possibility to use the entire battery. For instance with Fronius inverters, it is not possible to go below 5% battery SOC%. This can now be circumvented, by applying negatively scaled SOC.
User requested feature, fixes 1039
The settings page now accepts -10.0% as the new minimum
Example, real battery SOC is at 1.2%, but we tell inverter that we are still at 10.2%. This would be perfect for an inverter brand that never allows discharging past 10%.

Feature: Add negative SOC scaling 📉

---

Software/src/devboard/safety/safety.cpp
Software/src/devboard/utils/events.cpp
Software/src/devboard/utils/events.h

This PR implements a safety check for CPU temperature
So we can alert end users if the hardware is getting too hot, affecting lifespan of the hardware
We now check if the CPU temp exceeds 80*C, and if it does, we raise a warning event with a helpful note
"Battery-Emulator CPU overheating! Increase airflow/cooling to increase hardware lifespan!"

Feature: Add ESP32 CPU overheat event

---

Software/src/battery/CMFA-EV-BATTERY.cpp
Software/src/battery/CMFA-EV-BATTERY.h

This PR implements scaling on the raw SOC value reported by the CMFA EV battery
Raw SOC value will show 90% when full, so we cannot use it as-is
The software adds two new defines
```
#define MAXSOC 9000  //90.00 Raw SOC displays this value when battery is at 100%
#define MINSOC 500  //5.00 Raw SOC displays this value when battery is at 0%
```
We use these to re-scale the raw SOC to a usable value, using a static version of a stochastic oscillator (https://en.wikipedia.org/wiki/Stochastic_oscillator). This makes it possible to get a nice usable display value out of the raw value.

Bugfix: Add rescaling of CMFA-EV raw SOC

---

Software/src/devboard/utils/events.cpp

This PR makes the Equipment Stop event easier to understand
Many accidentally activate this, and have no clue how to get out of it
The text is changed from:
- EQUIPMENT STOP ACTIVATED!!!
To:
- User requested stop, either via equipment stop circuit or webserver Open Contactor button

Improvement: Update description for Equipment Stop

---

Software/src/battery/BMW-IX-BATTERY.cpp

This PR adds message expected by the SME (BMW iX battery ECU) according to information from Discord, and respective static message content as deducted from car logs.
- To prepare the battery emulator to be able to (in the future) send the messages that are needed for the SME to work outside the car.
- To ensure it is clear which message content (specific bytes) is not known yet, such that we can focus our efforts on finding out how to replicate those specific bytes.
- The bytes that are static in the car logs have been added to the messages.
- As not all data is defined, some `TODO:`'s have been defined, and the respective `.data` line in the message definition has been commented out. Once the full message has been deciphered, the lines can be activated.
- As some content can be fixed …

BMW iX: add messages expected by SME and static message content

---

Software/src/datalayer/datalayer_extended.h
Software/src/devboard/webserver/advanced_battery_html.cpp
Software/src/devboard/webserver/webserver.cpp

This PR adds a button in the Webserver, More Battery Info page, to be able to have user request NVROL reset on demand.
To aid development in PR #1017

Microfeature: Add button for NVROL reset (Zoe PH2)

---

Software/src/inverter/BYD-MODBUS.cpp

This PR updates the BYD reported FW/Serial data
To increase compatibility and not appear as an old battery from 2021
This PR also fixes the issue that Fronius Software "ROW 1.36.5-1" released on April 23rd breaks compatibility with the Battery-Emulator project.
We update the FW version from 3.16 -> 3.26. We also add a default serial number to the data field.

BYD Modbus: Update FW and Serial number

---

Software/src/devboard/hal/hw_stark.h

This PR changes the default pin used for SMA Enable line signal
Initial implementation picked a free GPIO (pin19). This pin is not optimal, since the Stark CMR has a dedicated SIGNAL IN pin (pin2) that can take the 11V input directly
19 changes to 2

Bugfix: Edit SMA inverter input pin for Stark CMR

---

Software/src/battery/BATTERIES.cpp
Software/src/battery/BATTERIES.h
Software/src/battery/RENAULT-ZOE-GEN1-BATTERY.cpp
Software/src/battery/RENAULT-ZOE-GEN1-BATTERY.h
Software/src/communication/can/obd.cpp
Software/src/devboard/webserver/webserver.cpp

This PR implements a minimal, abstract base class, which is a new type of battery API. When later implemented by all batteries, it allows all battery code to be compiled into common image. This first stage implements a minimal change: one battery implementation (Zoe Gen1) changed to this design.
This PR contains no functionality changes.
A base class approach is needed to gradually convert the code base to support common image.
CanBattery base class is an abstract base class for batteries (supporting CAN bus). The API is identical to the C-style API but allows in the future multiple run-time implementations of batteries.

Common base class for batteries

---

Software/src/battery/VOLVO-SPA-BATTERY.h

This PR tweaks the fully charged voltage allowed for 96S SPA batteries
Data from vehicle now available!
We allow charging to 408V, with 4.25V/cell max

Volvo SPA: Tweak voltage limits for 96S battery

---

Software/src/communication/rs485/comm_rs485.cpp
Software/src/inverter/BYD-MODBUS.cpp
Software/src/inverter/BYD-MODBUS.h
Software/src/inverter/INVERTERS.cpp
Software/src/inverter/INVERTERS.h

This PR implements a minimal, abstract base class for **inverter protocol** implementations. When later implemented by all inverter protocols, it allows all inverter code to be compiled into common image. This first stage implements a minimal change: one inverter implementation (BYD Modbus) changed to this design with relevant adaptation code.
This PR contains no functionality changes.
A base class approach for inverter protocols is needed to gradually convert the code base to support common image.
InverterProtocol and ModbusInverterProtocol abstract classes are the base classes for batteries (first supporting only Modbus). The API is identical to the C-style API but allows in the future multiple run-time implementations of inverter protocols.

Common base class for inverter protocols

---

Software/src/battery/BATTERIES.cpp
Software/src/battery/BATTERIES.h
Software/src/battery/CanBattery.h
Software/src/battery/JAGUAR-IPACE-BATTERY.cpp
Software/src/battery/JAGUAR-IPACE-BATTERY.h
Software/src/battery/RENAULT-ZOE-GEN1-BATTERY.h
Software/src/communication/can/comm_can.h

Convert Jaguar I-PACE battery implementation to use the common base class. The concrete battery class selected is indicated by SELECTED_BATTERY_CLASS define.

Use common battery base class for Jaguar Ipace battery

---

Software/src/devboard/safety/safety.cpp
Software/src/devboard/utils/events.cpp
Software/src/devboard/utils/events.h

This PR adds a high temperature Fault event
To be able to perform a graceful shutdown incase the Battery-Emulator overheats. It is better to stop gracefully, than wait for CPU to crash.
If the CPU temperature exceeds 110°C, we Fault the emulator. If we are able to cool down below 105°C, we resume operation.

Microfeature: Add high temperature fault event :thermometer: 

---

Software/Software.ino

This PR fixes a startup crash loop that occurs when using Modbus communication
By first initializing which inverter to use, and then starting the init_rs485, the crash is avoided

Fix startup crash when using Modbus inverter

---

Software/src/battery/BYD-ATTO-3-BATTERY.cpp
Software/src/datalayer/datalayer_extended.h
Software/src/devboard/webserver/advanced_battery_html.cpp
Software/src/devboard/webserver/webserver.cpp

This PR makes it possible to unlock crashed BYD Atto3 batteries :closed_lock_with_key: 
When Atto 3 EVs are crashed hard enough to trigger airbags, the BMS will lock itself and prevent contactor closing. The SOC% will also stop updating. This is problematic, and users of these batteries have suffered. Previous workarounds have been to bypass contactors, and estimate SOC% from voltage.
This is no longer a problem, since we now have the OEM commands to unlock crashed batteries :raised_hands: 
This feature adds a button in the "More Battery Info" page in the webserver, that when pressed will unlock the crashed battery.
After battery is unlocked, you can remove the "USE_ESTIMATED_SOC" from the BYD-ATTO-3-BATTERY.h file. Enjoy the easy contactor closing that this feature brings :raised_hands: …

Atto3: Add crashed BMS unlocking :lock: 

---

Software/src/battery/DALY-BMS.cpp
Software/src/battery/ECMP-BATTERY.cpp
Software/src/battery/FOXESS-BATTERY.cpp
Software/src/battery/IMIEV-CZERO-ION-BATTERY.cpp
Software/src/battery/JAGUAR-IPACE-BATTERY.cpp
Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp
Software/src/battery/KIA-HYUNDAI-HYBRID-BATTERY.cpp
Software/src/battery/MG-5-BATTERY.cpp
Software/src/battery/PYLON-BATTERY.cpp
Software/src/battery/RANGE-ROVER-PHEV-BATTERY.cpp
Software/src/battery/RENAULT-KANGOO-BATTERY.cpp
Software/src/battery/RENAULT-TWIZY.cpp
Software/src/battery/RJXZS-BMS.cpp
Software/src/battery/SANTA-FE-PHEV-BATTERY.cpp
Software/src/battery/SONO-BATTERY.cpp

This PR sets the battery_allows_contactor_closing = true; on some integrations that were missing it
So users can enjoy automated GPIO contactor closing on these batteries. One user reported that their Kangoo pack was not working with GPIO, this PR fixes that issue.
We set the datalayer.system.status.battery_allows_contactor_closing = true; inside the setup_battery function on the integrations that were missing it.

Bugfix: Add battery closing allowed flag on startup

---

Software/src/battery/RENAULT-ZOE-GEN2-BATTERY.cpp
Software/src/battery/RENAULT-ZOE-GEN2-BATTERY.h

This PR implements the NVROL reset function described on [ljames28/Renault-Zoe-PH2-ZE50](https://github.com/ljames28/Renault-Zoe-PH2-ZE50-Canbus-LBC-Information?tab=readme-ov-file#commands), and as is mentioned on #587.
This PR shall be checked by someone that has a Renault Zoe Gen2 battery.
Fixes #587
By implementing a new function `transmit_reset_nvrol_frames()` that implements the following pseudo code:
```
cansend 18DADBF1#021003AAAAAAAAAA
sleep 0.1
cansend 18DADBF1#043101B00900AAAA
sleep 1
cansend 18DADBF1#021003AAAAAAAAAA
sleep 0.1
cansend 18DADBF1#042E928101AAAAAA
sleep 30
```
Source: [ljames28/Renault-Zoe-PH2-ZE50 | Commands](https://github.com/ljames28/Renault-Zoe-PH2-ZE50-Canbus-LBC-Information?tab=readme-ov-file#commands)

Renault Zoe Gen2: add NVROL reset function

---

Software/src/battery/BYD-ATTO-3-BATTERY.cpp
Software/src/battery/BYD-ATTO-3-BATTERY.h
Software/src/datalayer/datalayer_extended.h
Software/src/devboard/webserver/advanced_battery_html.cpp

This PR tweaks the SOC% voltage lookup tables + add new PID polls  + removes estimated charge speed in favor of actual BMS allowed charge speed
Voltage table: To avoid large cell deviations that occur when targeting the same pack voltage as the car would charge the cells to
PID polls: To gain more info about the BYD Atto 3 batteries
Charge allowed W: To make safer end of charge rampdown, without making the LFP cells imbalanced
Preface, SOC% estimation via voltage is bad, especially bad when it comes to LFP cells, which have an extremely flat voltage curve. If you have a locked Atto3 battery, try to unlock it with the unlock command script to start with.
The new PID polls (14x) are available via the "More Battery Info" page
One of the new PID polls are "Allowed Charge Power". By using this …

BYD Atto 3: Tweak SOC voltage estimation lookup tables + More PID polls!

---

Software/Software.ino

This PR overhauls the scaled value calculations
The calculation has remained untouched for a long time. It has many bugs and missing functionality
Fixes #1104 
Also fixes #396 
Partially makes #926 better
We fix several issues:
- When negative scaling is used, it no longer results in the capacity remaining jumping to 0 for the whole range, as reported in 1104
- When double batteries are used, we now report the total capacity for bat1+bat2 towards the inverter
- We fix a place in the code where division by 0 could occur (if user sets min/max SOC setting to same values), making the board crash :warning: 
- We increase system performance, by removing millis() calls in the update_calculated_values() function
On Double Battery setups, the capacity is now summed together (Visible in Battery1 …

Bugfix: Scaled capacity overhaul

---

Software/src/inverter/AFORE-CAN.cpp
Software/src/inverter/AFORE-CAN.h
Software/src/inverter/BYD-CAN.cpp
Software/src/inverter/BYD-CAN.h
Software/src/inverter/INVERTERS.h

Yet another inverter protocol converted to use the common base class.

Use common base class for Afore CAN inverter protocol

---

Software/Software.ino
Software/src/charger/CHARGERS.cpp
Software/src/charger/CHARGERS.h
Software/src/charger/CHEVY-VOLT-CHARGER.cpp
Software/src/charger/CHEVY-VOLT-CHARGER.h
Software/src/charger/CanCharger.h
Software/src/charger/NISSAN-LEAF-CHARGER.cpp
Software/src/charger/NISSAN-LEAF-CHARGER.h

This PR converts the two charger implementation to use a common base class.
To support the future common image with run-time selectable chargers as well.
We follow a similar pattern as with batteries and inverter protocols: A common abstract base class is defined for CAN chargers and both charger implementations implement that interface. Charger is setup by instantiating the corresponding class and the old API is implemented by calling methods on the instance.

Chargers use a base class

---

.github/workflows/compile-all-double-batteries.yml
Software/src/battery/BATTERIES.cpp
Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/battery/NISSAN-LEAF-BATTERY.h
Software/src/charger/NISSAN-LEAF-CHARGER.cpp
Software/src/datalayer/datalayer.h
Software/src/datalayer/datalayer_extended.h

This PR ports Nissan Leaf battery to use the class interface. In addition this introduces a way to implement double battery support with the new class interface.
This is part of a continuous effort to bring all batteries to class based interface.
Nissan Leaf battery specific code is implemented as C++ class. Two instances of the same class is used when double battery support is activated. This design eliminates the need of duplicate code. Each instance uses separate CAN bus and writes to a different part of the "datalayer" similarly as the earlier double battery implementation. Static variables are moved to class members to allow two identical copies to exist in memory at the same time. The two battery instances operate identically with the exception of the first battery only updating the …

Nissan Leaf battery class with double battery support

---

Software/Software.ino
Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/charger/CHARGERS.cpp
Software/src/charger/CHARGERS.h
Software/src/charger/CHEVY-VOLT-CHARGER.cpp
Software/src/charger/CHEVY-VOLT-CHARGER.h
Software/src/charger/CanCharger.h
Software/src/charger/NISSAN-LEAF-CHARGER.cpp
Software/src/charger/NISSAN-LEAF-CHARGER.h
Software/src/communication/can/comm_can.cpp
Software/src/datalayer/datalayer.h
Software/src/devboard/safety/safety.cpp
Software/src/devboard/webserver/settings_html.cpp
Software/src/devboard/webserver/webserver.cpp

All charger code is built regardless of charger selection at build-time. Charger selection is determined at run-time. Code relying on charger functionality uses the common charger interface directly. Web server build-time dependency on charger type eliminated.
This is a continuation towards the goal of having all selections made at run-time to support a common image.

All chargers built regardless of build-time selection

---

Software/src/inverter/FERROAMP-CAN.cpp
Software/src/inverter/FERROAMP-CAN.h

This PR is yet another straight-forward inverter protocol implementation conversion to use the base class.

Ferroamp CAN inverter protocol code converter to use the base class

---

Software/src/battery/BMW-IX-BATTERY.cpp
Software/src/battery/BMW-IX-BATTERY.h
Software/src/datalayer/datalayer_extended.h
Software/src/devboard/webserver/advanced_battery_html.cpp
Software/src/devboard/webserver/webserver.cpp

This PR:
- adds functionality to close and open the contactors for BMW iX batteries
- adds buttons to the "More battery info" page to close and open the contactors
- updates the webserver to clarify that ✅  and ❌ indicate that the battery/inverter **allows contactors closing**.
To support contactor closing for the BMW iX batteries.
Updates to the BMW iX code, including functions to close the contactors, keep the contactors closed, open the contactors, and to handle the user requests from the webserver to open or close the contactors.

BMW iX: add functionality to close and open contactors

---

Software/src/inverter/SMA-BYD-HVS-CAN.cpp

This PR:
- changes `SMA_158` content depending on `battery_allows_contactor_closing`, rather than `inverter_allows_contactor_closing`
- adds `CAN_inverter_still_alive` for all CAN messages sent by SMA
- To ensure the inverter does not receive an error bit, whenever `inverter_allows_contactor_closing` is `false`. This error bit should be sent by the battery emulator and received by the inverter when the battery does not allow contactor closing.
- To ensure the `CAN_inverter_still_alive` is set to `true` by all messages that are sent by the inverter

SMA-BYD-HVS: update battery error handling, and CAN inverter still alive

---

Software/Software.ino
Software/src/battery/BATTERIES.cpp
Software/src/battery/Battery.h
Software/src/battery/CanBattery.h
Software/src/battery/DALY-BMS.cpp
Software/src/battery/DALY-BMS.h
Software/src/battery/RS485Battery.h
Software/src/communication/rs485/comm_rs485.cpp
Software/src/inverter/AFORE-CAN.h
Software/src/inverter/BYD-CAN.h
Software/src/inverter/BYD-MODBUS.cpp
Software/src/inverter/BYD-MODBUS.h
Software/src/inverter/CanInverterProtocol.h
Software/src/inverter/FERROAMP-CAN.h
Software/src/inverter/INVERTERS.cpp
Software/src/inverter/INVERTERS.h
Software/src/inverter/InverterProtocol.h
Software/src/inverter/KOSTAL-RS485.cpp
Software/src/inverter/KOSTAL-RS485.h
Software/src/inverter/ModbusInverterProtocol.cpp
Software/src/inverter/ModbusInverterProtocol.h
Software/src/inverter/Rs485InverterProtocol.h

- Kostal RS485 inverter protocol implemented as a class
- Proper base classes for Modbus and RS485 inverters and batteries
- Modbus functionality moved to Modbus base class
- Simplify inverter class API with a single update_values()
- Yet another inverter implemented as a class to support common image build

Kostal inverter class and RS485/Modbus refactoring

---

Software/src/battery/BYD-ATTO-3-BATTERY.cpp
Software/src/battery/BYD-ATTO-3-BATTERY.h

This PR converts the BYD Atto 3 battery implementation to use the base class with duplicate double battery code eliminated.
One step closer to being able to build in all the batteries for common image.

BYD Atto 3 battery converted to use the base class

---

Software/Software.ino
Software/src/battery/BATTERIES.cpp
Software/src/battery/BMW-I3-BATTERY.cpp
Software/src/battery/BMW-I3-BATTERY.h
Software/src/battery/BYD-ATTO-3-BATTERY.cpp
Software/src/battery/BYD-ATTO-3-BATTERY.h
Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp
Software/src/battery/KIA-HYUNDAI-64-BATTERY.h
Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/battery/NISSAN-LEAF-BATTERY.h
Software/src/battery/PYLON-BATTERY.cpp
Software/src/battery/PYLON-BATTERY.h
Software/src/battery/SANTA-FE-PHEV-BATTERY.cpp
Software/src/battery/SANTA-FE-PHEV-BATTERY.h
Software/src/battery/TESLA-BATTERY.cpp
Software/src/battery/TESLA-BATTERY.h
Software/src/battery/TEST-FAKE-BATTERY.cpp
Software/src/battery/TEST-FAKE-BATTERY.h
Software/src/communication/contactorcontrol/comm_contactorcontrol.cpp
Software/src/datalayer/datalayer.h
Software/src/datalayer/datalayer_extended.h
Software/src/devboard/webserver/advanced_battery_html.cpp
Software/src/devboard/webserver/webserver.cpp

- Rename `battery2_allows_contactor_closing` to `battery2_allowed_contactor_closing` to clarify that it means that the (second) battery itself doesn't dictate contactor closing but rather the variable gives battery code that permission and the decision is made elsewhere.
- Fix usage of "allows contactor closing" and "allowed contactor closing"
- Convert rest of the batteries supporting double battery to the new class model

Contactor closing variable fix and more double batteries converter to use the base class 

---

Software/src/battery/PYLON-BATTERY.cpp

This PR makes the startup of Pylon Battery more smooth
Prevents two incorrect events from firing at startup before we have values
SOH is initialized to 100% instead of 0%
SOC is initialized to 50% instead of 0%

Pylon Battery: Add startup values for SOH and SOC

---

Software/src/inverter/BYD-MODBUS.h

This PR fixes a compiler warning
Compiler warnings are bad
During recent refactoring, this line in Modbus BYD was changed;
#define MAX_POWER 40960
Into
const int MAX_POWER = 40960;
This introduced the warning. We now fix this by replacing int with uint16_t

Improvement: Fix const datacast to avoid compiler warning

---

Software/src/inverter/FERROAMP-CAN.h

This PR makes it possible to set TOTAL_CELL_AMOUNT over 255 on the Ferroamp protocol
Previously this would result in a compilation error. Fixes #1144 
We now handle the datatype properly

Ferroamp: Bugfix, Now possible to set TOTAL_CELL_AMOUNT over 255

---

Software/src/inverter/SMA-BYD-H-CAN.cpp

This PR implements the changes done for `SMA_BYD_HVS` in #1129, for `SMA_BYD_H`
To ensure upgrades are done for all protocols
By adding the content from #1129 to the `SMA_BYD_H` inverter protocol.

SMA_BYD_H inverter: add content previously added to SMA_BYD_HVS

---

Software/Software.ino

This PR removes SOC clamping below 1percent
When using negative SOC scaling, you really want the battery to go down to 0% SOC. This was not possible due to clamping function. Fixes #1176
We now remove this restriction. It was an overcautious safety feature.

Bugfix: Discharge below 1% SOC not possible

---

Software/src/lib/pierremolinaro-acan2515/ACAN2515.cpp

This PR increases the stack size for the ACAN2515 library
Fixes a stack overflow issue for ESP32 S3, which we do not use yet, but maybe soon :) 
https://github.com/pierremolinaro/acan2515/releases/tag/2.1.5
1024 grows to 1200

Improvement: Increase stack size for ACAN2515

---

Software/src/battery/FOXESS-BATTERY.cpp
Software/src/battery/FOXESS-BATTERY.h
Software/src/battery/IMIEV-CZERO-ION-BATTERY.cpp
Software/src/battery/IMIEV-CZERO-ION-BATTERY.h

This PR converts the two remaining batteries Foxess and Imiev CZero Ion to use the common battery base class so that we can later build them all into a common image.

Convert two remaining batteries to use the base class

---

Software/src/inverter/PYLON-CAN.h

What
This PR fixes a bug that prevents a config for a high capacity battery to compile
Why
As the low-byte of the 732x Pylon frame isn't correctly cast from int -> uint8_t, the compiler won't accept values > 255.
How
Correct masking and casting of low-byte of the AH_Capacity fixes the issues.
Implemented twice for the frame 7320 and 7321

Update PYLON-CAN.h to allow high capacity >255Ah

---

Software/src/inverter/FERROAMP-CAN.h

This PR implements same change as for Pylon-Can HV
As both implementations share the same code-base, it's better to align them and fix both implementations
Copy the same code for Frame 7320/7321

Bugfix - Update Ferroamp-Can.h to allow large capacity > 255Ah

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/battery/NISSAN-LEAF-BATTERY.h
Software/src/battery/RENAULT-ZOE-GEN2-BATTERY.cpp
Software/src/battery/RENAULT-ZOE-GEN2-BATTERY.h
Software/src/datalayer/datalayer.h
Software/src/devboard/webserver/cellmonitor_html.cpp

This PR implements balancing status, initially for Nissan LEAF and ZoeGen2 batteries, and also sets the foundation on how to implement the same on other battery types
To be able to see that battery is balancing properly long term
LEAF: We now read Group6 from the Nissan LEAF BMS, which contain the balancing resistor status (aka shunt status). We map this to the datalayer, into the newly created cell_balancing_status[]
The cellmonitor view now also shows the balancing status in the graph view:

Feature: Add balancing status (LEAF & ZoeGen2)

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp

This PR fixes a bug related to Nissan LEAF total battery capacity reporting
Before this fix, only the 24kWh LEAF pack had its battery size dynamically scaled according to SOH%
We now use the same method on all LEAF battery packs.

Bugfix: Nissan LEAF, make total capacity scale according to SOH%

---

.github/workflows/compile-all-batteries.yml

This PR adds the Daly BMS to the build system
To avoid anyone breaking it during other code maintenance, like previously noticed in #1201
We add it to the Github workflow

Bugfix: Add Daly to build system

---

Software/src/battery/Battery.h

This PR fixes a build issue that was noticed locally.
Build needs to work on all environments.
A return statement was missing from get-function in Battery class.

Fix compiler warning/error

---

Software/src/battery/NISSAN-LEAF-BATTERY.h
Software/src/battery/RENAULT-ZOE-GEN1-BATTERY.cpp
Software/src/battery/RENAULT-ZOE-GEN1-BATTERY.h
Software/src/battery/RENAULT-ZOE-GEN1-HTML.h
Software/src/datalayer/datalayer_extended.h

This PR implements support for running 2x Zoe Gen1 batteries at once
User requested feature, fixes #1105
We use the same method as on Nissan LEAF doubling!

Feature: Add support for Double ZoeGen1 batteries :battery: :battery: 

---

Software/src/battery/RENAULT-ZOE-GEN2-BATTERY.cpp
Software/src/battery/RENAULT-ZOE-GEN2-BATTERY.h
Software/src/devboard/utils/types.h

This PR makes the NVROL reset usable on the Zoe PH2. Running it would cause a watchdog reset
Fixes #1235 
How does it do it? Instead of using wait_ms, we use a state machine.

Bugfix: Zoe PH2, Make NVROL reset survive WDT trigger

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp

This PR makes the check for determining if we are on 98S or 90S more reliable
Some 98S owners reported seeing 90S
We fix the broken code :see_no_evil:

Bugfix: Kia-64/40 cell count detection

---

Software/src/battery/CHADEMO-BATTERY.cpp
Software/src/battery/CHADEMO-BATTERY.h

This PR improves the Chademo start, to generate less false-positive events
Fixes #1239 
We only update voltage after car has started communicating. We also init SOC% to 50%, as on other integrations to avoid fake battery empty messages

Chademo: Improve startup to throw less events

---

Software/src/battery/BMW-I3-BATTERY.h

This PR fixes #1257. 
A redundant null-pointer access is removed.

Fix BMW I3 double battery crash

---

Software/src/battery/CMFA-EV-BATTERY.cpp
Software/src/battery/CMFA-EV-BATTERY.h

This PR implements support for running 2x [CMFA-EV](https://github.com/dalathegreat/Battery-Emulator/wiki/Battery:-Dacia-Spring-%E2%80%90-Renault-K%E2%80%90ZE) batteries at once
User requested feature
Same implementation as other double batteries

Feature: Add support for Double CMFA-EV batteries :battery: :battery: 

---

Software/src/battery/RENAULT-ZOE-GEN1-BATTERY.cpp

This PR likely fixes #1274 
The current Zoe Gen1 code incorrectly always sent to battery 1 CAN instead of the object's configured CAN interface.

Use the correct CAN interface when Zoe sends in double battery setup

---

Software/src/battery/BMW-IX-BATTERY.cpp
Software/src/battery/BMW-IX-BATTERY.h
Software/src/battery/BMW-IX-HTML.cpp
Software/src/battery/BMW-IX-HTML.h
Software/src/datalayer/datalayer_extended.h

This PR eliminates BMW IX extended data layer.
Copying data to the extended data layer structure is redundant and wasteful since the same data is already available in the battery object.
We extend the BMW IX battery class with the same getter methods that the HTML renderer can now use directly only when needed.

Eliminate BMW IX extended datalayer

---

Software/src/battery/BOLT-AMPERA-BATTERY.cpp
Software/src/battery/BOLT-AMPERA-BATTERY.h

This PR makes the Bolt/Ampera 64kWh battery usable
User requested feature on the Discord
- The values missing for a fully working implementation is:
- SOC% missing! (now estimated based on voltage)
- Capacity (kWh) (now estimated)
- Charge max power (now estimated)
- Discharge max power (now estimated)
- SOH% (now hardcoded to 99%)

Feature: Bolt-Ampera: Add Estimation methods for missing values

---

Software/src/battery/MEB-BATTERY.cpp

This PR fixes an issue with MEB batteries opening contactors after 49 days of operation
Bugs are bad. Emulator should be able to continue operation nonstop.
The bug is related to millis() rollover (which happens approximately every 49.7 days) in the first timing comparison. Here's the issue:
`if (currentMillis > last_can_msg_timestamp + 500)`
This comparison is unsafe when millis() rolls over because of how unsigned arithmetic works. When last_can_msg_timestamp is close to the maximum value (ULONG_MAX), adding 500 to it will cause an overflow, making the comparison behave incorrectly.
The safer way is to use:
`if (currentMillis - last_can_msg_timestamp > 500)`

MEB: Fixed rollover millis bug

---

Software/src/inverter/Rs485InverterProtocol.h

This fixes Kostal RS485 inverter communication.
RS485 inverter object needs to be registered as a receiver for the communication to work.

Fix RS485 inverters by proper registration of a receiver

---

Software/src/battery/SONO-BATTERY.cpp

This PR fixes a compiler warning on Sono
Not nice to have to see compiler warnings. It was an actual issue.
2025 does not fit in an u8, but 25 does :)

Fix compiler warning for overflow on Sono

---

Software/Software.ino
Software/src/devboard/utils/events.cpp
Software/src/devboard/utils/events.h
Software/src/devboard/webserver/events_html.cpp

This PR fixes #1326 
When reporting event timestamps, backend incorrectly used the current tick rollover value instead of the one stored for the event itself. By using the event's rollover count, we get correct dates even after rollover(s).

Fix display of event dates

---

Software/Software.ino

Ignore the specific float value 53.3c (hex value 0x42555555) that temperatureRead often returns.
With a ESP32 lilygo at 78c, the temperature keeps bouncing between 53.3c and 78c - the lower value is incorrect. Ignoring it results in a smoothly changing temperature.
Hopefully this is not device specific, but is a common issue with all ESP32s (https://github.com/esphome/issues/issues/6543 suggests that it is).

Fix: Ignore erroneous 53.3c CPU temperature value that ESP32 often returns

---

Software/src/battery/MEB-HTML.h

This PR makes the temperature value shown in the "More Battery Info" page for MEB make more sense
Before this PR, having the Init/error state would show temperature as 87.0 and 87.5*C, which confuses users
We now show the text Init / Error incase the temperature measurement fails

MEB: Add Init/Error display for temperatre to more battery info page

---

Software/src/battery/MG-HS-PHEV-BATTERY.cpp
Software/src/battery/MG-HS-PHEV-BATTERY.h

This PR improves MG HS PHEV battery integration:
- Uses CAN1 broadcast messages for SoC, voltages, current and temperatures, rather than relying on OBD
- Implements optional voltage-based SoC scaling to allow the (NMC) cells to be charged over 4.1V/cell.
- Tidies various things up.
- It uses update_values as a 1Hz tick (is this acceptable?)
- It will only allow voltage-based SoC scaling if the voltage reading is less than 10s old, to avoid a being stuck on a stale voltage due to a partial CAN connection failure.

Preliminary changes for better MG HS PHEV integration

---

Software/src/devboard/webserver/webserver.cpp

This PR fixes a crash when saving settings.
A lambda function that saves string settings incorrectly captured arguments by ref instead of value.

Fix crash when saving settings

---

Software/src/battery/KIA-E-GMP-HTML.cpp

A recent KIA-E-GMP-HTML PR merge had an `include.h` #include, removed.

Fix KIA-E-GMP-HTML imports

---

Software/src/battery/BATTERIES.cpp
Software/src/battery/MG-HS-PHEV-BATTERY.cpp
Software/src/battery/MG-HS-PHEV-BATTERY.h

MgHsPhev was missing from BATTERIES.cpp, added.
Also a rogue #ifndef in MG-HS-PHEV-BATTERY.cpp stopped it building properly, removed.

Tidy up MG-HS-PHEV include/ifdefs and add to BATTERIES.cpp

---

Software/src/devboard/wifi/wifi.cpp

This PR fixes Wifi by making sure the module uses the compile-time settings.
We're still supporting compile-time configuration.

Fix WiFi to use settings

---

Software/src/devboard/hal/hal.h
Software/src/devboard/utils/logging.h
Software/src/devboard/wifi/wifi.cpp

This PR fixes a bug that prevented startup on Stark HW and a Wifi-reconnection issue.
Both issues are critical to fix.
GPIO allocation was fixed to handle the Stark case with duplicate NC-pin-values properly.
WiFi reconnection logic did not correctly handle the case when ESP WiFi stack returns IDLE state right after connected.

Stark and Wifi fixes

---

Software/src/communication/contactorcontrol/comm_contactorcontrol.cpp
Software/src/communication/nvm/comm_nvm.cpp
Software/src/datalayer/datalayer.h
Software/src/devboard/webserver/settings_html.cpp
Software/src/devboard/webserver/webserver.cpp

This PR implements user configurable BMS reset off duration
Some BMS does not require a long cooldown when the reset occurs. Another usecase for setting a short off duration is frequency control, when user might require battery to be online as much as possible in order to not miss any frequency stabilization requests from the grid provider
Value is now configurable in Webserver. 1-59 seconds. Default 30s.

Feature: Add user configurable BMS reset off time

---

Software/src/datalayer/datalayer_extended.h

This PR corrects the datatype for current value in More Battery Info
User reported bug on the Discord
We now use int16_t instead of uint16_t

Volvo SPA: Correct datatype for current value in More Battery Info

---

Software/src/battery/ECMP-BATTERY.cpp
Software/src/battery/ECMP-BATTERY.h
Software/src/battery/ECMP-HTML.h
Software/src/datalayer/datalayer_extended.h
Software/src/devboard/utils/events.cpp
Software/src/devboard/utils/events.h

This PR implements SOH candidate and contactor opening event for the Stellantis ECMP integration
Requested features on Discorod
We now fire an event (EVENT_CONTACTOR_OPEN) if contactor status becomes invalid. This lets user know that something is wrong, Warning event becomes active
We also add SOH% for cell#1 to the More Battery Info.  Scaling for this value still unknown

Stellantis: Add SOH candidate and contactor opening event

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp

Contactor closing allowed once the inverter is ready.
Some inverters doesn't like, if there is voltage at HV line during startup (eg. Kostal)
Added a check for the inverter_allows_contactor_closing flag before sending certain CAN frames.

Kia/Hyundai 40/64: Respect inverter_allows_contactor_closing on startup

---

Software/src/inverter/GROWATT-WIT-CAN.cpp
Software/src/inverter/GROWATT-WIT-CAN.h
Software/src/inverter/INVERTERS.cpp
Software/src/inverter/INVERTERS.h
Software/src/inverter/InverterProtocol.h

This PR implements basic support for [Growatt Wit inverters](https://github.com/dalathegreat/Battery-Emulator/wiki/Inverter:-Growatt-WIT). Paving the way for 100kW inverters for the Battery-Emulator
User requested feature on the Discord server
TODO before testing. All CAN .ID definitions need to be set correctly. I could not figure out how to do this yet. See the code for TODOs

New Inverter :zap: Add initial support for Growatt Wit CAN

---

Software/src/communication/contactorcontrol/comm_contactorcontrol.cpp

This PR fixes #1395 so that the double battery contactor control can be configured at compile-time (as well as at run-time).
The def CONTACTOR_CONTROL_DOUBLE_BATTERY is now only used to switch the setting on.

Fix double battery contactor control settings

---

Software/src/battery/VOLVO-SPA-BATTERY.cpp
Software/src/battery/VOLVO-SPA-BATTERY.h

This PR makes the Volvo SPA integration more stable and less likely to error out
Bug reported on the Discord server. Volvo integration can incorrectly go into faulted state while starting up
- We init cellvoltages to 3700mV instead of 37000mV to avoid code going right into FAULTED state
- We now only read cellvoltages if the value is available, and stop writing them to 0mV in case of value not available
- We now only read total pack voltage if the value is available, and stop writing the value to 0V in case of value not available

Volvo SPA: Improve robustness of reading of values

---

Software/USER_SETTINGS.h
Software/src/inverter/INVERTERS.cpp
Software/src/inverter/INVERTERS.h
Software/src/inverter/InverterProtocol.h
Software/src/inverter/SOL-ARK-LV-CAN.cpp
Software/src/inverter/SOL-ARK-LV-CAN.h

This PR adds a new CAN protocol, the [Sol-Ark LV CAN protocol](https://github.com/dalathegreat/Battery-Emulator/wiki/Inverter:-Sol%E2%80%90Ark-LV)
User requested functionality
Added to Wiki as supported inverter, testers wanted

New inverter protocol :zap: Sol-Ark LV CAN

---

Software/src/battery/RANGE-ROVER-PHEV-BATTERY.h

This PR adds voltage limits to 
Range Rover Sport (L494) [2013–2022] integration
Safer operation
Max voltage taken from log from CCS charging session

Improvement: Add voltage limits to RangeRoverPHEV

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp
Software/src/battery/NISSAN-LEAF-BATTERY.h
Software/src/battery/NISSAN-LEAF-HTML.h
Software/src/datalayer/datalayer_extended.h

This PR simulates more of an entire 2018+ ZE1 LEAF vehicle towards the battery
There is a growing concern that 40/62kWh batteries are not balancing as they should. We speculate that we might not satisfy all CAN data needs that the ZE1 style LEAF batteries have.
We add the following messages to the periodic sending, if we detect that we are on ZE1 battery:
- LEAF_355
- LEAF_3B8 // Sending 3B8 removes U1000 and P318E DTC
- LEAF_5C5 // Sending 5C5 removes U214E DTC
- LEAF_5EC 
- LEAF_626 // Sending 625 removes U215B DTC
CAN data taken from github.com/dalathegreat/Nissan-LEAF-Battery-Upgrade

Nissan LEAF: Add more ZE1 CAN message sending

---

.github/workflows/release-assets.yml

Tweak the GitHub Release Assets action to:
- Build factory images (using esptool)
- Commit and push all the images to the adjacent BE-Web-Installer repo
The action will need a secret setting up:
`WEB_INSTALLER_PUSH_TOKEN` which is a Personal Access Token for the `BE-Web-Installer` repo, with Content privileges on that repo (so it can commit and push).
(or alternately I could look into setting up a proper GitHub Apps thing for doing that)

Add factory builds and push to web installer

---

Software/src/lib/ESP32Async-ESPAsyncWebServer/library.json
Software/src/lib/ESP32Async-ESPAsyncWebServer/library.properties
Software/src/lib/ESP32Async-ESPAsyncWebServer/src/AsyncWebHeader.cpp
Software/src/lib/ESP32Async-ESPAsyncWebServer/src/AsyncWebServerRequest.cpp
Software/src/lib/ESP32Async-ESPAsyncWebServer/src/AsyncWebServerVersion.h
Software/src/lib/ESP32Async-ESPAsyncWebServer/src/AsyncWebSocket.cpp
Software/src/lib/ESP32Async-ESPAsyncWebServer/src/AsyncWebSocket.h
Software/src/lib/ESP32Async-ESPAsyncWebServer/src/WebResponseImpl.h
Software/src/lib/ESP32Async-ESPAsyncWebServer/src/WebResponses.cpp
Software/src/lib/ESP32Async-ESPAsyncWebServer/src/literals.h

This PR updates the library [ESP32AsyncWebServer to v3.8.0](https://github.com/ESP32Async/ESPAsyncWebServer/releases/tag/v3.8.0)
Updated libraries are always nice! Especially since @kyberias provided patches to this lib recently :raised_hands: Nice work!
We update from v3.7.10 -> v3.8.0

Library :scroll: Update ESP32AsyncWebServer to v3.8.0

---

Software/src/lib/mathieucarbou-AsyncTCPSock/src/AsyncTCP.cpp

Remove the `taskYIELD()` recently added to the AsyncTCP class.
I thought that this was necessary to prevent starvation of the same-prio tasks with watchdogs, but as Kyberias points out, FreeRTOS has `configUSE_TIME_SLICING` set, and has a fair scheduling algorithm, so this can't have been a problem.
Indeed I can no longer recreate it!

Revert AsyncTCP extra taskYIELD (unnecessary)

---

Software/src/inverter/SOFAR-CAN.cpp
Software/src/inverter/SOFAR-CAN.h

This PR slows down the CAN sending for the Sofar CAN protcol, and improves the inverter response generation
User noticed issues with 100ms sending. Now most messages are 1000ms, and some triggered on demand
Patch submitted by Pazdzierz on the Discord :raised_hands:

Sofar CAN: Reduced CAN sending rate, improved inverter response

---

Software/src/devboard/safety/safety.cpp
test/safety_tests.cpp

This PR changes the CPU overheat warning message to be less sensitive
To cut down on false positive warnings. So many people report issues, even though there are no issues
Raised the CPU temperature warning from 80 to 87deg

Improvement: Update CPU temperature setpoint

---

Software/src/battery/VOLVO-SPA-HTML.h

This PR fixes a bug in the More battery Info page for Volvo SPA
Precharge was swapped with Positive Contactor
These are now inverted to correct orientation!

Volvo SPA: Swap precharge/positive state

---

Software/src/battery/BATTERIES.cpp
Software/src/battery/BATTERIES.h
Software/src/battery/TESLA-BATTERY.cpp
Software/src/battery/TESLA-BATTERY.h
Software/src/communication/nvm/comm_nvm.cpp
Software/src/devboard/webserver/settings_html.cpp
Software/src/devboard/webserver/webserver.cpp

This PR implements easily configurable gateway, HVIL and generation settings for Tesla S/3/X/Y batteries
It was not possible to use the Common Image from releases directly with Tesla packs. This PR makes it possible
Everything now easily editable via Webserver, and stored to flash!

Tesla: Configurable GTW settings via Webserver

---

Software/src/battery/RENAULT-ZOE-GEN2-BATTERY.cpp

This PR makes the secondary battery write balancing status correctly
Bug noticed on Discord by user, second battery did not show any balancing resistors
Correct memcpy

Renault Zoe2: Make secondary battery write correctly to balancing status

---

Software/Software.cpp
Software/src/lib/pierremolinaro-acan-esp32/ACAN_ESP32_Settings.h

This PR increases the TX transmit buffer for Native CAN, to avoid messages being dropped on CAN heavy integrations like the BMW i3
Dropped messages means integrations wont work
mDriverTransmitBufferSize increased from 16 -> 32, benchtest seems OK, no longer drops messages towards a Kvases Memorator

Bugfix: Increase CAN TX buffer to avoid dropping messages

---

Software/src/battery/MEB-BATTERY.cpp

This PR makes the Volkswagen MEB Still Alive on CAN check work
It has always been broken :see_no_evil: 
We now correctly set the `datalayer.battery.status.CAN_battery_still_alive = CAN_STILL_ALIVE;` only when a known MEB CAN frame arrives

MEB: Fix CAN still alive handler

---

Software/src/battery/RJXZS-BMS.cpp

This is a fix for the previous fix, which was only populating 3 cellvoltages.

Fix cellvoltages index on RJXZS population

---

Software/src/battery/KIA-HYUNDAI-HYBRID-BATTERY.cpp
Software/src/battery/MG-5-BATTERY.cpp
Software/src/battery/PYLON-BATTERY.cpp
Software/src/battery/RANGE-ROVER-PHEV-BATTERY.cpp
Software/src/battery/RENAULT-TWIZY.cpp
Software/src/battery/SIMPBMS-BATTERY.cpp
Software/src/battery/VOLVO-SPA-BATTERY.cpp
Software/src/battery/VOLVO-SPA-HYBRID-BATTERY.cpp

Several batteries were failing the CAN-still-alive tests (in future PR), by setting CAN_STILL_ALIVE on irrelevant messages. This fixes those.
Hopefully I have chosen suitable CAN message IDs - there is a risk of causing problems if the messages I've picked aren't used on some batteries...
So that CAN failures are more likely to flag up error events.

Change several batteries to only flag CAN aliveness on relevant msgs

---

test/CMakeLists.txt
test/can_log_based/canlog_safety_tests.cpp
test/utils/utils.cpp
test/utils/utils.h

As per the GTest docs, this removes underscores from test names by CamelCasing them. And removes the unnecessary parameters.
To conform better with the GTest recommendations.

Tidy up parameterised test names

---

Software/src/battery/BATTERIES.h
test/battery/still_alive_tests.cpp

Small update to previous PR, to more reliably construct all the batteries (so we don't miss future ones), and rename things.

Tweak CAN still-alive tests to more reliably construct batteries

---

Software/src/battery/MEB-BATTERY.cpp
Software/src/communication/can/comm_can.cpp
Software/src/communication/can/comm_can.h
Software/src/communication/can/obd.cpp
Software/src/communication/can/obd.h
Software/src/devboard/webserver/webserver.cpp
test/emul/can.cpp

Makes the RX0/TX1 entries in CAN logs reflect the actual interface. Multiples the enum as an int by two, so that the TX is always one higher than the RX.
The logs end up like this:
```
(494.182) RX0 172 [8] 45 60 8B 49 00 93 00 00
(494.183) RX0 173 [8] 00 00 C7 C8 0F 61 0F 59
(494.184) TX1 8A [8] 80 00 00 04 00 02 36 B0
(494.184) TX1 1F1 [8] 0E 00 00 00 00 00 00 00
(494.186) RX4 1871 [8] 01 00 01 00 00 00 00 00
(494.186) TX5 187E [8] A2 30 00 00 63 58 00 00
(494.186) TX5 187A [8] 01 50 00 00 00 00 00 00
(494.186) TX5 1872 [8] C4 0E E6 0A 3C 00 3C 00
(494.187) TX5 1873 [8] DB 0D F9 FF 58 00 51 04
(494.187) TX5 1874 [8] C1 00 AD 00 9A 10 59 0F
(494.188) TX5 1875 [8] B7 00 04 00 01 00 00 00
(494.188) TX5 1876 [8] C1 00 61 0F AD 00 59 0F
(494.188) TX5 1877 [8] 00 00 00 00 54 00 22 02 …
```

Include CAN interface number in logs (with distinct TX/RX)

---

.github/workflows/release-assets.yml

Try and fix the T-2CAN factory image build yet again - one user reports that it might actually work this time.
The 2CAN should support qio, but this switches back to dio for now. Need to test against real hardware. Also switch back to 40mhz (even though the chip should be good for 80mhz).
It also uses 16mb (the true flash size) rather than 4mb - my assumption that it would work with the smaller size may be wrong.
Will experiment again if I can get my hands on an actual S3 to test.

Switch T-2CAN back to dio, and try 16mb

---

Software/src/devboard/webserver/webserver.cpp

Mirek P found a bug where exactly-8-character WiFi passwords didn't work.
This fixes a off-by-one so these now save.

Fix validation so that 8 character WiFi passwords work

---

Software/src/battery/TESLA-BATTERY.cpp
Software/src/battery/TESLA-BATTERY.h

This PR speeds up contactor opening on Tesla.
During refactoring, we (I) accidentally moved a 50ms code block to a 1000ms evaluation period. This made contactor opening very slow (60s instead of 9s)
We fix the hardcoded ticks to suit this new evaluation period. Bonus, also add some enumerations to make code easier to read

Tesla: Make contactor opening take 9s instead of 60s

---

Software/src/inverter/SMA-BYD-H-CAN.h
Software/src/inverter/SMA-BYD-HVS-CAN.h

This PR renames the SMA protocols
To avoid users accidentally using SMA protocols when they dont mean to
"BYD Battery-Box HVS over SMA CAN" ->  SMA compatible BYD Battery-Box HVS"
"BYD over SMA CAN" -> ""SMA compatible BYD H"

Rename protocol to make it more clear it is SMA

---

Software/src/battery/RENAULT-ZOE-GEN1-BATTERY.h

This PR fixes the max voltage limits set for the Zoe1 battery
Solax does not like seeing 420V for a 96S battery
We lower the max voltage allowed for this battery type to more sane values

Bugfix: Tweak voltage limits for Zoe1

---

Software/src/devboard/webserver/settings_html.cpp
Software/src/devboard/wifi/wifi.cpp

This PR allows dash as special character in usernames/passwords entered in the webserver
User requested on Discord, this was working in older versions
"-" added at the end of the regex
Bonus: Fixed a small bug that caused Wifi AP to ignore the user set name

Bugfix: Allow dash as special character in usernames/passwords

---

Software/src/devboard/hal/hw_stark.h

This PR makes the BMS power default ON
Very useful to have, and not require BMS reset feature in order to toggle this pin ON. Fixes #1588 
By default it is now set ON at startup

Stark CMR: Make BMS power on by default

---

Software/src/devboard/hal/hw_lilygo2can.h
platformio.ini

Note: This is in slight conflict with https://github.com/dalathegreat/Battery-Emulator/pull/1589
This assigns the pin connections on the LilyGo T-2CAN to try and make the best use of the GPIOs. It allows for:
- RS485 on the first SH-1.0mm connector, with TX/RX flipped so bootloader chatter isn't sent down the bus
- GPIO on the second SH-1.0mm, currently BMW WUP1/2 as per the other PR, but I propose this is made configurable (eg, for BMS_RESET/ESTOP/LED for people not using BMW batteries).
- SPI connections for a MCP2518, with the pins in the same order as the common AliExpress modules
- BMS_RESET/POS/NEG/PRE/BAT2 contactor connections together in a row
- LED near the power pins for easy wiring of an indicator
- HV precharge pins next to each other
ASCII-art diagram:
```
43:RS485_RX …
```

Proposed pin assignments for LilyGo T-2CAN (suggestions welcome)

---

Software/src/battery/TESLA-BATTERY.cpp
Software/src/battery/TESLA-BATTERY.h

This PR optimizes the CAN handler inside the Tesla battery section, and attempts to fix the WELDED issue seen on 9.x
Suspected Tesla issues in 9.X , causing WELDED + found some possible optimizations while looking at code
- Re-using of unified mux counter to save memory and less instructions
- Replaced Switch statement with else-if (and the most likely always being the first if check)
- Add missing break to 20A message

Tesla: Optimize CAN handler for faster execution + WELDED fix

---

Software/src/communication/precharge_control/precharge_control.cpp

This PR moves the max precharge timeout check to always be evaluated
Avoid odd scenario where precharge would fail, but not turn off (110V issue)
Now we always check the timeout while we are in active precharge state

Precharge: Move evaluation of max precharge time to always be checked

---

Software/src/communication/nvm/comm_nvm.cpp

This PR makes it possible to use MINSOC as 0% when using Scaled SOC
User reported issue. Fixes #1542 
We now allow values set to 0 to be used at boot

Bugfix: Make it possible to save 0 as minpercentage

---

Software/src/inverter/FERROAMP-CAN.cpp
Software/src/inverter/FERROAMP-CAN.h

This PR fixes the capacity writing for Ferroamp protocol
User reported feature broken on Discord
The reported values entered in the Webserver is now mapped periodically to the 7321 message
Bonus: All Send0 messages removed from the Ferroamp protocol, to save system resources.

Bugfix: Make capacity writing work for Ferroamp

---

Software/src/battery/BMW-IX-BATTERY.cpp
Software/src/battery/BMW-IX-BATTERY.h

This PR makes it possible to charge/discharge 78S iX1 batteries properly
User reported bug on Discord, not possible to charge battery due to 0kW allowed even though it should allow
We now define limits separately for 78S, 96S and 108S packs. This PR makes all iX integrations more robust

BMW iX: Fix incorrectly applied min/max voltages
