Software/BYD-MODBUS-2-LEAF-CAN.ino

Fix array length

---

.gitignore
Software/BYD-CAN.cpp
Software/INVERTERS.h
Software/NISSAN-LEAF-BATTERY.cpp
Software/NISSAN-LEAF-BATTERY.h
Software/RENAULT-ZOE-BATTERY.cpp
Software/RENAULT-ZOE-BATTERY.h
Software/SOLAX-CAN.cpp
Software/SOLAX-CAN.h
Software/Software.ino
Software/TESLA-MODEL-3-BATTERY.cpp
Software/TESLA-MODEL-3-BATTERY.h

- CAN handling rewritten for easier adding of additional Inverters/Batteries
- Added initial support for Solax inverters

Solax support

---

Software/TESLA-MODEL-3-BATTERY.cpp

- SOC now uses actual value instead of calculated
- Charge/Discharge power modbus registers now set
- Temperature decimals added

Tesla Model 3 register fix

---

README.md
Software/INVERTERS.h
Software/PYLON-CAN.cpp
Software/PYLON-CAN.h
Software/Software.ino

This pull request adds initial support for the pylontech defacto standard. Can be used to further develop support for inverters that support this type of standard.

Pylontech support

---

Software/NISSAN-LEAF-BATTERY.cpp

This branch adds cell voltage monitoring to Nissan LEAF batteries. It will now poll the BMS for the 96 individual cell voltages, and output min/max/dev values over serial. It will also act on cell over/under voltages, and put the inverter in a faulted state incase one cell drifts too far away (4250mV Over, 2700mV under, both scenarios result in stopped inverter and red LED state 🔴 ).

Add cell voltage monitoring for LEAF

---

Software/BATTERIES.h
Software/CHADEMO-BATTERY.cpp
Software/CHADEMO-BATTERY.h
Software/Software.ino

Add skeleton for Chademo support

Chademo v2x

---

Software/BATTERIES.h
Software/IMIEV-CZERO-ION-BATTERY.cpp
Software/IMIEV-CZERO-ION-BATTERY.h
Software/Software.ino

This PR adds the initial support for I-Miev / Czero/ Ion batteries. Do note that this is very work in progress, and will need lots of refinement. But the skeleton for it is there :)

Add initial imiev support

---

Software/BYD-CAN.cpp

Fixes reported from issue #28 
- Charge/Discharge swapped in 0x110
- Added inverter messages to BYD CAN

Goodwe feedback

---

Software/BATTERIES.h
Software/KIA-HYUNDAI-64-BATTERY.cpp
Software/KIA-HYUNDAI-64-BATTERY.h
Software/Software.ino

Adds the files needed to start working on a Kia/Hyundai 64kWh integration

Add skeleton for KiaHyundai 64kWh

---

Software/BATTERIES.h
Software/BMW-I3-BATTERY.cpp
Software/BMW-I3-BATTERY.h
Software/Software.ino

Add initial support for BMW i3 batteries

Bmw i3 support

---

Software/BMW-I3-BATTERY.cpp
Software/BMW-I3-BATTERY.h
Software/BYD-CAN.h
Software/CHADEMO-BATTERY.cpp
Software/CHADEMO-BATTERY.h
Software/IMIEV-CZERO-ION-BATTERY.cpp
Software/IMIEV-CZERO-ION-BATTERY.h
Software/KIA-HYUNDAI-64-BATTERY.cpp
Software/KIA-HYUNDAI-64-BATTERY.h
Software/NISSAN-LEAF-BATTERY.cpp
Software/NISSAN-LEAF-BATTERY.h
Software/PYLON-CAN.h
Software/RENAULT-ZOE-BATTERY.cpp
Software/RENAULT-ZOE-BATTERY.h
Software/SOLAX-CAN.cpp
Software/SOLAX-CAN.h
Software/Software.ino
Software/TESLA-MODEL-3-BATTERY.cpp
Software/TESLA-MODEL-3-BATTERY.h
Software/USER_SETTINGS.h
Software/config.h

This rewrite creates a `USER_SETTINGS.h` file that contains all the options and settings. This makes it faster to update to a newer version, without having to re-make all the customizations that you've previously made. It also makes it safer to use the software.
This PR also fixes a bug, SOLAX_CAN could not be compiled without DUAL_CAN option enabled. This is now fixed.
This PR also fixes some Tesla model 3 bugs, contactor not closing and bms_state getting stuck

Rewrite with central user settings file

---

Software/TESLA-MODEL-3-BATTERY.cpp

I planned to make more improvements and also re-factor / clean up, but don't have the time right now.

Improvements to debug output for Tesla batteries.

---

Software/NISSAN-LEAF-BATTERY.cpp
Software/NISSAN-LEAF-BATTERY.h
Software/Software.ino

- Raise baud rate from 9600 -> 115200
- Improve convert2unsignedint16 so it actually handles signed values properly
- USB printing made more user friendly with correct scalings
- Fixed an issue where the Charging/Discharging/Idle field would show wrong status

Leaf print refactor

---

Software/IMIEV-CZERO-ION-BATTERY.cpp
Software/IMIEV-CZERO-ION-BATTERY.h

This PR fixes the following for iMIEV batteries:
- SOC% now scaled properly (and filtered if unreasonable)
- Cell max/min voltage added
- Cell max/min temperature added
- Remaining capacity now scaled properly
- Added max charge/discharge limit estimation
- Added additional debug prints

Imiev fixes

---

Software/INVERTERS.h
Software/MODBUS-BYD.cpp
Software/MODBUS-BYD.h
Software/MODBUS-LUNA2000.cpp
Software/MODBUS-LUNA2000.h
Software/Software.ino
Software/USER_SETTINGS.h

This PR
* Separates Modbus RTU handling from main .ino file into separate files
* MODBUS-BYD .cpp / .h files now contain the HVM Modbus registers
* MODBUS_LUNA2000 .cpp / .h files now contain the Luna2000 modbus registers (still WIP)

Modbus luna2000

---

Software/Software.ino

This pull request refactors the `Software.ino` file.
It does this by:
- Reordering the functions at the bottom of the file to reflect the order in `main()`
- Splitting `handle_can()` into `receive_can()` and `send_can()`
- Adding comment sections "Input", "Process", "Output" to the main loop
- Changing the order of declarations in the preamble to match the order in `setup()`
- Adding initialization functions
- Updating comments (while we are at it)
Please find the individual commits to see all consequent changes.
This refactoring is done to improve the readability of the code. It should be particularly helpful for someone that is not familiar yet with this project, but also existing users may find it helpful.

Refactor Software.ino

---

Software/Software.ino

Sofar not get new data from battery, because not call function "update_values_can_sofar()". I add it.

Fix update data to sofar

---

Software/src/devboard/webserver/webserver.h

Due to the memory optimizations made in #126 , the webserver was broken. This pr fixes the compilation error!

Fix compilation error

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp
Software/src/devboard/webserver/webserver.cpp
Software/src/devboard/webserver/webserver.h

- Change of timing when Inverter volts are sent
- Change timing of when midvalue of frame 0x200 is sent
- Webserver compile error fix

Minor updates of timing

---

Software/src/battery/TESLA-MODEL-3-BATTERY.cpp

This PR adds SOH% value for Tesla packs. It also adds a sanity check for the kWh when full value reported by battery is invalid.
Previously this SOH% value was hardcoded as 99.00%. Not nice!
We now compare the when new kWh value with the current fully charged kWh value, and calculate a SOH% based on this.

Tesla: Add SOH% value and kWh safety check

---

Software/USER_SETTINGS.cpp
Software/USER_SETTINGS.h
Software/src/devboard/webserver/README.md
Software/src/devboard/webserver/webserver.cpp
Software/src/devboard/webserver/webserver.h

This PR supercharges the webserver with some additional features
- Webserver now shows version number
- Wifi signal strength added (dBm value)
- Reboot button added
- Settings page added
- All USER_SETTINGS can now be edited on the fly! 
Also:
- Fixed a bug causing AP to never turn on
- USER_SETTINGS .h and .cpp file refactored to account for live changes
By popular user request, new features are desired to the Webserver
The Webserver.cpp file has been refactored heavily

Feature: Advanced webserver

---

Software/src/devboard/webserver/events_html.cpp
Software/src/devboard/webserver/index_html.cpp

This PR improves how the events view is displayed. It also fixes some bugs related to the timestamps
To get a better overview of any special events / fault codes in the system
Before this PR:
After this PR:

Bugfix: Beautify eventsview

---

Software/src/devboard/mqtt/mqtt.cpp

Fix SOC Real in mqtt

---

.github/workflows/compile-all-batteries.yml
.github/workflows/compile-all-combinations.yml
Software/USER_SETTINGS.h
Software/src/battery/BATTERIES.h
Software/src/battery/VOLVO-SPA-BATTERY.cpp
Software/src/battery/VOLVO-SPA-BATTERY.h
Software/src/devboard/webserver/webserver.cpp

This PR adds support for two new battery packs! Massive thanks to niclashedlund over on the Discord server for this massive feat! 🙌 
We now have support for these batteries:
- Volvo XC40 78kWh
- Polestar 2 78kWh
See the Wiki page for more info on how to use these batteries

New Battery: Volvo XC40 / Polestar 2 78kWh ✅ 

---

Software/Software.ino
Software/src/battery/IMIEV-CZERO-ION-BATTERY.cpp

This PR adds cellvoltages for triplet batteries, and fixes temperature scaling
Thanks to Ruudi S over on the Discord server for noticing that this did not work properly!

Triplet battery: Cellvoltages and temperature fix

---

Software/src/lib/ayushsharma82-ElegantOTA/.github/workflows/ci.yml
Software/src/lib/ayushsharma82-ElegantOTA/README.md
Software/src/lib/ayushsharma82-ElegantOTA/library.json
Software/src/lib/ayushsharma82-ElegantOTA/library.properties
Software/src/lib/ayushsharma82-ElegantOTA/platformio_upload.py
Software/src/lib/ayushsharma82-ElegantOTA/src/ElegantOTA.h
Software/src/lib/bblanchon-ArduinoJson/ArduinoJson.h
Software/src/lib/eModbus-eModbus/CoilData.h
Software/src/lib/eModbus-eModbus/ModbusBridgeTemp.h
Software/src/lib/eModbus-eModbus/ModbusClientRTU.cpp
Software/src/lib/eModbus-eModbus/ModbusClientRTU.h
Software/src/lib/eModbus-eModbus/ModbusServer.cpp
Software/src/lib/eModbus-eModbus/ModbusServer.h
Software/src/lib/eModbus-eModbus/ModbusServerRTU.cpp
Software/src/lib/eModbus-eModbus/ModbusServerRTU.h
Software/src/lib/eModbus-eModbus/ModbusTypeDefs.cpp
Software/src/lib/eModbus-eModbus/ModbusTypeDefs.h
Software/src/lib/eModbus-eModbus/RTUutils.cpp
Software/src/lib/eModbus-eModbus/options.h

This PR updates the libraries used by the Battery-Emulator project
To fix bugs/issues that were present in the libraries
- Update eModbus to v1.7.1stable
- Update ArduinoJSON to v7.0.4
- Update ElegantOTA to v3.1.1

Bugfix: Update libraries (2024/March)

---

Software/src/battery/KIA-E-GMP-BATTERY.h

This PR makes the EGMP battery compile again
The change done in #247 broke it
Changed the datatypes to match the rest of the software

Bugfix: Update header to get EGMP to compile

---

Software/src/devboard/webserver/cellmonitor_html.cpp
Software/src/devboard/webserver/events_html.cpp
Software/src/devboard/webserver/settings_html.cpp

Fixing a mistake I made in another PR, causing events, cellmonitor and settings to be blank white page

Bugfix: Fix white blank webpage bug

---

Software/src/inverter/BYD-MODBUS.cpp

Noticed during testing of EVENT_MODBUS_INVERTER_MISSING that false positives could be triggered. This PR fixes that
We use an event history with three samples. This makes it less likely that a false positive is sampled. Keep in mind the 401 register is written every 60 seconds, so checking it only once every 60s could cause issues. We now require the value to be stale for 3 minutes (checked once every 60s), until we raise an event. This is a much more robust solution

BYD Modbus: Tweak trigger logic for missing inverter event

---

.github/workflows/compile-all-batteries.yml
.github/workflows/compile-all-combinations.yml
.github/workflows/compile-all-inverters.yml
Software/Software.ino
Software/src/devboard/utils/led_handler.cpp
Software/src/devboard/utils/led_handler.h
Software/src/devboard/webserver/webserver.cpp
Software/src/lib/smaresca-SimpleISA/SimpleISA.h

- This PR adds the "Warning: All" flag to the build system. It also fixes some compiler warnings that appears when you select this option in Arduino IDE
- This PR also forces the build system to use v3.0.0 of the ESP32 board manager
- Finally, this PR also fixes some warnings seen when compiling the code
To raise code quality, and prevent undesired behaviour of the code
We apply the `-Wall` flag on the workflows.

Improvement: Compiler warnings

---

.github/workflows/compile-all-batteries.yml
.github/workflows/compile-all-combinations.yml
.github/workflows/compile-all-inverters.yml

This PR fixes the build system, that was broken in another PR

Bugfix: Repair build system

---

Software/src/battery/KIA-E-GMP-BATTERY.cpp

This PR fixes the direction of current reported by the EGMP battery
To get the battery reported data in line with reality
Thanks to @JorgenSeemann for reporting this in #342

Bugfix: Egmp current value

---

Software/Software.ino
platformio.ini

Use unsupported but working ESP32 version in PlatformIO

---

Software/src/battery/PYLON-BATTERY.cpp

This PR fixes current,discharge and capacity scaling for [Pylon batteries](https://github.com/dalathegreat/Battery-Emulator/wiki/Pylon-Battery)
The values were scaled incorrectly, preventing this type of battery from being used
Thanks to testing done by members on the Discord server, we noticed this issue 🙌

Bugfix: PYLON Battery parameter scaling

---

Software/USER_SETTINGS.h
Software/src/battery/BATTERIES.h
Software/src/battery/JAGUAR-IPACE-BATTERY.cpp
Software/src/battery/JAGUAR-IPACE-BATTERY.h

This is a draft for now and contains the basic skeleton.

Initial iPace battery support

---

.github/workflows/compile-all-batteries.yml
Software/src/battery/JAGUAR-IPACE-BATTERY.cpp
Software/src/devboard/webserver/webserver.cpp

Minor tweaks to I-PACE handling:
- Add known battery frames to switch case
- Make battery frames signal still alive
- Add voltage min/max and cellvoltage count
- Add Jaguar to build system
Note, Jaguar support still WIP

Improvement: Add jaguar to build system

---

Software/src/battery/JAGUAR-IPACE-BATTERY.cpp
Software/src/devboard/utils/events.cpp
Software/src/devboard/utils/events.h

This PR adds more CAN mappings for Jaguar I-Pace
- HVIL detection (with Event!)
- Isolation loss detection (with Event!)
- Battery Voltage mapping
- Power calculation
NOTE: Jaguar support still WIP

Jaguar I-PACE: Add more CAN mappings and events

---

Software/src/battery/IMIEV-CZERO-ION-BATTERY.cpp

This PR adds cellvoltage safety checking for the triplets. It also improves reading of SOC
Safer operation of battery
Thanks to Ruudi S on the Discord for testing this!

Triplets: Add cellvoltage safeties and improved SOC handling

---

Software/src/inverter/PYLON-CAN.cpp

- Add Sleep status to open contactors in inverter at Fault
- Change status-value from 0x 11, 12, 13 to 01, 02, 03 to not call for extra chargning.

Update Status-bits PYLON-CAN.cpp

---

Software/src/battery/SANTA-FE-PHEV-BATTERY.cpp
Software/src/devboard/webserver/webserver.cpp

This PR makes the Santa FE battery work
Massive thanks to GoSmart over on the Discord server, for testing and providing CAN logs! :raised_hands:

Santa Fe PHEV: Improve battery mappings

---

Software/src/inverter/PYLON-CAN.cpp

This PR makes the pylon protocol more configurable
To get the code more compatible with more inverters, and to get more accurate data
Additional configurable parameters in the pylon.cpp file

Feature: Make pylon more configurable

---

Software/Software.ino
Software/USER_SETTINGS.h
Software/src/devboard/hal/hw_stark.h
Software/src/devboard/webserver/settings_html.cpp
Software/src/include.h

This PR makes the Stark CMR board function with the Battery-Emulator
For more information on this board visit the project discord or contact johan@redispose.se

Feature: Stark CMR introduction

---

Software/src/battery/BMW-I3-BATTERY.cpp

This PR fixes the bug in #418 
Some i3 packs have constant yellow light on due to failing CRC
We skip CRC entirely incase it fails on the first try

BMW i3: Add skip for CRC incase it fails initially

---

Software/Software.ino
Software/USER_SETTINGS.h
Software/src/devboard/hal/hw_lilygo.h
Software/src/inverter/BYD-SMA.cpp
Software/src/inverter/BYD-SMA.h
Software/src/inverter/INVERTERS.h

This PR adds support for BYD batteries, via SMA compatible CAN interface
To add support for SMA Sunny Boy Storage inverters

New protocol: BYD-SMA

---

.github/workflows/compile-all-combinations.yml
.github/workflows/compile-all-inverters.yml
Software/src/devboard/hal/hw_stark.h
Software/src/inverter/BYD-SMA.cpp
Software/src/inverter/SMA-CAN.cpp

This PR fixes the following
- Makes SMA protocols work with Stark Hardware
- Makes the SMA_CAN protocol pairing work, same style as BYD_SMA
- Adds Github workflows to the SMA-CAN procol, to make sure nobody breaks it in a future PR

Bugfix: SMA Cleanup

---

Software/src/battery/JAGUAR-IPACE-BATTERY.cpp

Rework the existing transmit code to instead send proper keep-alive messages.
This is a replacement for https://github.com/dalathegreat/Battery-Emulator/pull/434

iPace: Send proper keep alive message

---

.gitignore

Ignore built binary files

---

Software/Software.ino

bugfix. missing code commit from PR#457

Bug fix for PR#457 (disable  send CAN when pause for update)

---

Software/src/devboard/utils/events.cpp
Software/src/devboard/utils/events.h
Software/src/devboard/webserver/events_html.cpp
Software/src/devboard/webserver/webserver.cpp

This PR implements manual event clearing
Bonus fixes:
- Pause button centered properly
- Pylonbattery text on webserver added
User requested feature
A button is added to the Events webpage. When clicked it asks the user if they want to clear all errors.

Feature: Clear events via webpage

---

Software/src/devboard/webserver/webserver.cpp

Added a confirmation alert for the "Pause Charge/Discharge" functionality to prevent accidental activation.
A user reported frequently pressing the button by mistake, which caused unintended disruptions. Adding a confirmation step ensures users are aware before pausing power flow.
Implemented a confirmation dialog that prompts the user before setting the maximum charge and discharge values to zero when the "Pause Charge/Discharge" button is pressed.

Added confirmation alert for "Pause Charge/Discharge" functionality

---

Software/src/inverter/SOLAX-CAN.cpp

This PR fixes #385 
To have users able to configure max allowed Amp value in webserver
We actually look at the configured value now

Bugfix: Solax respect user set limits

---

Software/src/devboard/webserver/webserver.cpp

This PR implements a way to quickly see delta between cell min and cell max mV on webserver
Great user suggested feature from Discord
We now show the diff on the webserver:
Incase it goes into large deviation, we also paint it red:

Microfeature: Add cellmV diff to webserver

---

Software/src/battery/BYD-ATTO-3-BATTERY.cpp
Software/src/battery/BYD-ATTO-3-BATTERY.h

This PR adds support for running two Atto 3 batteries at the same time. Testing needed
User requested feature

Feature: Double Atto 3 battery support

---

README.md

This PR implements, Arduino installation and setup steps, the ones listed were outdated.  Added support for Ubuntu Linux in a few lines.
These were not accurate.
Words.

Development Environment Setup Documentation Improved

---

Software/src/inverter/BYD-CAN.cpp

This PR adds capacity handling for BYD CAN. Previously we incorrectly wrote charge limits to the field that should contain capacity.
We fix this in order to satisfy the inverter, and make the display on inverters show correct info
Content in 0x150 is now formatted correctly

Bugfix: Add capacity writing to BYD CAN

---

Software/src/inverter/BYD-CAN.cpp

This PR adds more inverter content discovered in https://github.com/dalathegreat/Battery-Emulator/issues/614
Inverter values can be used for future development
More data is extracted from 0x091 message

Feature: Add more BYD inverter mappings

---

Software/src/battery/SANTA-FE-PHEV-BATTERY.cpp

This PR implements double battery support for Santa Fe PHEV batteries
User requested feature on the Discord!
Fixes #595

Feature: Add double battery support for Santa Fe PHEV

---

Software/src/battery/NISSAN-LEAF-BATTERY.cpp

This PR fixes the issue reported in #705 
So we can read cellvoltages again
At the same time, we speedup the handling. Instead of waiting 100seconds before starting to poll, we now wait 20 seconds.

Regression: LEAF, Speedup polling, fix requests for cellvoltage

---

Software/src/battery/VOLVO-SPA-BATTERY.cpp
Software/src/datalayer/datalayer_extended.h
Software/src/devboard/webserver/advanced_battery_html.cpp
Software/src/devboard/webserver/webserver.cpp

This PR implements contactor closing for Volvo SPA platform (Volvo EX40 / Polestar 2)
Easier operation of the SPA platform
Massive thanks to niclashedlund and GoSmart over on the Discord server for this development :raised_hands: 
The "More Battery Info" page has been equipped with more information about the SPA battery. There is also options to Erase DTCs and to Read DTC, and a way to restart the BECM module.

Volvo/Polestar: Add contactor closing and DTC reset

---

Software/src/lib/bblanchon-ArduinoJson/ArduinoJson.h

This PR updates the ArduinoJson library to [v7.3.0](https://github.com/bblanchon/ArduinoJson/releases/tag/v7.3.0). The currently used version is 7.0.4
To benefit from the [safer copy policies](https://arduinojson.org/news/2024/12/29/arduinojson-7-3/)

Library: Update ArduinoJson to v7.3.0

---

.github/workflows/compile-all-combinations-part1-batteries-A-to-M.yml
.github/workflows/compile-all-inverters.yml
Software/USER_SETTINGS.h
Software/src/inverter/GROWATT-HV-CAN.cpp
Software/src/inverter/GROWATT-HV-CAN.h
Software/src/inverter/GROWATT-LV-CAN.cpp
Software/src/inverter/INVERTERS.h

This PR adds support for "Growatt BMS CAN-Bus-protocol High Voltage V1.10 2023-11-06"
To increase amount of inverters supported by the Battery-Emulator
This new protocol is not tested, lots of TODOs in the code related to serial numbers etc. Testers welcome!

New feature: Growatt HV protocol :zap: 

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp
Software/src/datalayer/datalayer_extended.h
Software/src/devboard/safety/safety.cpp
Software/src/devboard/webserver/advanced_battery_html.cpp

This PR implements support for running 2x Kia-Hyundai  64/40kWh batteries at the same time :battery: :battery: 
Feature requested by Discord member
Same way as other DoubleBattery implementations

Feature: Add support for Double Kia-Hyundai 64/40kWh batteries

---

Software/src/inverter/FERROAMP-CAN.cpp

This PR implements rescaling of non LFP packs, into LFP cellvoltage ranges.
To fix #887 , this avoids raising suspicion of LFP overvoltage when using NCM batteries. 
Linear interpolation to remap the value from the range [2500-4200] to [2500-3400]

Ferroamp: Add linear interpolation to fake LFP voltage range

---

Software/src/battery/DALY-BMS.cpp
Software/src/inverter/PYLON-LV-CAN.cpp

I did some more testing with by BMS & Inverter and managed to successfully charge and discharge my battery.
I did however find some remaining incorrect value conversions which are fixed with this PR
Make DALY and PylonLV work.
Side note I also added more text and pictures to the [Daly DIY LV Battery Wiki page](https://github.com/dalathegreat/Battery-Emulator/wiki/Battery:-Daly-SmartBMS).

(Hopfully) Final DALY BMS & Pylon LV fixes

---

.github/workflows/compile-all-batteries.yml
.github/workflows/compile-all-combinations-part2-batteries-N-to-Z.yml
Software/USER_SETTINGS.h
Software/src/battery/BATTERIES.h
Software/src/battery/ORION-BMS.cpp
Software/src/battery/ORION-BMS.h

This PR implements support for DIY battery builds with [Orion BMS](https://github.com/dalathegreat/Battery-Emulator/wiki/Battery:-Orion-BMS)
User requested feature on Discord!
Orion BMS support via Victron protocol, see the Orion BMS page for more info on how to setup the build

Feature: Add Orion BMS support

---

Software/USER_SETTINGS.h
Software/src/datalayer/datalayer.h
Software/src/devboard/webserver/can_replay_html.cpp
Software/src/devboard/webserver/can_replay_html.h
Software/src/devboard/webserver/webserver.cpp

This PR implements a new feature, CAN log replaying via Webserver
Awesome reverse engineering tool
Added a new page called "CAN Replay", where you can upload .log files and play them back towards an interface. Both normal CAN and CAN-FD is supported. You can also tick the "Loop" checkbox, to have the replay start over automatically when reaching the end.

Feature: CAN log playback via Webserver

---

Software/src/devboard/utils/events.cpp
Software/src/devboard/utils/events.h

This PR removes the EEPROM event log
It is not used and too difficult to maintain
Delete, delete, delete

Remove EE event log

---

Software/src/lib/adafruit-Adafruit_NeoPixel/Adafruit_NeoPixel.cpp
Software/src/lib/adafruit-Adafruit_NeoPixel/Adafruit_NeoPixel.h
Software/src/lib/adafruit-Adafruit_NeoPixel/esp.c

Reverts dalathegreat/Battery-Emulator#954
This was a bad change that caused performance issues. Reverting this PR
If I revert the changes, the 10ms function timing drops from 2008us -> 430us

Revert "Update Adafruit_NeoPixel library to commit fd74287"

---

Software/USER_SETTINGS.h
Software/src/battery/PYLON-BATTERY.cpp

This PR implements support for running 2x Pylon batteries at the same time
Fixes https://github.com/dalathegreat/Battery-Emulator/issues/966 , user requested feature
DOUBLE_BATTERY option can now be used at the same time as PYLON_BATTERY

Feture: Add double Pylon battery support

---

Software/src/battery/MEB-BATTERY.cpp
Software/src/datalayer/datalayer_extended.h
Software/src/devboard/webserver/advanced_battery_html.cpp

Add welded contactor status to webpage.
It was missing.
Add status to extended datalayer. Display status on webpage.

MEB: Add welded contactors status to webpage

---

Software/Software.ino
platformio.ini

This PR aims to improve overall performance of the code
Less chance of timing issues
The following optimizations are done:
- Remove unused int64_t task_times_us for reduced memory usage
- All time measurement places are now wrapped in ifdef FUNCTION_TIME_MEASUREMENT blocks, to prevent unnecessary function calls to micros, reducing CPU usage
- ESP32 platformio file updated to v3.2.0

Improvement: Performance and cleanup

---

Software/src/devboard/mqtt/mqtt.cpp
Software/src/devboard/webserver/webserver.cpp

Fix a bug in MQTT status generation caused the task to hang/crash and WDT timeout.
Correctly iterate the table of battery info.

Fix mqtt status generation crash

---

Software/src/devboard/mqtt/mqtt.cpp

Fix for memory leak in mqtt message receive function found by @kyberias

Bugfix for mqtt memory leak

---

Software/src/charger/CHEVY-VOLT-CHARGER.cpp

This PR fixes the Chevy charger debug logging. Fixes #1133

Fix Chevy charger logging prints that fail the build

---

Software/src/devboard/mqtt/mqtt.cpp

CPU temperature is published as MQTT topic.

Publish CPU temperature to MQTT

---

Software/src/lib/bblanchon-ArduinoJson/ArduinoJson.h

This PR updates the library ArduinoJSON that this system depends on
To take advantage of the latest crash fixes, it also reduces memory fragmentation and overhead in resource-constrained environments
We update from 7.3.1 -> 7.4.1

Library: Update ArduinoJSON to 7.4.1 :scroll: 

---

Software/Software.ino
Software/src/battery/BATTERIES.h
Software/src/battery/DALY-BMS.cpp
Software/src/battery/KIA-E-GMP-BATTERY.cpp
Software/src/communication/precharge_control/precharge_control.cpp
Software/src/communication/precharge_control/precharge_control.h
Software/src/devboard/wifi/wifi.cpp

This PR reduces amounts of millis() function calls
millis() calls take performance. The less you do this, the better
We instead pass the time from the main loop onto the functions

Improvement: millis() reduction

---

Software/src/devboard/webserver/advanced_battery_html.cpp

Include a header file to fix #1184

Fix advanced battery settings web page

---

Software/src/inverter/SOFAR-CAN.cpp

Improved high byte and low byte order when sending to Sofar

Sofar: sending correct values ​​to the inverter

---

.github/workflows/compile-all-batteries.yml
Software/src/battery/GEELY-GEOMETRY-C-BATTERY.h

This PR fixes the compilation errors of the Geely Geometry C battery.
It must be possible to compile all battery code.

Fix Geely battery compilation

---

Software/src/battery/BMW-IX-HTML.h
Software/src/battery/BMW-PHEV-HTML.h
Software/src/battery/MEB-HTML.h
Software/src/battery/NISSAN-LEAF-HTML.h

This PR prevents out of bounds array access on the HTML pages
Fixes #1202 , webserver no longer crashes if an unexpected value occurs
Instead of using const char* array[ ] , we use switch statements with a default, to prevent array overruns. eg.
switch(value){
case 1: content+="first string"; break;
default: content+="??"; break;
}

Improvement: Make Webserver More Battery Info page more crash proof

---

Software/USER_SETTINGS.h

This PR updates note on how BATTERY_WH_MAX works
Less confusion
Better comment

Improvement: Update USER_SETTINGS.h note

---

.github/workflows/compile-common-image-lilygo-logging.yml
Software/src/battery/BMW-IX-BATTERY.cpp
Software/src/battery/BMW-PHEV-BATTERY.cpp
Software/src/battery/IMIEV-CZERO-ION-BATTERY.cpp
Software/src/battery/KIA-E-GMP-BATTERY.cpp
Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp
Software/src/battery/MEB-BATTERY.cpp
Software/src/battery/MG-HS-PHEV-BATTERY.cpp
Software/src/battery/RENAULT-KANGOO-BATTERY.cpp
Software/src/battery/VOLVO-SPA-BATTERY.cpp
Software/src/battery/VOLVO-SPA-HYBRID-BATTERY.cpp
Software/src/charger/CHEVY-VOLT-CHARGER.cpp
Software/src/inverter/FOXESS-CAN.cpp
Software/src/inverter/SOLAX-CAN.cpp

Fix build when logging enabled.
This PR adds the missing header file references for files that start logging only when DEBUG_LOG is defined.

Fix build when logging enabled and add workflow that uses logging

---

Software/src/devboard/webserver/webserver.cpp

Fixes the equipment stop button and removes dupe code.

Fix equipment stop button and remove dupe code

---

Software/src/lib/bblanchon-ArduinoJson/ArduinoJson.h

This PR updates the library ArduinoJson from v7.4.1 to v7.4.2
Latest libraries are always preffered, to stay on top of bugfixes

Library :scroll: Update ArduinoJson to v7.4.2

---

Software/src/battery/KIA-HYUNDAI-64-BATTERY.cpp
Software/src/battery/KIA-HYUNDAI-64-BATTERY.h
Software/src/battery/KIA-HYUNDAI-64-HTML.h
Software/src/datalayer/datalayer_extended.h

This PR extends the info shown in the "More Battery Info" page for Kia/Hyundai 40/62kWh batterieis
User requested feature on the Discord server
Bonus: Obsolete USB logging removed

Kia/Hyundai 40/62: Add more info to "More Battery Info" page

---

.github/workflows/release-assets.yml

This PR adds a workflow to build images and add them to release as assets.
Each release should have an easy way to download the built images.

Add release assets workflow

---

.github/workflows/release-assets.yml

This PR updates the name of the secret used by the release asset updating workflow.

Update secret name

---

Software/src/devboard/webserver/settings_html.cpp

This PR increases the max kWh that you can configure a system to
Fixes #1354 , user requested change
120kWh limit is raised to 400kWh

Increase max capacity from 120kWh to 400kWh

---

Software/src/battery/VOLVO-SPA-BATTERY.cpp
Software/src/battery/VOLVO-SPA-BATTERY.h
Software/src/battery/VOLVO-SPA-HTML.h
Software/src/datalayer/datalayer_extended.h

This PR implements improved HVIL detection for Volvo SPA platform
Easier troubleshooting of why contactors dont close
The status of A / B / C connectors can now be seen in the More Battery Info page

Volvo SPA: Add HVIL status to More Battery Info page

---

Software/src/battery/KIA-E-GMP-BATTERY.cpp
Software/src/battery/KIA-E-GMP-BATTERY.h
Software/src/devboard/webserver/settings_html.cpp

This PR adds the same configurable limits as in https://github.com/dalathegreat/Battery-Emulator/pull/1487 for Kia eGMP platform
Forgotten during development
Same as in https://github.com/dalathegreat/Battery-Emulator/pull/1487 !

Improvement: Add estimated charge setting for Kia eGMP

---

Software/src/battery/BATTERIES.cpp
Software/src/battery/BATTERIES.h
Software/src/battery/Battery.h
Software/src/battery/RIVIAN-BATTERY.cpp
Software/src/battery/RIVIAN-BATTERY.h
test/CMakeLists.txt

This PR implements adds support for "[Rivian R1T large 135kWh batteries](https://github.com/dalathegreat/Battery-Emulator/wiki/Battery:-Rivian-R1T)"
User requested feature on the Discord :raised_hands:

New Battery! :battery: Add support for Rivian batteries  :battery: 

---

Software/src/battery/BATTERIES.cpp
Software/src/devboard/webserver/settings_html.cpp

This PR refactors the Settings page with cards
Grouping together settings options makes it easier for user to configure the software

Improvement: Refactor Settings page with cards
